### PR TITLE
Add new condition to check the zoom of a layer

### LINKED ISSUE #3314: Add "Camera Zoom" condition
## Description

There is no camera zoom condition, only a camera expression. This feels strange because there are conditions for every other or most other main camera parameters like X position, height, angle etc. and only zoom is missing. I think this should be added because for example newer users likely aren't familiar with the expressions available, search for "zoom" in the conditions and won't find anything when there actually is an expression for it.

## Solution suggested

Add a CameraZoom(*Layer*, *Camera*) condition

## Image

image

### PR DESCRIPTION
**Pull request by tristanbob**
Fixes #3314.

Example game:
[Add Camera Zoom Condition.zip](https://github.com/user-attachments/files/16077613/Add.Camera.Zoom.Condition.zip)

Video:
https://github.com/4ian/GDevelop/assets/8879811/d998b2ee-1dd4-48ab-98d7-bcccba9145f3

### CODE REVIEW

**Review by ClementPasteau — APPROVED** [review]
Lgtm! nice!

**Comment by 4ian** [comment]
Just chiming in: there was no way to make this as a `addExpressionAndCondition`?

**Comment by tristanbob** [comment]
There was an existing expression so I only added a condition. 

If you want, I can investigate using the newer combined method.

**Comment by 4ian** [comment]
I think we might be able to merge this new condition and the existing expression into a single `AddExpressionAndCondition`. It would not serve any purpose apart from refactoring the code (and ensuring for the future a perfect consistency between the condition and the expression).

The action is sadly not named "SetCameraZoom" but is named "ZoomCamera", so it won't work with `AddExpressionAndConditionAndAction`. Well, we could use it and deprecate "ZoomCamera", but I think it's not pragmatic.

Give a try to `AddExpressionAndCondition` to see if it works :)

**Pull request merged**
