### PR TITLE
Fix light ambient color action

### LINKED ISSUE #2734: "Set the ambient light color" does not accept "0;0;0".
## Describe the bug
The "Set the ambient light color" action cannot set RGB to "0;0;0".
Similarly, "1;0;0" and "0;0;1" are not set to the correct colors.

## To Reproduce
1. Add lighting layer.
2. Set a value that contains 0 in the "Set the ambient light color" action.

I used version 5.0.0-beta110.

### PR DESCRIPTION
**Pull request by Bouh**
Fix #2734

I have to said there is an error on master after npm install and launching GD:
image

### CODE REVIEW

**Comment by 4ian** [comment]
You need to run npm install ;)

**Comment by Bouh** [comment]
Wait before merging, i'm missed something with colors.

> You need to run npm install ;)

Already done twice :s

**Comment by 4ian** [comment]
> Already done twice :s

Have you run again npm start?

**Comment by Bouh** [comment]
It works with `yarn install`, `npm install` doesn't works fine, I'll update my workflow under Yarn.
My script was working with `npm install` and `yarn start` I'll unify everything.

Fix is apply on hot reloader.

**Comment by Bouh** [comment]
I've added a time ago in `GDevelop/.git/info/exclude`
```
newIDE/electron-app/package\.json
newIDE/app/package-lock.json
```
Because each time I run npm/yarn install, packages files are updated and goes in unstaged files
image
Every time I need to unstage them.

**Comment by 4ian** [comment]
I went ahead and made a fix where I still keep passing the R/G/B color as integers. In general it's a good idea to avoid passing colors-as-strings ("123;123;123") in the game engine because this is not an efficient representation (takes a lot of memory, need parsing. Better use 3 integers or one integer ("hex"))

**Comment by 4ian** [comment]
> Because each time I run npm/yarn install, packages files are updated and goes in unstaged files

That's weird! I just ran npm install in `GDJS` and there is no change to the package-lock.json. What is your node/npm version?

**Pull request closed without merging**
