### PR TITLE
Add word wrapping option for Text Object

### PR DESCRIPTION
**Pull request by Lizard-13**
It's just a graphical feature, you can't get the number of wrapped lines.

### CODE REVIEW

**Comment by 4ian** [comment]
Looks good for the code! Great job 👍
I wonder if there is something to be done when an instance of a text object on the scene has a custom size: should we detect this and make the object to have the same wrapping width as the instance custom width? (let's forget about height)

 Technically, this could be implemented with `extraInitializationFromInitialInstance` for `gdjs.TextRuntimeObject` (see example in `gdjs.TiledSpriteRuntimeObject` and other objects) where we can call setWrappingWidth if there is a custom size). For the IDE instance renderer, an extra check on `this._instance` to see if there is a custom size and then set the wrapping width as well.

Could be useful I think and seems feasible - what do you think?

**Comment by Lizard-13** [comment]
I had the same idea, you know?, but then realized that custom size is not passed to the text object, and I was fearing to mix non-related things. But if you think it's ok I could do it, and then just remove the "Wrapping width" option from the editor, it looks ugly.

Also, I was thinking on adding a small graphic line in the instance renderer to show the wrapping width, but right now you're using a single PIXI objet to render each instance. Using the custom width would be cool here too, because the text wrapping width would be displayed in the editor through the collision mask (we have to store the custom size in the text object json too, I think it isn't saved right now).

**Comment by 4ian** [comment]
> then just remove the "Wrapping width" option from the editor

I think we can remove it in this case, if we're considering that wrapping will be set by the instance width :) (or by using events).

> Also, I was thinking on adding a small graphic line in the instance renderer to show the wrapping width, but right now you're using a single PIXI objet to render each instance

If needed you can change the object to be a PIXI.Container, which can contain multiple PIXI objects inside.
But I think it's not necessary if we use the instance width :)  

> the text wrapping width would be displayed in the editor through the collision mask

Yes that's the good part! :)

> (we have to store the custom size in the text object json too, I think it isn't saved right now).

What do you mean?
In any case, we can keep the wrappingWidth and wrapping attributes that you added to TextObject. If we don't display them in the editor, we consider that all text objects are not wrapped by default (which is fine :)). Then it's up to the user to modify the width of instances of the text object if he/she wants the text to be wrapping (or use events if this need to be changed in the game, even if it's less likely :))

**Comment by Lizard-13** [comment]
> What do you mean?

Oh, I don't know why I thought the custom size was not serialized nor passed to the instances if it was a text object, that's why I not implemented it in the first place :P

I'm on it

**Comment by Lizard-13** [comment]
Wait, @4ian, if we use the custom size and custom width as wrapping in the editor, and convert this data to wrapping in the runtime object, we could just remove the wrapping properties set in TextObject.h/cpp files and don't serialize it at all...
I guess we can close the GDevelop.js pull request, no?

**Comment by 4ian** [comment]
That's true! GDevelop.js pull request is then not useful. That will keep things simple!
At least know you're able to compile it, can be useful for other things in the future 👍

**Comment by Lizard-13** [comment]
selfdisappoint

**Comment by Lizard-13** [comment]
Ok, it should use the custom size now, I've updated the text instance renderer on the IDE so the position is updated after changing the object size.

**Comment by 4ian** [comment]
Sorry about this I know it's frustrating to spend time like this when it's to remove the code then :/ 
But that looks good though now! :) Let me double check and merge this tomorrow! :)

**Comment by Lizard-13** [comment]
Don't worry man, just kidding, supper happy to make it to work actually :D

**Comment by 4ian** [comment]
Merging this now as it looks good! Thanks for working on this 👍

**Comment by blurymind** [comment]
Thank you @Lizard-13 awesome feature :D 👍

**Comment by blurymind** [comment]
skeleton in gd5 would be amazing! :D

**Comment by blurymind** [comment]
@Lizard-13 this is literally the most exciting feature for me to have in gd5.
Thank you for doing this.

**Pull request merged**
