### PR TITLE
New action/condition editor (to be activated in preferences for now)

### PR DESCRIPTION
**Pull request by 4ian**
This is an updated/reworked action/condition editor based on the discussions in https://trello.com/c/sRlxFnwh/303-redesign-the-action-condition-editor-dialog-to-choose-objects-first and https://github.com/4ian/GDevelop/issues/1153

* The idea is to have first the object that is the "target" of the action/condition to be chosen (or the object group).
* At the same level, by a click on the tab "Non objects and other actions" (or conditions), the user can browse the list of actions/conditions not related to an object. This make the discovering of "non objects" extensions like File system by @Wend1go, Dialogue Tree by @blurymind easier or others like Shopify, Facebook Instant Games, etc.. much easier as the list is less long.
* Once an object is chosen, we go to a similar view as before but:
  * Actions/conditions are displayed without "accordions"/tree. They are grouped and separated by headers in the list. This allow to directly see their icon and names. By just scrolling, you have an idea of **everything** you can do with your object.
* If an "non object" action/condition is chosen, the second step is just the list of parameters.

In terms of usability:
* This is still hiding the events sheet - but it's not worse than before.
* There is a search field in the first step. Search is done inside everything: object, groups and "non object" actions/conditions. Pressing Enter allow to select the first result.
  * This actually make things faster compared to before, because **you can start typing your object name** and press Enter.
  * **Tags** are supported so it's better for big games where you added tags and have a huge object list.
* There is the same search field as before in the second step (if you've chosen an object). It searches inside the object actions/conditions. Pressing enter allow to select the first result.
  * This is as good as before - but I added icons in the results :) Pressing Enter select the first result.

This surely need **polishing and feedbacks** but I believe this will be a step forward in terms of productivity, discovery and intuitive learning. Feel free to give it a try if you can check out the branch.

Note that if we want to make this the default editor, tutorials will have to be adapted. This is why it will be **first rolled out as an option** in the preference, so that users opt in (and new user are not lost).

TODO:
- [x] Check the TODOs in the code
- [ ] Pressing Enter after choosing an object action/condition should focus the first field (add a small timeout?).
- [x] Ensure a minimum height even when no search results?
- [x] Verify the scope of the object action/condition - I've seen "private" properties of behaviors visible in the scene events sheet which should not be the case.
- [ ] Mark certain conditions like the "Collision" condition as to be displayed inside object conditions (right now it's a "non object" condition, but this is surely confusing).
- [ ] See how to reorder the list of "non object" conditions? Skip the accordion?
- [x] Back button should go back to the same tab (to allow quick exchange between action/conditions).
- [x] Fix display issue when the object list is empty

### CODE REVIEW

**Comment by 4ian** [comment]
First screen:
Screenshot 2019-07-23 23 57 32

Searching (notice that no more tabs):
Screenshot 2019-07-23 23 57 48

Finding an action:
Screenshot 2019-07-23 23 57 58

Second screen for object:
Screenshot 2019-07-23 23 58 27

Searching:
Screenshot 2019-07-23 23 59 15

Second screen for other actions/conditions:
Screenshot 2019-07-23 23 59 24

**Comment by blurymind** [comment]
It would be nice if we can still change an object after it's parameters
have been set - the way we can atm. Being able to swap objects like that is
an advantage that we lose with this. That is why in my suggestion I offered
that we keep our parameter editor, while introducing a new component for
selecting an object and it's action which would then open the old editor
with the action and object set for you. This seems to have removed the
object selector field.

Looking at the screenshots, the listed items don't appear to be
alphabetically sorted, so the reason that drove me to open the issue in the
first place doesn't seem to be resolved with this new design

**Comment by blurymind** [comment]
Splitting them into tabs just adds more clicks to the process too. We want less clicks, not more :)

**Comment by blurymind** [comment]
I guess we could still swap out objects in the event sheet, so we are not going to be losing that one completely I guess.

**Comment by 4ian** [comment]
> I guess we could still swap out objects in the event sheet, so we are not going to be losing that one completely I guess.

Yep, that was my main point: it's already faster to use this, so it's perfectly fine to have a slightly longer process if you want to change object. Because it's not the main use case of the dialog, so optimizing for this would lead to de-optimizing for the other main use case, which is building an action/condition from scratch.

> Being able to swap objects like that is
an advantage that we lose with this

You can still click on Back, enter your new object name, press Enter, done :) So it's one more click, totally worth it for something that is not the main use case I think?

> Looking at the screenshots, the listed items don't appear to be
alphabetically sorted

Right, I can sort them but I was wondering if there was not a better way, which is the most used actions/condition categories first.

> Splitting them into tabs just adds more clicks to the process too. We want less clicks, not more :)

It's just one more click, and power users will use the search :) I think it's totally worth it for the cleanliness that is offered by having these actions/conditions separated from the rest. It make the old editor looks very odd at messing everything on a single screen.

> If I type position, will the search yield all actions related to position even when they don't have the word position in their names?

The search criteria stay the same: it's searching in `displayedName` (the name shown on screen) and 
`fullGroupName` (`the/name/of/the group` leading to the action/condition). So if your group contains "position", yes everything related to this will be shown.
I don't think we should add something else because it would make search show too much unrelated things?

**Comment by Bouh** [comment]
Back button :| bruuuh
I prefer list and parameters instead back button for edit the condition/action, back button is good just for go back to the object selection.
And also for the reasons to change action without losing the parameters.

And you can see at 7seconds we have a display issue. 
https://youtu.be/YdlrZPNh_Do

**Comment by blurymind** [comment]
I was hoping for something more menu like and less wizard like in order to
have less mouse travel around the screen. Does the back button lose your
action selection and entered parameters?

Anyways please consider the sorting. For a smarter list that adapts to user
selection, that would be where a tab of most used would make more sense
than most often used. In any case a combination of most often used and
alphabetical could also be nice?

**Comment by 4ian** [comment]
Right I've never tried on an empty game! Hence the display issue.

> I prefer list and parameters instead back button for edit the condition/action, back button is good just for go back to the object selection.

Right now there is an issue where the back button is always sending back to the list of objects. If we go back to the proper tab, that should allow for quick switch between actions/conditions?

I understand that you would like to be able to switch quickly, but I'm not sure how to achieve this while keeping a proper separation that is needed between objects and other actions/conditions and not having a huge overwhelming window.

I've added these checks to fix both of these issues:

- [ ] Back button should go back to the same tab (to allow quick exchange between action/conditions).
- [ ] Fix display issue when the object list is empty

**Comment by 4ian** [comment]
> Does the back button lose your action selection and entered parameters?

Your parameters are still there :) But the selected action is lost. I could make it preselected if you click on back? Maybe even scroll to it.

> In any case a combination of most often used and alphabetical could also be nice?

Some UX people would yell at us for doing that I think, because we're changing the list ordering, so destroying any hope of muscle memory. "Argh GDevelop moved this category agaaaain staahp" 😄

**Comment by blurymind** [comment]
How about a list that at the top shows a top 5 of most used objects and after those 5, shows the rest in alphabetical order? Just another idea of getting the best of both worlds

**Comment by 4ian** [comment]
> How about a list that at the top shows a top 5 of most used objects and after those 5, shows the rest in alphabetical order? Just another idea of getting the best of both worlds

Oh sounds like a great idea to me!
We can actually use the grey subheaders for separating the "Top 5" from the rest. As for the ordering, I can imagine using something like "[frecency](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Places/Frecency_algorithm)". Basically a simple algorithm that rate the action/conditions used recently to create a top 5.

**Comment by 4ian** [comment]
Or actually just the last 5 used objects and action/conditions. The idea is that if you used an action/condition, you might want to use it again soon.

**Comment by Bouh** [comment]
I suggested this : 

We keep back button just for back to the object list.

1 - Object selection
object_1

2 - Actions for this object
object_2

If we click on back button you go back to 1, and if you choose non-object you got this.
non_object

We refresh list on left if we choose object and parameters are always on right.

**Comment by Bouh** [comment]
I know the empty area is bad but my "1 - Object selection" can be your "first screen" like you wish

**Comment by blurymind** [comment]
Wouldn't it be better to show more objects in a grid instead of a list. If
it's a list it doesn't have to be so wide and cover the whole event sheet

**Comment by Wend1go** [comment]
One small addition. Could you add an additional column to the object list and show the object tags that are assigned to the objects?
Often one sprite/frame is used on different places (like a coin that can be picked up in the level and a coin in the HUD displaying the already collected coins, etc.). This way it would be easier to distinguish between similar objects in the list.

**Comment by 4ian** [comment]
I see the idea, let me check if material-ui's ListItem support this usecase :) What to do though if there are too many tags to display?

**Comment by blurymind** [comment]
@4ian I don't understand why you want to split this like this even more. Look at all the wasted screen estate:
wasted

You can use the space AND get rid of the back button and the extra clicks:
noBackButtons

**Comment by 4ian** [comment]
> Not downgrade the desktop experience

Just to be clear: I am *not* trying to downgrade anything - on the contrary I want to get something better :) 

>  The menu does not need to be stretched to full width like this. It feels like a bad design

I agree that it's too stretched, but this might be because in the previous version it was stretched because we need this space. Now we don't need to stretch the whole dialog, because it's clean and does not have too much information at once.

> You can use the space AND get rid of the back button and the extra clicks
> No forward buttons, no back buttons - one simple dialog :)

But you're not saving click in the "dialog with 3 part" mockup, right? You still have to: 
1) click in the first part on your object, 
2) then click on the action/condition, and 
3) then finally you get the parameters, right? 

* This is the same amount of click in my solution :) The only difference is that I did a separation between the first step and the second step (more about this later).
* There is no forward button in my solution. It's *not a wizard* dialog!

Not saying that your mockup is bad, but we actually don't have more clicks with the solution in my PR :) I think it's important to mention because I see a lot of "too much clicks" in the feedbacks.

Anyway, maybe we should just try on the field how this is working so far?

I'm afraid that we're optimizing for the "number of clicks" and are biased because we are so used to the existing editor. As experienced users of GDevelop, you see that you'll have to do one more click to select your object. This is not how we must think, because this extra click on the object, you would have done it in the old editor too :)
I understand that you might not like the "separation", but let's reflect on the use cases again of this dialog. When are we using this dialog?

* Case 1: when we're creating a new action.
  * With the old version, 1 to choose a category, 1 to choose the action, 1 or keyboard to choose the object.
  * With the proposed version, 1 click to choose the object, 1 to choose the action (because no more categories).
* Case 2 : when we're editing an action, by double clicking on it.
  * With both versions, you can edit parameters directly, apart for the object name.
  * With the old version, advantage: you can edit the object name.
  * With my proposal, **disadvantage**: you cannot edit the object name (but read case 3). 
* Case 3: we want to edit the object
  * Use the events sheet directly, fastest solution in all cases.
* Case 4: we want to change the action/condition to use a slightly similar one. For example, change from position x to position y.
  * Old version: 1 click (though you have categories that might need more clicks)
  * New version: 1 click if you're an object. 1 click on back and 1 click on the proper action/condition (**disadvantage**). 
* Any other cases? I think I've covered everything (creation, edition, edition of object, edition of the action/condition itself)

I understand that your latest mockup would unify all in a single dialog, so that the extra click on back and edition of object name would be 1 less click.
But is the added conveniency worth it, when it comes to deal with a dialog that is composed of 3 sections? (and questions to come with it, like what happen if I chose an action that is not compatible with the new object I clicked on?)

**Comment by 4ian** [comment]
Just to let you know, this feature is really draining my energy because I spent a bit of time on it and a lot discussing before doing it on Trello and now discussing again - without finding any mockup or solution that is 100% satisfying for everyone.

I have the feeling that there is no ideal solution - if you have one feel free to mockup it up but taking into account everything that I will need to do, including:
* The appearance of it on a resized, smaller window (~600px width)
* The fact that it must work for new conditions/actions and existing ones
* The fact that it must let the user choose an object first, or a non object action/condition.
* The fact that action/condition can be changed.

Remember that when implementing it, I have to make absolutely all interactions work, so I can't just start implementing a mockup and discover that some thing are missing or not working or look ugly on a small screen.

For the time being, I'm going to take a bit of rest on this and make a first finished version on which we can iterate - but later :)
Otherwise, I'm feeling like I'm losing a lot mental energy arguing about choices rather than actually implementing a solution that will be better for all users.

**Comment by 4ian** [comment]
I also realized that I may not have been clear on the flow using my current proposal. Here are two GIFs for the case of adding an action:

Object action:
NewInstructionEditorDialog_player

Non object action, using search (otherwise you have to browse in the list in the second tab):
NewInstructionEditorDialog_timeScale

**Comment by Bouh** [comment]
I will think about these specifications and make sure to keep as much as possible your proposals.
I have some new ideas. I'll put it in pictures for each case.

**Comment by Wend1go** [comment]
I think we should keep @4ian 's current approach and try it out in a real project. After that, we can start adjusting things. According to the GIFs it already looks like a big improvement.

Talking about the tags, we could use the wasted space at the right of the object list to show some more details about the object (at a later date). Like Tags, Layer, Size, Variables etc.

**Comment by 4ian** [comment]
@Bouh Sure, thanks for your time on this as well as @blurymind on your feedbacks. To be clear, I absolutely value and appreciate your time making feedbacks and suggestions on this :) As this is an important and hairy issue, any mockups/examples covering most cases is highly appreciated.

I've been thinking about it and I would be keen to try something that is responsive, i.e: on a large screeen we have a "2 or 3 column layout" like in blurymind latest posts. But this is more work to this so I want to be sure before doing anything :)

> I think we should keep @4ian 's current approach and try it out in a real project withing the next Beta. After that, we can start adjusting things.

I want to release a new beta in the next days - because it has been a while and there are interesting things waiting for being released in master :) This will probably be in it - but again this is not definitive and will be improved.

> Talking about the tags, we could use the wasted space at the right of the object list to show some more details about the object (at a later date). Like Tags, Layer, Size, Variables, attached behaviours etc. when hovering over an object in the list.

Behaviors can be especially interesting, i'll think about that too (though not sure what we should show first, but the idea is interesting).

**Comment by Bouh** [comment]
I propose three schematics.
The red paths are the main paths.
The blues are paths for "back" buttons.

1 - The closest to the current system of @4ian in this PR.
2 - Make your choice before in eventsheet with two links (New system)
3 - The column system of @blurymind on steroid, with tabs.

I prefer the 3th choice with selections by default for avoid empty area.

Image is huge 10700x11000px so here a external link
[https://i.imgur.com/nHFazLk.jpg](https://i.imgur.com/nHFazLk.jpg)

**Comment by blurymind** [comment]
Here is another mockup, this time more inline with @4ian 's design and 1 modal dialog:
1. initial:


2.
Screenshot 2019-07-23 23 58 27

**Comment by Bouh** [comment]
@4ian @blurymind you will receive an invitation to edit the mockup at this address:
https://app.creately.com/diagram/j3MeOGcKGZh
I've just added the 4th mockup, which is the current system in this pull request.

@Wend1go  i don't have your mail, i can't invite you :|

**Comment by 4ian** [comment]
I've updated the new editor with some things that will interest you for sure ;) This is a mix of Bouh third suggestion and the original proposal + the idea of having everything visible, as possible by the screen size.

* Reponsive size: 
  * if opened in a large window (>1150px width window), you'll have a **2 (or 3) columns view** (**"View everything at once"**). There will be the object/other actions/conditions column on the left. The rest is blank first on the right, then show the parameters and optionally an intermediate column with object actions/conditions. No back button ;)
  * if opened in a medium window (>750px and <1150px), you'll have the list of objects/other actions or conditions alone first, then when selected, the parameters with optionally the left column with the object actions/conditions. (**"intermediate view"**, as the original proposal)
  * if opened in a small window (<750px, typically a tablet or when docked to half a screen), you'll have all the "steps" shown one after the other (so if you select an object, then you have a screen with just the list of actions or conditions, then a final screen with just the parameters).
* As said, back button is gone on big screens.
* Parameters are kept even if you change object or action/condition (so that it's easy to switch between similar actions/conditions) (whatever the screen size).
* If you change to another object, the selected action/condition and parameters are kept (if the said action/condition is compatible with the new obejct) (whatever the screen size) (so that it's easy to change object).
* Selected tabs are kept when you click on back (so that you don't have to click again on "Other actions" tab on smaller screen if you go back to the first screen, to change to another action or condition).

* Finally, all of this should still be **novice friendly**, because when you add a new action or condition, even on large screen the right part is blank, so you choose first an object or an "other action".

A few examples:

"Large screen" with an object :
Screenshot 2019-07-27 18 55 28

"Medium screen" with an object :
Screenshot 2019-07-27 18 33 09

GIF with all 3 sizes used to add an object action:
NewInstructionEditorDialog_responsive

**Comment by blurymind** [comment]
@4ian this is absolutely beautiful. Thank you for working so hard  on this feature. With this last design I am positive that GD most probably has the best design out there for this feature. Not only does it execute it in the most intuitive way, but it also does it with the user's resolution in mind :)

**Comment by 4ian** [comment]
Glad that you're finding this to be a good solution :) Let's add this as an option into the next version  and see how it goes :)

**Comment by Bouh** [comment]
Thank you for this hard work! It's awesome, I can't wait to get feedback from users: D

**Comment by 4ian** [comment]
Still a few things to iron out:

- [ ] Pressing Enter after choosing an object action/condition should focus the first field (add a small timeout?) in all cases.
- [ ] Mark certain conditions like the "Collision" condition as to be displayed inside object conditions (right now it's a "non object" condition, but this is surely confusing).
- [ ] See how to reorder the list of actions/conditions (alphabetical sort for categories)

but we'll go ahead with this version so that it can be tested starting from next version :)

**Pull request merged**
