### PR TITLE
Simplify events sheet context menus

### PR DESCRIPTION
**Pull request by 4ian**
- Move zoom in/out to “events sheet”. Move “collapse” to Events Sheet.
- Move “Add …” into a single submenu.
- Remove undo/redo.

## Before:
image

## After:
image

## After (sub menus)
image
image
image

## For actions/conditions:

Cleaner with the undo/redo:

image
image

### CODE REVIEW

**Comment by D8H** [comment]
Zoom in and zoom out are not really contextual actions. I wonder if there should be somewhere else.
Do you know if parent items can have a shortcut? I think a shortcut to display the "Add" menu could be nice one day.

**Comment by 4ian** [comment]
> Do you know if parent items can have a shortcut? I think a shortcut to display the "Add" menu could be nice one day.

They can't, but we could have a command in the command palette + a shortcut to toggle a "Add event..." dialog that would list them.
We should also add shortcuts to add in a single key a new condition or action. But that can be done later :)

**Comment by 4ian** [comment]
Good remark, I will normalize to Title Case.

**Comment by 4ian** [comment]
@D8H 

There were actually 4 commands in the command palette to add an event, a sub event, a comment, and any event :) 
With shortcuts! (Shift + A, Shift + D, none, Shift + W, respectively). 

So I've fixed their display:
image
image

Also in this menu now:
image

**Pull request merged**
