### PR TITLE
Add 'StringList' as new parameter type for extensions

### PR DESCRIPTION
**Pull request by Wend1go**
There is just a small "uglyness" (see below)

### CODE REVIEW

**Comment by 4ian** [comment]
Sweet!
Two things as you can see on SemaphoreCI: https://semaphoreci.com/4ian/gd/branches/pull-request-911/builds/2

* Flow is warning you that `Cannot call parameterMetadata.getExtraInfo because property getExtraInfo is missing in undefined`
image

This means that you have to add a if case or handle in some way the case where "parameterMetadata" is undefined (which can happen if the field is used in some strange conditions).

* Run `npm run format`/`yarn format` to auto format your code.

Do you intend to use this soon for an extension? Or is it more to prepare things for later extensions?

**Comment by Wend1go** [comment]
I wanted to use it in the Tween extension. But I still need to do some research on how Tween.js works and how it best fits into the GD workflow.

I'll add the check and format this evening.
Did I get you right that `getExtraInfo()` will keep the `ExtensionName::` prefix for the foreseeable future?
In this case I would change the replace function into "rease everything on the left up to the double colon `::`.

**Comment by 4ian** [comment]
> Did I get you right that getExtraInfo() will keep the ExtensionName:: prefix for the foreseeable future?

No I think I'll remove the prefix (precisely, I'll apply the prefix only for parameters that are objects).

**Comment by Wend1go** [comment]
Ok done :smiley:

**Comment by 4ian** [comment]
FYI, I'll do the changes but got carried out by other things when working on translations :)

**Comment by 4ian** [comment]
I've fixed the "extra info" and added handling of "stringWithSelector", understood as a string by the game engine. "stringWithSelector" sounded better because the type sent to the JS function is a string, not a list/array of strings.

To use this:
- Merge master branch into your branch.
- Remove newIDE/app/srclibGD.js file
- Relaunch `npm run start` or `yarn start`.

Let me know if it works.
You'll have to change "stringlist" to "stringWithSelector" and rename your file for consistency. Apart from this, should work like before!

**Comment by Wend1go** [comment]
I couldn't find libGD.js under the path you mentioned. Or did you mean`GDevelop/newIDE/app/public/libGD.js`?
After removing the file it got downloaded again but when I parse extraInfo there is still the preceeding `ClassName::`
In other words, I couldn't test this yet.

**Comment by 4ian** [comment]
You have to merge master branch in your branch ;)

>you mean GDevelop/newIDE/app/public/libGD.js

Yes sorry, this file. Merge master, delete it and relaunch npm run start so that it get downloaded

**Comment by 4ian** [comment]
> I wonder if it is possible to edit the list of items bound to the StringListField from within the extension that uses it.

No easy way, we would need some kind of abstraction allowing to declare types of identifiers

**Comment by Wend1go** [comment]
Ok the items are correctly shown now.
But the returned value in my test extension is an empty string.
Have to go to work now, I'll look into this when I come home.

**Comment by Wend1go** [comment]
Guess I found the culprit. Will test it tonight.

**Comment by 4ian** [comment]
Oh thinking about it now, as this is considered as a string, you have to ensure that quotes are in your values: 

```js
        dataSource={this._choices.map(choice => ({
          text: choice,
          value: '"' + choice + '"',
        }))}
```

**Comment by Wend1go** [comment]
No, even with the quotes I still get an empty string.
grafik

**Comment by 4ian** [comment]
Sweet! Looks good for me to merge

**Comment by 4ian** [comment]
Ran Prettier on your file, remember to run `yarn format` before committing ;)

**Comment by 4ian** [comment]
Merged! Thanks for adding this and look forward to see it being used in the Tween extension :)

**Pull request merged**
