### PR TITLE
New expression parser

### PR DESCRIPTION
**Pull request by 4ian**
- [x] Write visitor for a tree of nodes (class with `virtual VisitXXX` for each kind of node).
- [x] Rewrite old "callbacks" to node visitor version...
  - [x] ExpressionCodeGenerator
  - [x] ExpressionObjectsAnalyzer
  - [x] ExpressionObjectsRenamer
  - [x] ExpressionObjectsRemover
  - [x] ExpressionParameterSearcher
  - [x] ExpressionValidator
- [x] ...and replace calls to old parser/callbacks by the new one in GDCore/GDCore/GDCpp.
  - [x] ExpressionCodeGenerator in GDCpp and GDJS (+ GenerateGetVariable/GenerateVariableXXX)
  - [x] Update the SetCustomCodeGenerator
    - [x] SetReturnNumber
    - [x] SetReturnString
    - [x] GetArgumentAsNumber
    - [x] GetArgumentAsString
- [x] Write visitor to get errors
- [x] Handle "optional" parameters like `MouseX(,)` (at least for proper code generation)
- [ ] Check if need to handle legacy "optional" parameters like `MouseX(,0)`
- [x] Add tons of tests:
  - [x] `-DeadFish.Variable(Speed)`
  - [x] `00.65`
  - [x] Add tons of fuzzy test to ensure no crashs 
- [ ] Replace calls to old parser by the new one in:
  - [x] IDE
  - [ ] Old IDE (replace CallbacksForExpressionCorrectnessTesting)
- [x] Check that error reporting in the IDE is enhanced with new error messages
- [x] Add colored red highlight at the position of errors in the IDE
- [ ] After release, update wiki to say that PointX and PointY need quotes.

### CODE REVIEW

**Comment by blurymind** [comment]
@4ian thank you for working on this. We spend alot of time in that expression parser, so improving it has big implications on the user experience 👍

**Comment by 4ian** [comment]
Yeah this will definitely bring lasting improvements to the user experience and unlock potential new improvements (highlighting, better error messages, etc...). Will make things more consistent also and error proof (some syntax error are not properly caught by the current parser).
Will probably need help to test the new parser - I've covered it with lots of tests but I'll provide a checkbox to still use the old parser as long as it's not tested on multiple games :)

**Comment by 4ian** [comment]
Should be almost ready :)

First addition that was made available by this new parser:
image
image
image
image

**Comment by 4ian** [comment]
I've added near "realtime" validations of expressions as the user type (with a small delay to avoid overloading the CPU with useless validations though). Should make working on expressions a much better experience :)

@blurymind @Lizard-13 @Wend1go and other following the development on GitHub:
I'm now wondering how to best handle the transition to the new parser. As this is a core element of the events, I've added tons of tests and I believe it's fully compatible with the old parser and bug free - but ideally we should test it on a good number of games. Even if it is much better quality and more powerful than the previous one, there could be some edge cases or bugs.

I think I'll upload a version of GD for testing purpose, so the community can give it a try.
I've added an option in the preferences to disable the new parser and go back to the old one, but ideally I would like to entirely remove the old parser and the deprecated associated classes from the codebase soon.

**Comment by Lizard-13** [comment]
At first I thought that the worst scenario would be it marking an error when there isn't one or vice versa, but if it's the guy that replaces invalid expressions with zero... Yeah, lets test it a lot :)

The transition is ok IMO, more people using it will report bugs faster, and with an option to switch back there's nothing to fear.

Just make sure everybody knows about the change and the setting to roll back.

**Comment by 4ian** [comment]
I've uploaded a *testing* version here:
* https://github.com/4ian/GDevelop/releases/download/v5.0.0-beta59/GDevelop.5-5.0.0-beta59-expressionparser2.0-win.zip (Windows)
* https://github.com/4ian/GDevelop/releases/download/v5.0.0-beta59/GDevelop.5-5.0.0-beta59-expressionparser2.0-mac.zip (macOS)
* https://github.com/4ian/GDevelop/releases/download/v5.0.0-beta59/gdevelop-5.0.0-beta59-expressionparser2.0.tar.gz (Linux)

This is built from this branch. Can anyone having some time download this version, run it and try a few games with it?
* In case you suspect there is something wrong - like the game is not behaving properly: check the expression is the related part of the game. You can go in preferences and uncheck the option to use the new parser:

image

Relaunch the preview of the game and see if it's better (beware, this option will only stay unchecked until the next time you restart GD!)

* Try to edit a few expression. In case something looks wrong, send me a screenshot. If the editor seems to freeze/crash let me know too (even if again there should be an extensive test coverage of the new parser).

**Comment by Bouh** [comment]
I will continue dev my game with this version, if i've a bug i will reported you here.
Maybe instead try each example one by one each time, maybe a exemple with all action / condition in needed ?
Instead tryed each example one by one each time, maybe a exemple with all action / condition is needed ?
With catch error for each event ?

**Comment by 4ian** [comment]
Not sure what you mean, you mean generating an example/sample game with all actions/conditions?
This is the expression parser so it's more related to expressions. I'm not that concerned with specific functions - because the only things that differ is their name and what they take as parameter. It would be more about some weird way of writing a formula, like things like "MouseX(,)" should theoretically not be supported (but it's ok as parameters are optional).

**Comment by Bouh** [comment]
(Indeed thit is not useful to make a example.)

About New expression parser :
It's not a bug but here a point that could be improved
Color
`"red"` Display nothing ❌
`red ` Display you must wrap inside double quotes  ✔
[The color picker can out off screen](https://i.imgur.com/axe3Ggm.png)

**Comment by 4ian** [comment]
Yes this is not a bug per se because colors are string expressions. There could a warning if there is no function call though and the color is not valid.

**Comment by Lizard-13** [comment]
Perfect!, have to click outside the expression editor to get errors was a bit cumbersome :)

**Comment by Lizard-13** [comment]
Just remember a crash case, tried it with your pre-built version and it is still broken, maybe it has been already fixed in later commits. Set an expression to `00.65` for example, breaks the game (multiple zeros before the decimal point) :)

**Comment by 4ian** [comment]
Ah nice, thanks for letting me know! Will check this. I have to rebase this branch and make sure there are no other cases like this which are broken :)
Will be good to go then

**Comment by 4ian** [comment]
@blurymind @Lizard-13 @Bouh @Wend1go @zatsme @KinkGD

I've uploaded a new version with the new expression parser. Would you take some time to try it?

Windows: https://github.com/4ian/GDevelop/releases/download/v5.0.0-beta61/GDevelop.5-5.0.0-beta61-expressionparser2.0-win.zip
macOS: https://github.com/4ian/GDevelop/releases/download/v5.0.0-beta61/GDevelop.5-5.0.0-beta61-expressionparser2.0-mac.zip
Linux: https://github.com/4ian/GDevelop/releases/download/v5.0.0-beta61/gdevelop-5.0.0-beta61-expressionparser2.0.tar.gz

This also contains all the new features since the latest beta, including the new physics engine and all (if there is any issue with these features, report on an issue like usual). 
As before:

Can you run it and try a few games with it?
* In case you suspect there is something wrong - like the game is not behaving properly: check the expression is the related part of the game. You can go in preferences and uncheck the option to use the new parser:

image

Relaunch the preview of the game and see if it's better (beware, this option will only stay unchecked until the next time you restart GD!). Report me any difference (with the game if possible :))

* Try to edit a few expressions. In case something looks wrong, send me a screenshot. If the editor seems to freeze/crash let me know too (even if again there should be an extensive test coverage of the new parser).

* The new parser should also fix a few bugs when renaming objects. You can try to rename an object and see if it's properly renamed in expressions in events.

**Comment by zatsme** [comment]
Will try it after work later 🙂

**Comment by 4ian** [comment]
@blurymind @Lizard-13 @Bouh @Wend1go @zatsme @KinkGD I've updated the testing version, same links:
Windows: https://github.com/4ian/GDevelop/releases/download/v5.0.0-beta61/GDevelop.5-5.0.0-beta61-expressionparser2.0-win.zip
macOS: https://github.com/4ian/GDevelop/releases/download/v5.0.0-beta61/GDevelop.5-5.0.0-beta61-expressionparser2.0-mac.zip
Linux: https://github.com/4ian/GDevelop/releases/download/v5.0.0-beta61/gdevelop-5.0.0-beta61-expressionparser2.0.tar.gz

PointX and PointY will now take the name of the point as a string, for consistency with the rest of the expressions.

**Any game saved with this version won't be compatible with the previous one**. Please make backups.
This is because all PointX/PointY expressions will be converted to take the argument as a string, so with quotes around it. If you use your game saved with this version with a previous version, you'll have to revert all the changes made to PointX/PointY so be careful ;)

Let me know if this is working properly for you.

**Comment by zatsme** [comment]
Quick test before work, no time for a better explanation so hope this helps!





So this is what you get in the asteroids example.... works fine

But if the user then changes the object thus



then saves, loads we end up with



So then take away the quotes from the point def, save, load and it gets worse!!



Now I do realise this is not a thing the user would probably do... but they might.

Would it not be better to not allow quotes in the point definition screen so this cannot happen?

**Comment by zatsme** [comment]
Could you :-

1: Remove quotes on loading old projects so they work without quotes.
2: Not allow quotes on the definition screen.

There's no real need to have quotes in a name, is there?

🤔

**Comment by 4ian** [comment]
No worries, it's my bad. I forgot to do the update of PointX/PointY **only once**. Right now, every time you're opening your game, your game is considered as having the old PointX/PointY, and get updated by having new quotes added.

Disregard this and don't save your game with this version.

**Comment by Lizard-13** [comment]
So point names? :open_hands:

**Comment by 4ian** [comment]
Yes :) Please don't abuse it 😄
In the future, constant text could be optimized to directly address object - even though the difference could be thin with using a string.

**Comment by 4ian** [comment]
@blurymind @Lizard-13 @Bouh @Wend1go @zatsme @KinkGD I've updated the testing version, you can verify it's the latest because in the "About GDevelop" dialog, you should see GDevelop.js **4.0.98** :)

This fix the issue of quotes "getting worse" shown by @zatsme. There should be no known bugs. Let me know if you find something suspect or not working.

**Comment by 4ian** [comment]
>To be fair though - sometimes you do want to have quotes in a string - so one can use an escape character (), which is exactly what gdevelop seems to have done in your use case.

Yes exactly, GDevelop is adding a backslash \ before your quotes to keep them.

> But in the case of naming points, I doubt anyone would need quotes there

It's true too that there is little chance a point have a quote. This being said, there is no issue allowing any character, as point names are now strings.
So you can have a quote but you'll have to "escape" it in the strings (like what GD is doing).

There was a bug in the conversion (the conversion to string was done again and again) but this is fixed now.

**Comment by Lizard-13** [comment]
@4ian Another one for you, I can't test it in your builds because I'm in a 32-bits machine out of the country so hopefully it's already fixed: Valid string expressions with invalid characters before them invalidate the entire scene user code, the scene turns into a static world, only affected by automated behaviors.
Examples: `="Scene"`, `letters"Scene"`, `evenWithSpacesBetween "Scene"`, `nonQuotedStringsToo VariableString(x)`

There is no problem if the invalid symbols are located after the strings (`"Scene"=` is OK).
There is no problem if there is no valid string at all (`invalidExpression withoutAValidString` is OK)

Reported here: http://forum.compilgames.net/viewtopic.php?f=19&t=11146

**Comment by 4ian** [comment]
I think the previous expression parser was particularly bad here and would let invalid expression and generate invalid JS code (I remember this happened for other things. Your expression would be invalid but improper code would be generated... crashing your whole game).

Normally, the new parser* and code generator will totally avoid this. I'll try these expressions to be extra sure but I'm confident that this will be caught :) (to be very precise, the parser is a "[Recursive descent parser](https://en.wikipedia.org/wiki/Recursive_descent_parser)", and only parse properly a "grammar" ensuring nothing that is invalid can goes unnoticed - making it strict while the previous parser was more a big hack).

**Comment by 4ian** [comment]
Found a bug! :'( 
Distance expression, and any expression using an object as parameter, is not working (crashing the game). Will release this once this is fixed.

**Comment by 4ian** [comment]
This looks stable enough according to beta 63, and I believe this properly cover all the use case of expressions in GDevelop and is well tested. Merging this now! 
Next step will be to remove the code of the old expression parser to clean the codebase after a few betas.

**Comment by 4ian** [comment]
Anyone working with GDevelop: when you update to latest master, please remove libGD.js in newIDE/app/public and relaunch `yarn start` or `npm run start`.

**Pull request merged**
