### PR TITLE
update piskel version

### PR DESCRIPTION
**Pull request by blurymind**
I made a new build of piskel based on https://github.com/blurymind/piskel/tree/piskel-plus (a300d17) here:
[piskel-editor.zip](https://github.com/4ian/GDevelop/files/3859182/piskel-editor.zip)

This PR updates GD to use that new build.

I've been working on piskel for a while, improving some of it's weak points. The new features are:
- color index shift brush (super useful for cell shading sprites) (1)
- ability to source all  layers when using the bucket tool
- palette transfer tool (apply the currently selected palette colors to the frame you are on) (2)
piskelNew

bucketToolSourcePiskel
piskelPaletteTool

### CODE REVIEW

**Comment by 4ian** [comment]
Thanks for these updates 👍
Looking at the folder, seems there are duplicate of some JS files and CSS files - there was only one CSS and two JS files previously, contrary to now where they are 2 and 4 respectively:

Screenshot 2019-11-17 15 09 13
Screenshot 2019-11-17 15 10 11

Can you ensure that you have a clean build of Piskel and reupload the zip? :)

**Comment by blurymind** [comment]
Ah sorry, I must have zipped the wrong thing. I will try to update it tonight

**Comment by blurymind** [comment]
@4ian I reuploaded it now :)

**Comment by 4ian** [comment]
I've uploaded it in beta 82 :)

**Comment by 4ian** [comment]
I've uploaded it in beta 82 :) 

You should be able to update the hash (put a fake hash package.json, console.log the real hash computed in import-zipped-editor, and then replace it again in package.json) and we're good.

**Comment by Bouh** [comment]
Because the hash is outdated, i cannot run dev env on my pc

**Comment by blurymind** [comment]
> I've uploaded it in beta 82 :)
> 
> You should be able to update the hash (put a fake hash package.json, console.log the real hash computed in import-zipped-editor, and then replace it again in package.json) and we're good.

How do I compute the real hash? I remember trying it with the zip last time and failing :) it has to be done on the folder instead of the zip file itself and needs to be sha256?

**Comment by 4ian** [comment]
import-zipped-editor is computing the real one, have you tried `console.log`to log it?
Update package.json to download the version stored in beta82, relaunch npm start, this will log you a warning about potential corrupted/tampered archive. Add a console.log at the right place in `import-zipped-editor` to see the hash the was computed for the folder.

**Comment by 4ian** [comment]
I'll do it if you don't manage to find the hash, probably tomorrow as I'm busy tonight though.

**Comment by 4ian** [comment]
Merged :) Thanks for improving Piskel!

**Comment by blurymind** [comment]
> Merged :) Thanks for improving Piskel!

Thank you for merging it :)  at least GD users will get the improvements

Piskel's author hasn't replied to my email or the pm on twitter. I wonder if its worth waiting a month more and then forking it into a new pixel editing app (someone on twitter suggested calling it Lexip xD )

in any case there appears to be interest in other people to improve piskel, but because nobody reviews code at the main branch, its been frozen

**Pull request merged**
