### PR TITLE
Add helpPagePath Video object

### PR DESCRIPTION
**Pull request by Bouh**
I have questions about the video object that I hope could be resolved if users use a help link that directs them to the wiki.

When I wrote the video extension the help path was added to the extension, but it seems that this path is not the same as the button for objects.

I saw that there is a button for the Skeleton object, I reproduced for the Video object but there are some things missing, it doesn't work.
I would need to be enlightened:)

### CODE REVIEW

**Comment by Bouh** [comment]
I found by mimicry, it's seem working well :)

**Comment by Bouh** [comment]
I found by mimicry, it's seem working well :)

**Comment by 4ian** [comment]
This works :) I'm thinking of an alternative where you can pass the helpPagePath as an argument: `getDefaultObjectJsImplementationPropertiesEditor({ helpPagePath:  "/test" })`.

This would require you to add an argument to getDefaultObjectJsImplementationPropertiesEditor and to change the 3/4 mentions to getDefaultObjectJsImplementationPropertiesEditor in the codebase: https://github.com/4ian/GDevelop/search?q=getDefaultObjectJsImplementationPropertiesEditor&unscoped_q=getDefaultObjectJsImplementationPropertiesEditor

That would be I think a bit better, because we would keep a simple method `getDefaultObjectJsImplementationPropertiesEditor` that we can easily search for, instead of having it existing but not used by any object.

**Comment by 4ian** [comment]
Basically:

```
  getDefaultObjectJsImplementationPropertiesEditor() {
    return {
      component: ObjectPropertiesEditor,
      createNewObject: object =>
        gd
          .asObjectJsImplementation(object)
          .clone()
          .release(),
      castToObjectType: object => gd.asObjectJsImplementation(object),
    };
  },
```

would be:

```
  getDefaultObjectJsImplementationPropertiesEditor(options) {
    return {
      component: ObjectPropertiesEditor,
      createNewObject: object =>
        gd
          .asObjectJsImplementation(object)
          .clone()
          .release(),
      castToObjectType: object => gd.asObjectJsImplementation(object),
      helpPagePath: options.helpPagePath,
    };
  },
```

Then make sure to replace all calls to `getDefaultObjectJsImplementationPropertiesEditor` in the codebase by passing options: `getDefaultObjectJsImplementationPropertiesEditor({helpPagePath: '/the/page'})`. Also update the mentions to it in the doc, and you're good! :)

**Comment by Bouh** [comment]
Why not use the helpPagePath from here 
https://github.com/4ian/GDevelop/blob/d1c6347f3d8456ea752ee0ff15c02387f2bc45df/Extensions/Video/JsExtension.js#L24

And this is just for JS extension, the other extensions in cpp have `SetExtensionHelpPath()` too.
Why set this path again when we have already.

This seems link the declarations made in an extension to the object editor in GDevelop.
Why make a bridge between both files?
I mean in an extension we can say directly which editor we need.
That way you don't need this file  ObjectsEditorService.js.
But i understand the entire role of ObjectsEditorService.js maybe :)

**Comment by 4ian** [comment]
> Why not use the helpPagePath from here

It would be the best solution, but that means that in ObjectEditorDialog you have to fetch the object metadata using `gd.MetadataProvider.getObjectMetadata`. I would also have to add `GetHelpUrl` in ObjectMetadata in Bindings.idl for libGD.js. Then we could use it to get the help url.

> I mean in an extension we can say directly which editor we need.
> That way you don't need this file ObjectsEditorService.js.

Extensions don't know anything about the IDE Javascript files, that's why this file is in the newIDE sources. Also this is necessary for extensions written in C++: you can't set in a C++ extension a JavaScript object to be used for the editor :)
Though I agree it would be better if we could remove this "bridge" entirely.

**Comment by Bouh** [comment]
> It would be the best solution, but that means that in ObjectEditorDialog you have to fetch the object metadata using gd.MetadataProvider.getObjectMetadata. I would also have to add GetHelpUrl in ObjectMetadata in Bindings.idl for libGD.js. Then we could use it to get the help url.

That adds code for little things, so let's start with the basic idea!
Existing file have been edited like you wish.
I've also added link to [wiki page ](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/extend-gdevelop)about the built-in extension for the object in `ExampleJsExtension`

**Comment by 4ian** [comment]
Sounds good, I've re-run Prettier with single quotes for the JsExtension.js file (looks like I need to add a config file somewhere for these files), merging now!

**Comment by 4ian** [comment]
Thanks for adding this 👍

**Pull request merged**
