### PR TITLE
Fix object name not being correctly cleared in ObjectGroup editor

### PR DESCRIPTION
**Pull request by arthuro555**
When selecting an object in the ObjectGroup editor, the text field should be cleared, as you can witness here:
https://github.com/4ian/GDevelop/blob/f83bea54c9601f3ded89e08a9c07beb0112b41df/newIDE/app/src/ObjectGroupEditor/index.js#L41-L43
This doesn't happen though, as when `onChoose` is called on the autocomplete, the new value isn't read from the props by setting the state `inputValue` to `null`. 

I toyed arround with the expressions autocomplete as I believe it is using the same component and I couldn't notice any regressions with those changes.

### CODE REVIEW

**Comment by 4ian** [comment]
Nice, can you try on a "touch screen", for example by using the Chrome devtools? The autocomplete should notably work when editing a parameter inline in the events sheet, I remember issues with this (you would select something and it would get discarded, etc...).
Would be good to verify all the use cases on a touch screen to ensure no regressions :)

**Comment by arthuro555** [comment]
I tried on my smarthphone browser and there was no problem in the inline popover autocomplete.

**Comment by 4ian** [comment]
Seems to work well, thanks!

**Comment by Bouh** [comment]
Close #2039

**Pull request merged**
