### PR TITLE
[VisualDebugger] Show objects position instead of origin.

### PR DESCRIPTION
**Pull request by D8H**
This the change for this proposition:
* https://github.com/4ian/GDevelop/discussions/3395

### CODE REVIEW

**Comment by Silver-Streak** [comment]
I didn't get a chance to respond in the discussion, but one of the main things when the visual debugger was getting added was to show all points. So the origin point *should not* be replaced as users will still need visual representation of its placement, although I agree showing the position point *in addition* is helpful

**Comment by 4ian** [comment]
Agree that we can probably:
- have "Position" as being the "unrotated, unscaled, unflipped" X;Y position of the object.
- In case the origin point is not at the exact same position, then we show it too. This can be the case for sprite objects that have a "origin" point, but which is impacted by the rotation/scale/flip.
  - When the origin is exactly at the object position, let's not show it to avoid cluttering the rendering :)

**Comment by D8H** [comment]
Tested on:
* an unrotated Sprite: only the position label and point is visible.
* a rotating Sprite: the origin point is shown and makes its loop.

**Comment by 4ian** [comment]
Thanks! Looks much better to always show the proper position :) And the origin/points for sprites (and we can extend to other objects in the future).

**Pull request merged**
