### PR TITLE
Copy/cut/paste Behavior (JS part)

### PR DESCRIPTION
**Pull request by Bouh**
Hello

Here are the Copy/cut/paste buttons for the behaviors. Paste is not functional there seems to be a need for some code in C++?

### CODE REVIEW

**Comment by 4ian** [comment]
Nice! Can you tell me what is the error message? I'll add the missing function.

**Comment by Bouh** [comment]
```
const newName = newNameGenerator(name, name =>
      eventsBasedBehaviorsContainer.hasEventsBasedBehaviorNamed(name)
    );
```
Error
`TypeError: Cannot read property 'hasEventsBasedBehaviorNamed' of undefined`

**Comment by 4ian** [comment]
Nothing was missing actually, but the class containing a list of events based behavior is done a bit differently internally (methods are just has, get, insertNew, instead of the old, more verbose hasXXX, getXXX, insertNewXXX). 
In case of doubt, you can always refer to this file: https://github.com/4ian/GDevelop/blob/master/GDevelop.js/Bindings/Bindings.idl which contains every single method exposed from C++ to JavaScript :) (you just have to type them with a lowercase as the first letter).

I've fixed the changes, seems to work well so merging this :)

Thanks for working on that!

**Comment by Bouh** [comment]
I always learn a little more, thanks :)

**Pull request merged**
