### PR TITLE
use newer electron builder

### PR DESCRIPTION
**Pull request by ClementPasteau**
see #6225

### CODE REVIEW

**Comment by ClementPasteau** [comment]
Let's wait for AppVeyor to build the .exe and test out the build installs properly

**Comment by romw314** [comment]
All checks passed.

**Comment by ClementPasteau** [comment]
Unfortunately the .exe was not generated as the certificate we used was temporarily expired. 
I'm relaunching the build.
fyi, the .exe can be found in the AppVeyor artifacts once it's finished. We need to test that it actually installs properly (the test being green is not enough)
I'll do a quick test

**Review by 4ian — APPROVED** [review]

**Comment by romw314** [comment]
Thanks.

**Pull request merged**
