### PR TITLE
Some little issues

### PR DESCRIPTION
**Pull request by victorlevasseur**
- Fix wrong platform in the Slot machine example
- Fix a PNG encoded in 8 bits preventing the Platformer with tilemap example to run correctly

### CODE REVIEW

**Comment by 4ian** [comment]
Thanks for the fixes :)
Is there anything not working when using Slot machine example with HTML5 platform?

**Comment by victorlevasseur** [comment]
The function event is not working (an empty ninth event is displayed in the
event editor).

2015-04-06 23:05 GMT+02:00 Florian Rival <notifications@github.com>:

> Thanks for the fixes :)
> Is there anything not working when using Slot machine example with HTML5
> platform?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/4ian/GD/pull/96#issuecomment-90243521>.
>



-- 
Victor LEVASSEUR
victorlevasseur52@gmail.com

**Comment by 4ian** [comment]
Ah ok indeed! I tested the example with the HTML5 platform and didn't see issues while previewing that's why I saved it with this platform.
Good catch :)

**Comment by BillyOutlast** [comment]
@dependabot rebase

**Pull request merged**
