### PR TITLE
Fix _PARAM0_ for FB instant game

### PR DESCRIPTION
**Pull request by Bouh**
This patch [fix this ](http://www.forum.compilgames.net/viewtopic.php?p=70022#p70022).
capture

### CODE REVIEW

**Comment by 4ian** [comment]
Good catch :) But seems that should `Save the content of _PARAM1_ in key _PARAM0_  [...]`

**Comment by Bouh** [comment]
omg again many files,i need a tuto about git, again.. sorry

**Comment by 4ian** [comment]
Could you revert the changes made to package-lock.json? Depends on your git client, you can uncheck this when creating your commit to not include changes made in this file. To revert it, you can take a look at https://www.shellhacks.com/git-revert-file-to-previous-commit/ 
something like : `git checkout 0b1213a8e428f943486ecb31a68d975415ae5476 -- package-lock.json`

**Comment by 4ian** [comment]
👍 Thanks for taking the time to submit the PR :)

**Pull request merged**
