### PR TITLE
Optimize z-order change

### PR DESCRIPTION
**Pull request by D8H**
Pixi allows to sort the object before the rendering which is probably O(n log(n)).

To keep the objects in order, we had to remove and insert an element in the array which takes O(n) for one z-order change and thus O(n²) when every object z-order changes.

When few objects are created or change of z-order in one frame, the engine will be less efficient than before, but it should not show much.
Whereas, when a lot of objects are created at the same frame (at the start of a scene for instance) or when a lot of y-ordered object are moving, the engine should be more efficient.

### CODE REVIEW

**Comment by Silver-Streak** [comment]
Just to check, is there a way to achieve both optimizations? e.g. some sort of check that sees if object order changes are < 50 use the old way, but if over 50 use the new one?

**Comment by arthuro555** [comment]
I was actually looking into optimizing this too, and overthinking this way too much 😅 
The problem with this is that this will do a lot of redundant sorts (every time the container is dirty, it will call `array.sort` on `container.children`). 
Note also that doing a `container.addChild` is bad for performance, as it invalidates caches on the object and the container, since, as far as pixi is concerned, this removes the object from its previous container and adds it to a new one. Instead, as we can see by how `PIXI.Container` internally reorders children when `sortableChildren` by simply calling `.sort` on the children array, we should be able to simply place the object at the correct place by ourselves.

My idea would be to do a binary search by ourselves on `container.children` to find the index the closest to the object's zOrder, and move the object there using `.splice` to both remove the object from its old index and add it to the newfound one. 
This should be much more efficient since:

- We tell PIXI that only the order changed and not anything else, which is our intention there, allowing it to not wrongfully invalidate caches
- We never conduct a sort redundantly
- A binary search is more efficient than a sort (`O(log n)` instead of `O(n log n)`), and we can safely go off the assumption that other objects will already be sorted (heck, that is what we were already doing)

The only potential issue is that this means we are shifting the array around twice per zOrder change (remove object from old position, insert it into new position), which is not necessarily the case with sort (a sort can simply swap objects one by one), and I am unsure whether or not that could cause a significant overhead, especially if V8 decides to resize the internal array because of this 🤔

**Comment by D8H** [comment]
> Just to check, is there a way to achieve both optimizations? e.g. some sort of check that sees if object order changes are < 50 use the old way, but if over 50 use the new one?

To make few objects creation efficient, we need to add objects on top of the layer to avoid any sort or search. Internally, objects are first added to the default layer then removed from it to be added to the actual layer set in the create action parameter.

It's a bigger change than this PR and maybe it optimizes something that doesn't make a difference. I doubt that games firing 1000 bullets per seconds will start to skip frames because of this.


> A binary search is more efficient than a sort (`O(log n)` instead of `O(n log n)`), and we can safely go off the assumption that other objects will already be sorted (heck, that is what we were already doing)
> 
> The only potential issue is that this means we are shifting the array around twice per zOrder change (remove object from old position, insert it into new position), which is not necessarily the case with sort (a sort can simply swap objects one by one), and I am unsure whether or not that could cause a significant overhead, especially if V8 decides to resize the internal array because of this

The issue with `splice` is that it needs to shift every element of the array on the right of the removed or inserted element which make it O(n) and make binary search almost irrelevant. Moving the element could solve the issue if we consider that z-order doesn't change by much, but again I'm not sure a few z-order that changes is a bottle neck.

**Comment by arthuro555** [comment]
Fair enough

**Review by 4ian — APPROVED** [review]
lgtm! Thanks for the discussion, I think this is a good improvement already and avoid us running into O(n^2) for something as simple as setting a z-order (and worse, even removing/adding back a children in pixi for just changing a z-order).

A few games should appreciate this :)

**Pull request merged**
