### PR TITLE
Refactor import-GDJS-Runtime script to use Node.js

### PR DESCRIPTION
**Pull request by 4ian**
Use a Node.js script to copy GDJS runtime and extension runtime files. The raw performance of using Node.js and recursive-copy module might or might not be better than using rsync (on macos/linux) and xcopy (on Windows) like the old script - but performance should be more than enough in any case.

### CODE REVIEW

**Comment by 4ian** [comment]
Tested on macOS and Windows, seems safe to go with this.
@grymmjack I updated the script that created issues for you on WSL. If you want to try again, should hopefully be better now (to be safe, delete node_modules in newIDE/app, then relaunch `npm install` and `npm start`)

**Comment by grymmjack** [comment]
Hey @4ian I tested this.

This is what I did:
removed the old repo, and refetched new (rm -rf). 

Then ran the 2 commands you suggested from within VS  Code WSL shell:
```
gj@DESKTOP-MH9OVO5:/i/git/gdevelop/GDevelop/newIDE/app$ npm install
npm WARN deprecated keen-tracking@1.1.3: deprecated
npm WARN deprecated url-search-params@1.1.0: now available as @ungap/url-search-params
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of 
core-js@3.
loadDep:webpack-hot-middl ▌ ╢███████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟ 
npm ERR! Linux 4.4.0-18362-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)      
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /i/git/gdevelop/GDevelop/newIDE/app/npm-debug.log      
gj@DESKTOP-MH9OVO5:/i/git/gdevelop/GDevelop/newIDE/app$ npm start

> gdevelop-ide@0.1.0 start /i/git/gdevelop/GDevelop/newIDE/app
> npm run import-resources && npm run make-version-metadata && react-scripts start


> gdevelop-ide@0.1.0 import-resources /i/git/gdevelop/GDevelop/newIDE/app
> npm run import-zipped-external-editors && cd scripts && node import-libGD.js && node import-GDJS-Runtime.js && node import-monaco-editor.js && node import-zipped-external-libs.js        


> gdevelop-ide@0.1.0 import-zipped-external-editors /i/git/gdevelop/GDevelop/newIDE/app
> cd scripts && node import-zipped-editor.js piskel 5.0.0-beta82 e02f67866b338b4cc577e1ffa48f55f52cd520ed751dccc6f0931e3c1b995de0 && node import-zipped-editor.js jfxr 5.0.0-beta55 8ac12b557c2ddba958c6f0d3e0c5df8cf3369a65262dcb90cf5c8a7a7d20bdf6 && node import-zipped-editor.js yarn 5.0.0-beta80 5930c686ccf2b6fd3433b1c9539483473a6aedb8b6a73dd13c07030c95efecb9

module.js:549
    throw err;
    ^

Error: Cannot find module 'shelljs'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/i/git/gdevelop/GDevelop/newIDE/app/scripts/import-zipped-editor.js:6:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

npm ERR! Linux 4.4.0-18362-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "import-zipped-external-editors"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! gdevelop-ide@0.1.0 import-zipped-external-editors: `cd scripts && node import-zipped-editor.js piskel 5.0.0-beta82 e02f67866b338b4cc577e1ffa48f55f52cd520ed751dccc6f0931e3c1b995de0 && node import-zipped-editor.js jfxr 5.0.0-beta55 8ac12b557c2ddba958c6f0d3e0c5df8cf3369a65262dcb90cf5c8a7a7d20bdf6 && node import-zipped-editor.js yarn 5.0.0-beta80 5930c686ccf2b6fd3433b1c9539483473a6aedb8b6a73dd13c07030c95efecb9`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gdevelop-ide@0.1.0 import-zipped-external-editors script 'cd scripts && node import-zipped-editor.js piskel 5.0.0-beta82 e02f67866b338b4cc577e1ffa48f55f52cd520ed751dccc6f0931e3c1b995de0 && node import-zipped-editor.js jfxr 5.0.0-beta55 8ac12b557c2ddba958c6f0d3e0c5df8cf3369a65262dcb90cf5c8a7a7d20bdf6 && node import-zipped-editor.js yarn 5.0.0-beta80 5930c686ccf2b6fd3433b1c9539483473a6aedb8b6a73dd13c07030c95efecb9'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gdevelop-ide package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd scripts && node import-zipped-editor.js piskel 5.0.0-beta82 e02f67866b338b4cc577e1ffa48f55f52cd520ed751dccc6f0931e3c1b995de0 && node import-zipped-editor.js jfxr 5.0.0-beta55 8ac12b557c2ddba958c6f0d3e0c5df8cf3369a65262dcb90cf5c8a7a7d20bdf6 && node import-zipped-editor.js yarn 5.0.0-beta80 5930c686ccf2b6fd3433b1c9539483473a6aedb8b6a73dd13c07030c95efecb9      
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gdevelop-ide
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gdevelop-ide
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /i/git/gdevelop/GDevelop/newIDE/app/npm-debug.log

npm ERR! Linux 4.4.0-18362-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "import-resources"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! gdevelop-ide@0.1.0 import-resources: `npm run import-zipped-external-editors && cd scripts && node import-libGD.js && node import-GDJS-Runtime.js && node import-monaco-editor.js && node import-zipped-external-libs.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gdevelop-ide@0.1.0 import-resources script 'npm run import-zipped-external-editors && cd scripts && node import-libGD.js && node import-GDJS-Runtime.js && node import-monaco-editor.js && node import-zipped-external-libs.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gdevelop-ide package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run import-zipped-external-editors && cd scripts && node import-libGD.js && node import-GDJS-Runtime.js && node import-monaco-editor.js && node import-zipped-external-libs.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gdevelop-ide
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gdevelop-ide
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /i/git/gdevelop/GDevelop/newIDE/app/npm-debug.log

npm ERR! Linux 4.4.0-18362-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! gdevelop-ide@0.1.0 start: `npm run import-resources && npm run make-version-metadata && react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gdevelop-ide@0.1.0 start script 'npm run import-resources && npm run make-version-metadata && react-scripts start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gdevelop-ide package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run import-resources && npm run make-version-metadata && react-scripts start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gdevelop-ide
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gdevelop-ide
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /i/git/gdevelop/GDevelop/newIDE/app/npm-debug.log
gj@DESKTOP-MH9OVO5:/i/git/gdevelop/GDevelop/newIDE/app$
```

If this is really silly I can just not use WSL and use Windows vanilla stuff or my Macbook. Don't waste time trying to solve for this if you think it's not important. I just like WSL because it lets me stay in the same context as when I'm working for my real job.

I've attached the npm-debug.log in case there are interesting things in it.

[npm-debug.log](https://github.com/4ian/GDevelop/files/4082878/npm-debug.log)

**Comment by 4ian** [comment]
Your version of npm is definitely too old: v3.5.2 
That's at least what I've seen here: https://npm.community/t/npm-install-error-missing-required-argument-1/8113

Upgrade to at least v6 of npm (npm install -g npm might work, otherwise might be worth re-installing Node.js as it comes with npm?).

Personally, I do work with a version of Node that is not that recent (v8.15.1) but still have a recent npm version :)
Then, removing node_modules and re-running npm install should work!

**Comment by grymmjack** [comment]
Hey @4ian thanks! I will do this. Before I forget though on my WSL this is how I updated my node and npm versions:
https://gist.github.com/noygal/6b7b1796a92d70e24e35f94b53722219

This made it super easy and now I am at 
`node v12.14.1`
`npm v6.13.4`

:)

I will clear the node_modules as you said and run npm install and npm start again, will report back sir!

```
gj@DESKTOP-MH9OVO5:/c/Users/grymm$ curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13527  100 13527    0     0  87270      0 --:--:-- --:--:-- --:--:-- 87270
=> Downloading nvm from git to '/home/gj/.nvm'
=> Cloning into '/home/gj/.nvm'...
remote: Enumerating objects: 286, done.
remote: Counting objects: 100% (286/286), done.
remote: Compressing objects: 100% (256/256), done.
remote: Total 286 (delta 34), reused 93 (delta 17), pack-reused 0
Receiving objects: 100% (286/286), 146.90 KiB | 7.34 MiB/s, done.
Resolving deltas: 100% (34/34), done.
=> Compressing and cleaning up git repository

=> Appending nvm source string to /home/gj/.bashrc
=> Appending bash_completion source string to /home/gj/.bashrc
=> You currently have modules installed globally with `npm`. These will no
=> longer be linked to the active version of Node when you install a new node
=> with `nvm`; and they may (depending on how you construct your `$PATH`)
=> override the binaries of modules installed with `nvm`:

/usr/local/lib
├── electron@7.1.9
└── picture-tube@1.0.0
=> If you wish to uninstall them at a later point (or re-install them under your
=> `nvm` Nodes), you can remove them from the system Node as follows:

     $ nvm use system
     $ npm uninstall -g a_module

=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
gj@DESKTOP-MH9OVO5:/c/Users/grymm$ export NVM_DIR="$HOME/.nvm"
gj@DESKTOP-MH9OVO5:/c/Users/grymm$ [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
 -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completiongj@DESKTOP-MH9OVO5:/c/Users/grymm$ [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
gj@DESKTOP-MH9OVO5:/c/Users/grymm$ nvm install --lts
Installing latest LTS version.
Downloading and installing node v12.14.1...
Downloading https://nodejs.org/dist/v12.14.1/node-v12.14.1-linux-x64.tar.xz...
######################################################################################################################################################################################################################################## 100.0%Computing checksum with sha256sum
Checksums matched!
Now using node v12.14.1 (npm v6.13.4)
Creating default alias: default -> lts/* (-> v12.14.1)
gj@DESKTOP-MH9OVO5:/c/Users/grymm$ node --version
v12.14.1
gj@DESKTOP-MH9OVO5:/c/Users/grymm$ npm --version
6.13.4
gj@DESKTOP-MH9OVO5:/c/Users/grymm$
```

**Comment by grymmjack** [comment]
It worked it seems but should I / we be concerned about "vulnerabilities" ? 
```

✅ src/Version/VersionMetadata.js properly generated.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/react-scripts/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 2455 packages from 1335 contributors and audited 75655 packages in 210.442s
found 934 vulnerabilities (352 low, 8 moderate, 574 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by grymmjack** [comment]
Also when i ran `npm start` it started a localhost:8000 development server that just sat there so I aborted `npm start` with `^C` - guessing you just wanted to me to test that kind of thing to see if that happened, and it did. OK I think I'm back on track with the WSL and whatever changes you made and updating to the LTS versions of node and npm works :)

Now since you've already put the Expressions reference into the wiki I guess what you originally asked of me is done, and now you are merely asking to make sure it's right and correct it if it's not?

If that's what you need, I got you. 

Thanks for working with me to get the tools figured out @4ian.

**Comment by 4ian** [comment]
> It worked it seems but should I / we be concerned about "vulnerabilities" ?

Not really, 99.9% are noise because they include dependencies of dependencies of dependencies and most of them are not used in the app itself (but just for the tooling, like webpack) and they are including code that turns out to be never executed.
Alas this kind of reports from npm are hard to action (you can't just upgrade the dependencies of your dependencies) and obnoxious as they are conveying more noise than signal. :/
I would be more concerned about vulnerabilities in packages actually used to render the editor (React, the react-markdown package) as a malicious user could try some injection (though most/all of what you're doing is in your own game, so the vector of attacks are limited). Another risk would be an attack targeting developers using npm itself, by having a rogue package that is doing nasty things on your computer when installed. This should be prevented by the use of yarn.lock/package.json lock that force to install specific version of packages (this is a more generic problem with package managers - how to detect malicious packages).

> Also when i ran npm start it started a localhost:8000

Was it more like localhost:3000? By default the port 3000 should be used. But yes that's expected :)

> Now since you've already put the Expressions reference into the wiki I guess what you originally asked of me is done, and now you are merely asking to make sure it's right and correct it if it's not?

Yep this is indeed done because I wanted to get this new page ready as soon as possible - I'm trying to put more focus on documentation recently :) 
Though, as we say, the devil is in the details, and they are still tons of these expression descriptions that could be improved or even fixed (typos or bad wording). If you want to start with simple stuff, please don't hesitate to submit fixes (searching in the whole codebase for a sentence should be enough to find the file containing it) (for extensions, it's either a `JsExtension.js` file or a `Extension.cpp` for older extensions or builtin extensions written in C++).

Though they are a lot of things to do in the roadmap, complexity can vary from simple to quite complex. I tried to add a few "Not too hard" tags, you can filter by this tag to find these cards: https://trello.com/b/qf0lM7k8/gdevelop-roadmap?menu=filter&filter=label:Not%20too%20hard%20%E2%9A%BD%EF%B8%8F

What is in the editor (IDE) column is more likely to be related to React, what is in the game engine column might be pure JS in the game engine but often involves also a bit of React or update the the extension (JS, sometimes a bit of C++ - though not too complicated).

Last solution, which actually might be the most interesting one: browse and use the app, find something that is not ideal, try to fix it :) After all, a good knowledge of GD will help you get better at finding stuff in the codebase :)

**Pull request merged**
