### PR TITLE
Update Howler to 2.11

### PR DESCRIPTION
**Pull request by zatsme**
Latest howler fixes android not playing html5 sounds/music

### CODE REVIEW

**Comment by 4ian** [comment]
Great! Unless there is other concerns, I'll merge this then :)

**Comment by zatsme** [comment]
So, this update fixes android sounds when using HTML5 option which is not currently user selectable.  If you preview the game in the IDE it will not play until an interation in chrome first.  A PC build from the IDE plays the music straight away also.

So it seems that we need the HTML5 option to be user selectable in the IDE?!

**Comment by 4ian** [comment]
The issue is always the same, Chrome is blocking audio until the user do a first interaction: https://developers.google.com/web/updates/2018/11/web-audio-autoplay

**Comment by zatsme** [comment]
Well it plays on android now without interaction, so that's better than before.

Do you think we need an option to choose HTML5 or Web audio playback?

**Comment by 4ian** [comment]
I'm not sure about this, I think it's a technical issue that should not be surfaced to the user. Otherwise, we make the user responsible for knowing that one for them has issue, while it should be GDevelop/the game engine job to choose the best according to the media file.

**Comment by zatsme** [comment]
Well, this doesn't appear to break anything  so might as well merge for now and maybe rethink/research how to make this work better for everybody without any user interaction.

Maybe we need to detect target O/S and use the appropriate method, or just provide docs on how to enable HTML5 audio if required, or ensure a click is done before using sound.

Right now, if we merge then we can test what happens on all platforms and then decide what needs to be done from here on....

Once merged I'll create a sound tester demo so we can all test using the same code and log the results and compare.

**Comment by 4ian** [comment]
> Right now, if we merge then we can test what happens on all platforms and then decide what needs to be done from here on....

Yes my view too, the latest version will bring improvements/fixes in any cases. Merged! Thanks for taking the time to do the PR :)

> Once merged I'll create a sound tester demo so we can all test using the same code and log the results and compare.

Nice, let us know when you have it, will be useful!

**Pull request merged**
