### PR TITLE
New variables list improvements

### PR DESCRIPTION
**Pull request by AlexandreSi**
To fix:
- [x] https://github.com/4ian/GDevelop/issues/3927

@Silver-Streak ideas:
- [x] I would recommend docking the copy/paste/delete/undo/search bar at the top, so users don't have to scroll back up if they have a large list of variables.
- [ ] There probably needs to be a copy/paste variable option on the right-click menu. If there is one, I can't seem to activate it (only copy/paste text in a variable name/value seems to work)
- [x] When searching, if the top level of a structure/array is found, the children aren't shown. Not sure if that is intentional or not (or if it should be). Likewise, results that are structures or array cannot be expanded, which feels like it reduces the effectiveness/usefulness of searching somewhat, since I'd have to unsearch and then manually find the structure/array again.
- [ ] Probably needs a right-click "Collapse/Expand this level" option for child variables to collapse/expand all children of the current variable at the level selected.
- [x] When adding a new variable via the "Add variable" button, the window doesn't jump/scroll to it. So the user may not know a variable was created at the bottom of the list and may hit the button a few times. I'd probably recommend jumping to any new variable as the focus, since it was created via a conscious action by the dev clicking the button. 
- [ ] CTRL+A, select all rows.

### CODE REVIEW

**Comment by AlexandreSi** [comment]
I won't add the right click behavior as it would require to have a 3-dots additional button on each line, that would make the lines heavier.
With the fixed position toolbar, it may prove itself less necessary. We'll see if we have more requests on this in the future

**Comment by AlexandreSi** [comment]
@Bouh I pushed a new version.
Storybook should be at this url http://gdevelop-storybook.s3-website-us-east-1.amazonaws.com/fine-tune-new-variables-list/latest/index.html

Can you try the select?

**Comment by Bouh** [comment]
To be sure, I started the application locally, it works fine now!

image

**Comment by Bouh** [comment]
If possible to add:
- [ ] CTRL+A, select all rows.
I add this to your first post.

**Comment by AlexandreSi** [comment]
I was having trouble adding shortcuts to the component, and I just realized that the tree view has implemented accessibility guidelines, so it captures key events. So much that I cannot detect the A key type at my level. And Material UI does not allow to remove the accessibility shortcuts.

So Ctrl+A will be for another time (maybe TreeView is not that useful at the end of the day)

**Pull request merged**
