### PR TITLE
Enable more warnings from Clang when compiling C++ sources

### PR DESCRIPTION
**Pull request by 4ian**
Only show in developer changelog

### CODE REVIEW

**Comment by ClementPasteau** [comment]
nice!

Where/when do the warnings appear? in the terminal when running a `npm run build` in `GDevelop.js`?

**Comment by 4ian** [comment]
Yes! All warnings should be shown btw in Travis once the compilation is done. 
I think I've avoided with the few warnings there were deactivated to have too much of them (that would make it hard to see new ones when working on a file).
If this goes well we can even enable `-Werror` in the future to fail the build for warnings (warnings in C++ are almost always important to fix).

**Comment by ClementPasteau** [comment]
Shouldn't we fix the warnings and make it error right away to be on a clean base right away?

**Comment by 4ian** [comment]
> Shouldn't we fix the warnings and make it error right away to be on a clean base right away?

In theory yes, in practice my battery is running away and I preferred to push something useful rather than postpone it for later ;)

**Comment by 4ian** [comment]
> Shouldn't we fix the warnings and make it error right away to be on a clean base right away?

In theory yes, in practice my battery is running away and I preferred to push something useful rather than postpone it for later ;)

**Pull request merged**
