### PR TITLE
Add script to extract all the expressions available in GDevelop

### PR DESCRIPTION
**Pull request by 4ian**
@Bouh @grymmjack You might be interested by this new script :) 

To run it: `cd newIDE/app/scripts` and then `node extract-reference-document.js`.

This creates a reference.md file in the same folder with all expression of all extension/object/behaviors :) 
There will be adaptations to do I think in:

- [ ] extension/object/behaviors themselves, to improve descriptions
- [ ] On the formatting, I've just put a few headers and stuff, but I think we could try to make a table like http://wiki.compilgames.net/doku.php/gdevelop5/all-features/functions 
- [ ] Add parameters, right now I'm just showing the name of the expressions
- [ ] We could even add links to help page! Search in [Bindings.idl](https://github.com/4ian/GDevelop/blob/master/GDevelop.js/Bindings/Bindings.idl) for all the methods of libGD.js objects that you can use (search for ExpressionMetadata object in this file. You can also look at the [C++ documentation like this page about ExpressionMetadata](https://docs.gdevelop-app.com/GDCore%20Documentation/classgd_1_1_expression_metadata.html))

I'll merge this now (so you can try in master branch) but discussion can continue here :)

When it's done I'll make the functions page more visible in the wiki :)

### CODE REVIEW

**Comment by grymmjack** [comment]
Awesome! Let me get my toolchain and workspace setup and I'll dig in. <3

**Comment by 4ian** [comment]
Sure, let us know if you have an issue when setting that up :)

**Comment by grymmjack** [comment]
I am having an issue.

```
gj@DESKTOP-MH9OVO5:/i/git/gdevelop/GDevelop/newIDE/app/scripts$ node extract-reference-document.js 
Exception while requiring module (from optionalRequire): { Error: Cannot find module 'electron'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at optionalRequire (/i/git/gdevelop/GDevelop/newIDE/app/src/Utils/OptionalRequire.js:26:14)
    at Object.<anonymous> (/i/git/gdevelop/GDevelop/newIDE/app/src/GameEngineFinder/LocalGDJSFinder.js:5:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12) code: 'MODULE_NOT_FOUND' }
./CopyRuntimeToGD.sh: line 19: syntax error: unexpected end of file
./CopyRuntimeToGD.sh: line 19: syntax error: unexpected end of file
libGD.js based on GDevelop 4.0.98-0-release
Initializing GDJS platform...
* Loading builtin extensions... Loading BuiltinObject...
Loading Sprite...
Loading BuiltinCommonInstructions...
Loading BuiltinCommonConversions...
Loading BuiltinVariables...
Loading BuiltinMouse...
Loading BuiltinKeyboard...
Loading BuiltinJoystick...
Loading BuiltinScene...
Loading BuiltinTime...
Loading BuiltinMathematicalTools...
Loading BuiltinCamera...
Loading BuiltinAudio...
Loading BuiltinFile...
Loading BuiltinNetwork...
Loading BuiltinWindow...
Loading BuiltinStringInstructions...
Loading BuiltinAdvanced...
Loading BuiltinExternalLayouts...
done.
* Loading other extensions... Loading PlatformBehavior...
Loading DestroyOutsideBehavior...
Loading TiledSpriteObject...
Loading DraggableBehavior...
Loading TopDownMovementBehavior...
Loading TextObject...
Loading ParticleSystem...
Loading PanelSpriteObject...
Loading AnchorBehavior...
Loading PrimitiveDrawing...
Loading TextEntryObject...
Loading Inventory...
Loading LinkedObjects...
Loading SystemInfo...
Loading Shopify...
Loading PathfindingBehavior...
Loading PhysicsBehavior...
done.
Platform initialization ended.
Unable to find JS extensions modules
Error while writing output Error: Could not find GDJS
    at onNotFound (/i/git/gdevelop/GDevelop/newIDE/app/src/GameEngineFinder/LocalGDJSFinder.js:34:37)
    at fs.access.err (/i/git/gdevelop/GDevelop/newIDE/app/src/GameEngineFinder/LocalGDJSFinder.js:19:10)
    at FSReqWrap.oncomplete (fs.js:135:15)
```

I'm using WSL so maybe that's an issue, but.

I had `npm` already installed as well as `node`. Are there specific versions of npm or node required? I have these:

`npm 3.5.2`
`node v8.10.0`

It threw a bunch of errors when I ran `sudo npm install`, so i did some research and discovered it could also use `yarn` so I installed that and ran yarn and it simply fixed a lot of things I think.

But I've gotten that last bit of problem just a few moments ago.

Any help is greatly appreciated @4ian !

**Comment by grymmjack** [comment]
I've seen errors like this:
`./CopyRuntimeToGD.sh: line 19: syntax error: unexpected end of file`

Based on linefeed mismatches between platforms. I'll check into that next and run `dos2unix` on it if you think that will help?

Also question: with npm installation or yarn, do I need to traverse the entire directory structure wherever I find .package.json files? I did that too just in case it was needed. I'm sort of a newb with npm and node and only have limited experience.

Thanks

**Comment by 4ian** [comment]
Mmm I never used WSL. It might be confused because you're running in a Linux environment but on Windows. 

> I've seen errors like this:
> ./CopyRuntimeToGD.sh: line 19: syntax error: unexpected end of file

The last error `Could not find GDJS` is caused by this. Things won't work until you fix the run of this script. You might want to try to convert linefeeds, not sure if this will work as this was only tested in Linux and macOS though! You might have fixes to do inside this file (GDJS/scripts/CopyRuntimeToGD.sh)

(also disregard `Cannot find module 'electron'`, it's actually expected. I should hide this, it's because we're requiring electron to see if we're running inside electron or not)

> It threw a bunch of errors when I ran sudo npm install

Not sure about WSL, but in macOS/Linux it's highly highly recommended to *not* use sudo. Instead, always install with just npm install - otherwise you're getting files owned by root and more problems down the line.
yarn is fine, I'm using it on macOS, and npm on Windows (but without WSL).

> Are there specific versions of npm or node required?

Your version must be enough, any Node 8+ should work.

Let me know how it goes.

**Comment by 4ian** [comment]
If you figure out how to run CopyRuntimeToGD.sh properly, you should then remove `node_modules` folder in `newIDE/app` to be extra sure and relaunch `npm install` (or `yarn`) to be sure that all the additional scripts are launched :)

"Thankfully" most scripts now are actually in JS and ran by Node.js (so should be cross platform). If we verify that fixing CopyRuntimeToGD.sh works, we could actually rewrite it (and its sibling CopyRuntimeToGD.bat) in JavaScript. Would be more maintainable. They were created at a time where GDevelop editor was not even running in JavaScript :) 

If you're totally stuck, we'll do that to see if it's better.

**Comment by grymmjack** [comment]
It works no prob on my macbook. :) Now researching.

**Comment by grymmjack** [comment]
Actually it looked like it worked but I'm missing some things:

```
~/git/GDevelop/GDevelop/newIDE/app/scripts (master ✘)✹ ᐅ node extract-reference-document.js 
Exception while requiring module (from optionalRequire): Error: Cannot find module 'electron'
Require stack:
- /Users/gj/git/GDevelop/GDevelop/newIDE/app/node_modules/node-require-function/index.js
- /Users/gj/git/GDevelop/GDevelop/newIDE/app/src/Utils/OptionalRequire.js
- /Users/gj/git/GDevelop/GDevelop/newIDE/app/src/JsExtensionsLoader/LocalJsExtensionsLoader.js
- /Users/gj/git/GDevelop/GDevelop/newIDE/app/scripts/lib/LocalJsExtensionsLoader.js
- /Users/gj/git/GDevelop/GDevelop/newIDE/app/scripts/extract-reference-document.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at optionalRequire (/Users/gj/git/GDevelop/GDevelop/newIDE/app/src/Utils/OptionalRequire.js:26:14)
    at Object.<anonymous> (/Users/gj/git/GDevelop/GDevelop/newIDE/app/src/GameEngineFinder/LocalGDJSFinder.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/gj/git/GDevelop/GDevelop/newIDE/app/node_modules/node-require-function/index.js',
    '/Users/gj/git/GDevelop/GDevelop/newIDE/app/src/Utils/OptionalRequire.js',
    '/Users/gj/git/GDevelop/GDevelop/newIDE/app/src/JsExtensionsLoader/LocalJsExtensionsLoader.js',
    '/Users/gj/git/GDevelop/GDevelop/newIDE/app/scripts/lib/LocalJsExtensionsLoader.js',
    '/Users/gj/git/GDevelop/GDevelop/newIDE/app/scripts/extract-reference-document.js'
  ]
}
ℹ️ Copying GDJS and extensions runtime files (*.js) to '/Users/gj/git/GDevelop/GDevelop/newIDE/app/resources/GDJS/Runtime'...
✅ Copied GDJS and extensions runtime files (*.js) to '/Users/gj/git/GDevelop/GDevelop/newIDE/app/resources/GDJS/Runtime'.
ℹ️ Copying GDJS and extensions runtime files (*.js) to '/Users/gj/git/GDevelop/GDevelop/newIDE/app/node_modules/GDJS-for-web-app-only/Runtime'...
✅ Copied GDJS and extensions runtime files (*.js) to '/Users/gj/git/GDevelop/GDevelop/newIDE/app/node_modules/GDJS-for-web-app-only/Runtime'.
libGD.js based on GDevelop 4.0.98-0-release
Initializing GDJS platform...
* Loading builtin extensions... Loading BuiltinObject...
Loading Sprite...
Loading BuiltinCommonInstructions...
Loading BuiltinCommonConversions...
Loading BuiltinVariables...
Loading BuiltinMouse...
Loading BuiltinKeyboard...
Loading BuiltinJoystick...
Loading BuiltinScene...
Loading BuiltinTime...
Loading BuiltinMathematicalTools...
Loading BuiltinCamera...
Loading BuiltinAudio...
Loading BuiltinFile...
Loading BuiltinNetwork...
Loading BuiltinWindow...
Loading BuiltinStringInstructions...
Loading BuiltinAdvanced...
Loading BuiltinExternalLayouts...
done.
* Loading other extensions... Loading PlatformBehavior...
Loading DestroyOutsideBehavior...
Loading TiledSpriteObject...
Loading DraggableBehavior...
Loading TopDownMovementBehavior...
Loading TextObject...
Loading ParticleSystem...
Loading PanelSpriteObject...
Loading AnchorBehavior...
Loading PrimitiveDrawing...
Loading TextEntryObject...
Loading Inventory...
Loading LinkedObjects...
Loading SystemInfo...
Loading Shopify...
Loading PathfindingBehavior...
Loading PhysicsBehavior...
done.
Platform initialization ended.
Searching for JS extensions (file called JsExtension.js) in /Users/gj/git/GDevelop/GDevelop/newIDE/app/resources/GDJS/Runtime/Extensions...
Loading AdMob...
Loading BBText...
Loading DeviceSensors...
Loading DeviceVibration...
Loading DialogueTree...
Loading Effects...
Loading MyDummyExtension...
Loading FacebookInstantGames...
Loading FileSystem...
Loading Physics2...
Loading Screenshot...
Loading Tween...
Loading Video...
Loaded extensions [
  {
    extensionModulePath: '/Users/gj/git/GDevelop/GDevelop/newIDE/app/resources/GDJS/Runtime/Extensions/AdMob/JsExtension.js',
    result: { message: '✅ Successfully loaded the extension.', error: false }
  },
  {
    extensionModulePath: '/Users/gj/git/GDevelop/GDevelop/newIDE/app/resources/GDJS/Runtime/Extensions/BBText/JsExtension.js',
    result: { message: '✅ Successfully loaded the extension.', error: false }
  },
  {
    extensionModulePath: '/Users/gj/git/GDevelop/GDevelop/newIDE/app/resources/GDJS/Runtime/Extensions/DeviceSensors/JsExtension.js',
    result: { message: '✅ Successfully loaded the extension.', error: false }
  },
  {
    extensionModulePath: '/Users/gj/git/GDevelop/GDevelop/newIDE/app/resources/GDJS/Runtime/Extensions/DeviceVibration/JsExtension.js',
    result: { message: '✅ Successfully loaded the extension.', error: false }
  },
  {
    extensionModulePath: '/Users/gj/git/GDevelop/GDevelop/newIDE/app/resources/GDJS/Runtime/Extensions/DialogueTree/JsExtension.js',
    result: { message: '✅ Successfully loaded the extension.', error: false }
  },
  {
    extensionModulePath: '/Users/gj/git/GDevelop/GDevelop/newIDE/app/resources/GDJS/Runtime/Extensions/Effects/JsExtension.js',
    result: { message: '✅ Successfully loaded the extension.', error: false }
  },
  {
    extensionModulePath: '/Users/gj/git/GDevelop/GDevelop/newIDE/app/resources/GDJS/Runtime/Extensions/ExampleJsExtension/JsExtension.js',
    result: { message: '✅ Successfully loaded the extension.', error: false }
  },
  {
    extensionModulePath: '/Users/gj/git/GDevelop/GDevelop/newIDE/app/resources/GDJS/Runtime/Extensions/FacebookInstantGames/JsExtension.js',
    result: { message: '✅ Successfully loaded the extension.', error: false }
  },
  {
    extensionModulePath: '/Users/gj/git/GDevelop/GDevelop/newIDE/app/resources/GDJS/Runtime/Extensions/FileSystem/JsExtension.js',
    result: { message: '✅ Successfully loaded the extension.', error: false }
  },
  {
    extensionModulePath: '/Users/gj/git/GDevelop/GDevelop/newIDE/app/resources/GDJS/Runtime/Extensions/Physics2Behavior/JsExtension.js',
    result: { message: '✅ Successfully loaded the extension.', error: false }
  },
  {
    extensionModulePath: '/Users/gj/git/GDevelop/GDevelop/newIDE/app/resources/GDJS/Runtime/Extensions/Screenshot/JsExtension.js',
    result: { message: '✅ Successfully loaded the extension.', error: false }
  },
  {
    extensionModulePath: '/Users/gj/git/GDevelop/GDevelop/newIDE/app/resources/GDJS/Runtime/Extensions/TweenBehavior/JsExtension.js',
    result: { message: '✅ Successfully loaded the extension.', error: false }
  },
  {
    extensionModulePath: '/Users/gj/git/GDevelop/GDevelop/newIDE/app/resources/GDJS/Runtime/Extensions/Video/JsExtension.js',
    result: { message: '✅ Successfully loaded the extension.', error: false }
  }
]
Done.
```

Any ideas?

**Comment by 4ian** [comment]
It works :) See reference.md that was generated in the same folder.

You can disregard the first error, it's actually expected. I should hide this, it's because we're requiring electron to see if we're running inside electron or not.

**Comment by 4ian** [comment]
Also, I'll update the script that was not working in WSL to use node.js. Should work better on any environment, WSL or not :)

**Pull request merged**
