### PR TITLE
Upgrade Pixi.js to 6.1.2

### PR DESCRIPTION
**Pull request by ClementPasteau**
The first purpose was to fix the issue #2644.
I tested the issue example and it is indeed fixed!

A lot of other fixes (and features) have been bundled in this release too: https://github.com/pixijs/pixijs/releases/tag/v6.1.0

What do you reckon is the best way to test such an upgrade @4ian ? Manual tests on multiple games ?

### CODE REVIEW

**Comment by Bouh** [comment]
I would say
- [ ] Add all objects one by one by adding them to the scene.
- [ ] Start a preview with the different objects.
- [ ] Check all effects. [See here](https://github.com/4ian/GDevelop/pull/2447#issuecomment-808395980)

**Comment by Bouh** [comment]
Visual unit test are also a good thing for the future :)
https://github.com/zaqqaz/visual-unit-tests

**Comment by 4ian** [comment]
> I would say
> 
> * [ ]  Read the previous PixiJS patch notes for checking any deprecated methods or updated.
> * [ ]  Add all objects one by one by adding them to the scene or check examples with these objects.
> * [ ]  Start a preview with the different objects.
> * [ ]  Check all effects. [See here](https://github.com/4ian/GDevelop/pull/2447#issuecomment-808395980)
>   Checking the effects is important PIXI.Filter is based on PixiJS core.

Seems like a good list. The idea is to check manually all objects and then a bunch of more or less random example to hope to catch any regression according to the changelog. Seems like this upgrade is fairly low risk overall!

**Comment by ClementPasteau** [comment]
Nice! I'll try to do that at the end of the day

**Comment by ClementPasteau** [comment]
did it a bit earlier :)

- Tested all objects and their render in the preview, everything looks fine.
- Tested multiple project examples
- Tested all particle effects with the project (https://github.com/GDevelopApp/GDevelop-examples/tree/main/examples/particle-effects-demo)
- Tested multiple layer effects with the effects demo in `GDJS/tests/games/effects/all effects demo.json`

The only thing that's different is the `Blur` Layer effect.
Previously, it seemed to crop the image, based on the number of render passes being done. (1 was cutting the image in half, 2 was hiding the image completely ??)
I assume this is a bug fixed rather than a bug introduced, am I wrong? @Bouh 

ezgif com-gif-maker

**Comment by Bouh** [comment]
> I assume this is a bug fixed rather than a bug introduced, am I wrong? @Bouh

Correct it's like an unexpected fix ^^

Let me compile GDevelop with these changes and check. We are never too much to check this big API change.

**Comment by 4ian** [comment]
Looks solid, and maybe we got a bugfix for free! @Bouh let us know if you find anything else, otherwise I think we can go ahead!

**Review by 4ian — APPROVED** [review]

**Comment by Bouh** [comment]
Sounds good to me for the runtime and IDE!

- One thing on the developer side, the .map file shouldn't be updated too? 
https://github.com/4ian/GDevelop/blob/9aa6ce0485615ef12bbc14098baedbbc5dd38339/GDJS/Runtime/pixi-renderers/pixi.js#L10

- As the effects are also on objects I've tested some effects on objects and they work fine too.

**Comment by 4ian** [comment]
> One thing on the developer side, the .map file shouldn't be updated too?

Good catch, should be otherwise we'll have surprises when trying to debug :) (i.e: wrong lines everywhere I guess)

**Comment by ClementPasteau** [comment]
interestingly the .map was never included 🤔 

I'll add it so we're in a better position if a problem occurs in the future

**Comment by ClementPasteau** [comment]
I believe this will need more work than expected to add the .map for this file.
I couldn't get it to work and I can't find a similar example where a map is added directly from the code when it is not part of an extension.

As this is not causing any error in the console (it's always been like that) I'm suggesting to merge like this and we can see later if we really need the map.

**Comment by 4ian** [comment]
Yep let's go ahead as things are not worse (they are even strictly better if there are no regressions :)) than before!

**Pull request merged**
