### PR TITLE
Add new collision mask vertices on the middle of edges

### PR DESCRIPTION
**Pull request by D8H**
http://gdevelop-storybook.s3-website-us-east-1.amazonaws.com/new-vertex/latest/index.html?path=/story/objecteditor-spriteeditor--collision-masks

### CODE REVIEW

**Comment by tristanbob** [comment]
I didn't know what this was at first, but now that I do, people are going to love this! (the old way was very frustrating when adding new vertices)

Does it select the longest line to determine where to add the vertice?

https://user-images.githubusercontent.com/8879811/210273415-56bb8be3-0a44-40be-b3ac-177fd7894808.mp4

**Comment by tristanbob** [comment]
I just noticed it thought the polygon was not convex. Is that a bug or simply a limitation of storybooks?

**Comment by D8H** [comment]
> Does it select the longest line to determine where to add the vertice?

Exactly.

> I just noticed it thought the polygon was not convex. Is that a bug or simply a limitation of storybooks?

It's a strict convexity check. I don't know if it's important, but it's probably better to warn about it as the point is useless in this configuration.

**Review by ClementPasteau — APPROVED** [review]
lgtm!

**Pull request merged**
