### PR TITLE
Search events translations

### LINKED ISSUE #1215: Search function in Events tab does not search event names.
## Describe the bug
When searching (Magnifying Glass) in the Events editor, if you search for the text of an event, no results are found. 

e.g. If I want to search for all "Stop Object" events, searching for "Stop" returns 0 results.

## To Reproduce

1. Add a "Stop Object" event to your event list.
2. Click the Search/Magnifying Glass icon.
3. Search for **Stop**. 
4. Click **Search**. Case insensitive and filters do not matter. No results will be found.

## Other details
OS: Windows 10 Pro 64 bit.
GDevelop Version: 5.0.0-beta79
Screenshots attached
No results

### PR DESCRIPTION
**Pull request by AlexandreSi**
Resolves #1215 and should satisfy [highlighting search results forum topic](https://forum.gdevelop-app.com/t/highlighting-search-results/35432)

Add possibility to search Events by the events' sentences

### CODE REVIEW

**Comment by AlexandreSi** [comment]
Maybe I should add a little transformation to the `completeSentence` variable in which we search for the string:
- to replace any amount of adjacent spaces with one space (to prevent no results search with bad formatting)
- to be less sensitive to special characters such as `:` `,`

**Comment by AlexandreSi** [comment]
- Former search and replace kept as is
  
  image

- New search in event sentences tab
  image

- Colored handle
  image

**Comment by UlisesFreitas** [comment]
Hi mates could something like this be added to the search results.
Showing 1 of 1
add-showing-of
2

**Comment by AlexandreSi** [comment]
Got you: #3172

**Pull request merged**
