### PR TITLE
Instance Variables - commitVariableValueOnBlur

### PR DESCRIPTION
**Pull request by Bouh**
Based on #1818
Ready to review.

### CODE REVIEW

**Comment by 4ian** [comment]
Looks good! I added a comment to explain why we use this prop in the dialog (we use it to avoid useless re-renders, which we can afford in this case because we know the component will get blurred before the dialog is closed).

Removing the commitOnBlur in the case of the usage of VariablesList in `InstancePropertiesEditor` has a downside. Any time I press a key to change a character, the variable is saved, which trigger a re-render of all variables (not ideal, but that's ok, can be an optimization done later) and, worse, a re-render of the whole editor. See how the components are highlighted after I pressed a key:
image

This is quite costly and we should avoid this. The reason is because we have this:
https://github.com/4ian/GDevelop/blob/c2fedf23b98d59d805522cec74504a16ce6d0891/newIDE/app/src/InstancesEditor/InstancePropertiesEditor/index.js#L178-L181

Which I think is useless. The idea of this piece of code was to force a refresh so that the dialog position on screen is updated by material-ui. But:
- `InstancePropertiesEditor` is never shown in a dialog... so I think this was added by error!
- Since the upgrade to the latest material-ui version a few months ago, maybe this hack (search for `onSizeUpdated`) is now useless :) 

For now, would be great if you can:
1) remove the onSizeUpdated in InstancePropertiesEditor. So that changing a variable just re-render all variables (again, sub optimal, maybe there is something better to do).
2) triple check that it works well.

We can look at removing the `onSizeUpdated` in another PR (the issue that without them, when you added a bunch of new variables, the dialog was not getting re-positioned on screen... not super nice when you add tons of variables and that the dialog is expanding outside of the window borders ^^).

**Comment by Bouh** [comment]
Something with memo() ?

**Comment by Bouh** [comment]
It's good 
image

**Comment by 4ian** [comment]
> Something with memo() on VariableRow ?

That could maybe help a bit indeed, though not for structures (you need to iterate on it in all cases) (memo/PureComponent would maybe help to avoid re-rendering a row if the variable name and value did not change). 

> It's good

Looks good yep 👍

**Pull request merged**
