### PR TITLE
Fix issues noted in #895 - locate resource command breaking after a resource has been renamed

### PR DESCRIPTION
**Pull request by blurymind**
Much thanks to @zatsme for discovering this bug. I just noticed a silly mistake in my code that breaks the locate resource commands in the resource manager after a resource has been renamed. This should fix it

### CODE REVIEW

**Comment by 4ian** [comment]
Oh right, I also got confused while reviewing this code originally. Thanks for the fix! :)

**Comment by blurymind** [comment]
@4ian sorry for overlooking this in the first place :)

btw I am trying to add a warning before renaming resource by using confirm like this:
https://github.com/4ian/GDevelop/search?l=JavaScript&q=confirm%28

but ithe mothod is not imported in resourceslist. Now I am wondering - how do you import it?

**Comment by blurymind** [comment]
adding window to it seems to make it work.. window.confirm("blah blah")

**Comment by blurymind** [comment]
Haha tricky. Thank you for sharing this. I amended it now :)

**Pull request closed without merging**
