### PR TITLE
Improve Mouse extension to autocomplete possible values for expression

### PR DESCRIPTION
**Pull request by ClementPasteau**
Adresses #3359 

image

### CODE REVIEW

**Comment by AlexandreSi** [comment]
Looks great! I'm just wondering if these are the only possibilities. I found this:
https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons

But I'm not sure we support those. At least, I'm not sure if the list you added is a suggestion, or if it behaves like an enum and you can't choose another value than these 3

**Comment by 4ian** [comment]
We don't support those (we have a "enum like" content) *but* this could be cool to add the auxiliary ("wheel") button and the "browser back/forward" buttons.

[image](https://github.com/4ian/GDevelop/blob/ad3c7e4fad611e17fd827ebd349bd881fa4bca17/GDJS/Runtime/pixi-renderers/runtimegame-pixi-renderer.ts#L453-L475)

Approving this because this is still an improvement :)

**Comment by Bouh** [comment]
Is these values are case sensitive? Please no 👀

**Comment by ClementPasteau** [comment]
Yes they are. Not ideal, but the autocomplete should help avoid mistakes

**Comment by 4ian** [comment]
They are/always have been... but I must admit we could reduce the requirements here. There won't ever be a "Left" button and a "left" button being two different things.

**Pull request merged**
