### PR TITLE
Shortcut for duplicate instance(s)

### PR DESCRIPTION
**Pull request by danired**
I added a shortcut for Duplicating instance(s) `Ctrl + D`.
This shortcut is used in many programs, and I think some times is more intuitive.

image

### CODE REVIEW

**Comment by tristanbob** [comment]
Thanks, this is useful!  Could we also add an offset for newly created instances?
I have accidentally made duplicated instances (on top of each other) in my scene in nearly every game I have made.

**Comment by 4ian** [comment]
Looks like a good idea! Give a try at Tristan suggestion, and we'll merge this otherwise even if you don't manage to do it :)

**Comment by danired** [comment]
Hi @tristanbob ,

But I think that offset is currently in `master`.

I  tried in my branch with the shortcut and the contextual menu and is always creating an offset

And just for testing I tried now in `master` and is doing the offset too.

I attach a video

https://user-images.githubusercontent.com/21989259/221132030-d62ec0b3-ebab-4d58-b19c-9be5ea98795e.mp4

**Comment by tristanbob** [comment]
This is perfect! 

The only thing left to do (it can be done outside this PR) is to change the control + drag method of duplicating so that the copy is not made until the drag is pulled a minimum distance.  Currently you can get a ton of hidden copies within control click on an instance.

**Comment by danired** [comment]
> The only thing left to do (it can be done outside this PR) is to change the control + drag method of duplicating so that the copy is not made until the drag is pulled a minimum distance. Currently you can get a ton of hidden copies with control click on an instance.

Yes, I think we can do it in a different PR. And I could try it if you don't mind.

**Comment by 4ian** [comment]
> I tried in my branch with the shortcut and the contextual menu and is always creating an offset

Perfect then! I forgot we had this already.

Please make sure to run `npm run format` in newIDE/app, commit the results and it's good to go. Thank you!

**Comment by danired** [comment]
Done

**Comment by 4ian** [comment]
Thanks again, great work!

**Comment by danired** [comment]
Thanks to you! 🤗

**Comment by tristanbob** [comment]
I tested this on the nightly build and it works great.  Thanks for your excellent contribution, @danired!

**Pull request merged**
