### PR TITLE
Fix help paths of objects

### PR DESCRIPTION
**Pull request by Bouh**
Fix path for Tile map and Bitmap Text.
Video help path lead to an empty page but I notified the content creator team to fill the wiki page.

### CODE REVIEW

**Comment by 4ian** [comment]
Somehow I missed this! Thanks :)

**Comment by jack-ii** [comment]
The help path for the **Light** object is still wrong.

**Comment by Bouh** [comment]
The Update will be push in the next release. And page for light object is currently empty. URL will be on the objects page of our wiki.

**Comment by jack-ii** [comment]
I thought of linking or copying to this, better than on a non-existent page. But doesn't matter.
https://wiki.gdevelop.io/gdevelop5/all-features/lighting/reference#lights

**Comment by Bouh** [comment]
Someone at GDevelop will be in charge of these changes, it's on the rails 😉

**Pull request merged**
