### PR TITLE
Updated pixi-particles

### PR DESCRIPTION
**Pull request by arthuro555**
Mainly for pixi v5 support. Tested on "Various Particles Effects" Example.

### CODE REVIEW

**Comment by 4ian** [comment]
Could you add details explaining which version is used, and what are the changes and breaking changes if any, since the previous one?

**Comment by arthuro555** [comment]
I updated to the last version, 4.2.0. There are not really any new features for the particles themselves. There are multiple bug fixes, Pixi v5 support, and internal changes. The main reason for this update is the pixi v5 support.

**Comment by Quarkstar** [comment]
Thank you!  :joy: But I've upgraded it to v4.2.0 in #1628.

**Comment by arthuro555** [comment]
Oh, I didn't see. Your PR isn't merged yet tho. In the meantime this one can already be merged, can't it ¯\_(ツ)_/¯? 
No but more seriously, it's better your PR staysand I close this one as it would add merge conflicts and yours is bigger. ~~I'm sad I wasted my time again not checking if my methods is ok or if it isn't being implemented already tho.~~

**Comment by Quarkstar** [comment]
I am sorry for that. I upgrade it because old version is not compatible with pixi v5.
Very sorry for wasting your time. ToT

**Comment by arthuro555** [comment]
No, you didn't waste my time don't be sorry 😅 . I'm upset against myself that I didn't verify the work of others and wasted my time because of that.

**Comment by 4ian** [comment]
No worries, in case for some reason we can't do the upgrade to Pixi v5 because of a blocking issue, we would still be able to use this PR to make an upgrade of Pixi particles.

**Pull request closed without merging**
