### PR TITLE
Clean examples folder

### PR DESCRIPTION
**Pull request by Bouh**
# Context

All non-starters examples are now fetched on the fly see #2697

Examples has been moved on :
https://github.com/GDevelopApp/GDevelop-examples

# Goal of this PR

This PR cleans the folder example for keeping only starters examples.
I was doing a clean pass in the examples folder for keeping only the starters, and I've started to load the example flappy bird clone, some image files cannot be fetched.

A check on all examples will be required for clean resources and check if the examples are working like attempt.

# Next step

Check and clean if needed the examples, continue with: 
https://github.com/GDevelopApp/GDevelop-examples/pull/4

### CODE REVIEW

**Comment by 4ian** [comment]
> This PR cleans the folder example for keeping only starters examples.

Yes, I totally forgot this! Only starter examples should be included now :) 

If an example is not working correctly, please open an issue (or make a PR) on the other repository :)

**Comment by 4ian** [comment]
@Bouh, can we merge already this PR? If I'm not mistaken, it's fine to do now, and we can work on the GDevelop-examples repository?

**Comment by Bouh** [comment]
> @Bouh, can we merge already this PR? If I'm not mistaken, it's fine to do now, and we can work on the GDevelop-examples repository?

Yes we can merge this one.

**Comment by 4ian** [comment]
Actually you've not deleted the files, you left the "Nouveau dossier" folder: 
image

**Pull request merged**
