### PR TITLE
Update howler

### PR DESCRIPTION
**Pull request by arthuro555**
Bump howler to v2.2.0
Useful for #1955 as it adds the spatial sound plugin, adds lots of bug fixes and support for m4b format.
Tested on both music examples with both music and sound actions.

### CODE REVIEW

**Comment by Bouh** [comment]
This need to be tested atleast once in an apk on mobile or in a webview on mobile.

**Comment by 4ian** [comment]
Ideally let's do some tests on mobile to avoid any obvious issue. Apart from that, happy to update Howler! :)

**Comment by arthuro555** [comment]
I tested with the preview over wifi, it works fine, and the discord members "Kappa" and "BlacKat Belladonna" tested the apk version for me. No issues spotted.

**Comment by Bouh** [comment]
And the patch notes from 2.1.2 to 2.2.0 have nothing to migrate, it's only fixes for us.
Ready to merge!

**Comment by 4ian** [comment]
If it's only bugfixes, sounds safe! Thanks @arthuro555 for the PR :)

**Pull request merged**
