### PR TITLE
Translation and formatting expressions

### PR DESCRIPTION
**Pull request by victorlevasseur**
**Native game only implementation**
**Do not merge now, opened for discussions.**

This PR adds two features.

# The features
## String formatting

A string expression provides a **string formatting feature** with a simple and easier syntax than the C syntax.

For example:
```
Format("{0} is {2} but the parser still need some {1}", "Formatting", "work!", "cool")
```

I implemented a small parser for this syntax, tell me how I can improve/optimize it. It uses ```std::string```
 internally to avoid unnecessary UTF8 iterating as the only relevant characters are {, } and the numbers.

To make this string expression possible, I added a new type to the parameters: ````variadic```. The kind of parameter obviously only works if placed at the end of an expression/action/condition parameters list. The extraInfo field is used to determine the type of the variadic parameter (only one type, either "string" or "expression", so this is more limited than the C++ parameters packs). 

These parameters accepts from 0 to an infinity of values. **The editors have not been updated to allow assisted insertion of such parameters making them impossible to use currently in conditions and actions. However, the expression parser has been updated not to throw error messages due to the parameter count with variadics.**

## Translation

Using the ```_("something here")``` string expression, strings can be translated. A button has been added to the "Project" ribbon to generate a .pot file from all marked strings and an action is provided to load a translation from a .mo file.

The .mo parsing is done with a simple "parser" I wrote too.

Here is the documentation draft of the translation feature: http://wiki.compilgames.net/doku.php/gdevelop/documentation/game_translation

# Discussion

**Some points I would like to discuss:**

 - this: #318 
 - The formatting parser is working but I think it can be largely optimized, ideas ?
 - Javascript implementation
 - GUI for variadic parameters in expressions editors
 - GUI for variadic parameters in instruction editor
 - Allowing (in the conventional way) .mo files to be added in the project resources ("Image bank").

### CODE REVIEW

**Comment by 4ian** [comment]
That's a pretty big project you have there :) Let's try to keep things simple, in particular for the Javascript engines where the translations could be a "simple" JSON file. In most cases, JS games will run in an environment (browser, Cocos2d-JS, Electron sometimes) that do not provide access to external files (browser in particular), so the translations will have to be built in.

**Comment by victorlevasseur** [comment]
If we explicitly allow adding other files to the "image" bank. Then, we can easily add builtin .mo files to projects, solving the problem for Javascript projects. Then, I chose the gettext format so that we don't have to bother with the translation editing tool as there are many already developped.

**Comment by 4ian** [comment]
.mo files are in a binary format so I'm not totally sure we can use it in Javascript (in Node.js there are surely ways to do it, but not in "Vanilla JS" in browsers). But some people already created workaround it seems: https://github.com/mikeedwards/po2json

**Comment by 4ian** [comment]
Sure it's a good idea to stick to existing formats :)

**Comment by victorlevasseur** [comment]
If we allow to embed the .mo files (either by putting them in the image manager or, like the sound, by automatically put them into the compiled project), we can load them using the ResourcesLoader from pixi or cc.Loader from Cocos2D. Then, we can get a byte array and I can, as I made for the C++ implementation, write a simple parser for the .mo file.

**Comment by victorlevasseur** [comment]
How can I get the file in a synchronous way without forcing it from being preloaded? (and is there a way to preload a file without asking the user to add the file to the "image bank"?)

**Comment by 4ian** [comment]
What is the issue with the `rawfile` parameter that you've added. What is your problem precisely?

**Comment by victorlevasseur** [comment]
The problem is how to preload the file during the loading of the game. Do I
need to create à "translation **file** manager" that uses PIXI.Loader like
the textures and the sounds managers ?

Le mar. 27 déc. 2016 15:41, Florian Rival <notifications@github.com> a
écrit :

**Pull request closed without merging**
