### PR TITLE
Move JSON and JS variable conversions to gdjs.Variable

### PR DESCRIPTION
**Pull request by arthuro555**
Moves javascript and JSON convertion utilities from `gdjs.evtTools.network` to gdjs.Variable.

### CODE REVIEW

**Review by 4ian — APPROVED** [review]
A welcome refactoring, thanks 👍

**Comment by 4ian** [comment]
Actually there is an issue with undefined variables that will crash, thankfully TypeScript caught this for us:
image

**Comment by arthuro555** [comment]
> Actually there is an issue with undefined variables that will crash

Yes, I was working on that and fixing the tests + formatting.

**Comment by 4ian** [comment]
Ah I started fixing this and pushed on the branch. Do you want to force push your changes?

**Comment by arthuro555** [comment]
No problem, I saw your push and just pulled the changes and merged it with my changes already

**Comment by arthuro555** [comment]
There is a small breaking change in the JSON formatting, it will look like `{"a":1}` instead of `{"a": 1}` now, do you think this could be an issue?

**Comment by 4ian** [comment]
Not an issue, the previous formatting was not very standard, and no one should really rely on this specific formatting :)

**Pull request merged**
