### PR TITLE
Update CircleCI configuration to have more memory

### PR DESCRIPTION
**Pull request by 4ian**
Don't show in changelog

### CODE REVIEW

**Comment by arthuro555** [comment]
image  
Weird, that's still not enough.... But it's 16 GB ram and I can build it with my 8GB ram 🤔

**Comment by 4ian** [comment]
Yeah I think it's another problem, like a memory leak. Especially considered that it used to work on CircleCI and started failing from one day to the other. I wonder if it can be related to the Node.js version or something like that. 8GB should be really more than enough to build the app, even less.

**Comment by 4ian** [comment]
Seems like the solution was to set `export NODE_OPTIONS="--max-old-space-size=8192"`, to allow Node.js to use more space than the default limit. Unsure why it's needed here and not when building locally. Anyway!

**Comment by arthuro555** [comment]
Nice 👍

**Pull request merged**
