### PR TITLE
Experimental build/steamworks

### PR DESCRIPTION
**Pull request by ClementPasteau**
See https://github.com/4ian/GDevelop/pull/5439
And https://github.com/4ian/GDevelop/pull/5401

### CODE REVIEW

**Comment by Silver-Streak** [comment]
Just to understand, as HelperWesley and I commissioned Arthuro on the steamworks integration; What is the reversion about?

Is there a fundamental issue that needs to be refactored entirely, or is this a minor thing that just needs to be updated before going into the main build?

**Comment by 4ian** [comment]
> Is there a fundamental issue that needs to be refactored entirely, or is this a minor thing that just needs to be updated before going into the main build?

Integration of this is making the code signing of the macOS version of GDevelop fail entirely. We need to spend time understanding then fixing this. This was reverted so that this does not block releases of GDevelop.

**Comment by Silver-Streak** [comment]
@4ian after your last change I had the builds-reattempt. As far as I can see they succeeded (including the mac build)? But I'd defer to you on what else this needs to proceed.

**Comment by arthuro555** [comment]
@Silver-Streak The change from 4ian was basically downgrading steamworks.js to verify it is a regression on their side, but we cannot keep it downgraded since the integration relies on the latest version. To proceed we'd need to either

- Roll out our own distribution of steamworks.js with the old mac compilation pipeline (complex, not a durable solution)
OR
- Wait for @ceifa to fix the mac compilation upstream (ideal, but not controlled by us)

**Comment by arthuro555** [comment]
I've done a test, could you try changing `steamworks.js` to `@gdevelop/steamworks.js`? I've disabled linking with zig and linked with the MacOS tools instead (as done before) for this build (as you can check out on my for of steamworks.js).

Alternatively, could I get push permissions for the repository so that I can do it myself? I like to think that I have proven myself to be trustworthy enough for this and it would simplify such issues in the future as well 🙏

**Comment by arthuro555** [comment]
The signing was a success 🥳

**Comment by 4ian** [comment]
We would probably need to have the link to the repo of the forked steamworks.js somewhere. Can you share access with us? Can you open a PR on Steamworks.js repo?

Because this is becoming a mandatory dependency and I would rather not have to maintain yet another dependency :)

**Comment by arthuro555** [comment]
...huh

The error we had is fixed, but now we have a new error...
The error is unrelated to Steamworks, so I think it might be because of the package-lock that I committed that was previously left uncommitted?

**Comment by ClementPasteau** [comment]
@arthuro555 you seem to have deleted the package-lock of the electron-app in your PR indeed. Was this done on purpose?

**Comment by arthuro555** [comment]
Huh, it wasn't, I thought I'd committed it not deleted it

**Comment by arthuro555** [comment]
Alright, looks good?

**Comment by ClementPasteau** [comment]
We'll wait a bit to merge it, as waiting for a performance fix to be released first, and we'd rather keep that hotfix on its own.

**Comment by 4ian** [comment]
Bugfixes are released, I think we're good to merge this! :)

**Comment by ClementPasteau** [comment]
Let's goooooo! Thanks @arthuro555 this will be in the next release, let's keep an eye on any feedbacks from the early users!

**Review by 4ian — APPROVED** [review]
Let's remove the CSC_FOR_PULL_REQUEST=true

**Pull request merged**
