### PR TITLE
Fix events sheet not wrapping on small screens

### PR DESCRIPTION
**Pull request by AlexandreSi**

### CODE REVIEW

**Review by ClementPasteau — APPROVED** [review]
lgtm, can you share a screenshot of the change?

**Comment by AlexandreSi** [comment]
Before:
image


After:
image

**Comment by tristanbob** [comment]
This makes it hard to tell what is a condition vs action.  What could we do visually to help with this?  I see it is a darker color, but how about a slight indentation also?  

I wonder what sub-events will look like.

**Comment by AlexandreSi** [comment]
There's already the left padding for the actions, you can see they're a bit off. I don't know if it's enough.
This display was the default one before a regression was introduced, so I just fixed it.
But the mobile display of the events sheet can be a whole discussion to have

**Pull request merged**
