### PR TITLE
Added the Ladder climbing speed attribute

### PR DESCRIPTION
**Pull request by PawBud**
this is a fix for the issue: _#1563_ 

as suggested by @PascalLadalle

### CODE REVIEW

**Comment by 4ian** [comment]
Why did you close the PR? :) That's a good start! Only missing the JS extension implementation :)

**Comment by PawBud** [comment]
Ohh @4ian i am extremely sorry but there seems to be a problem with git. Hence I am trying to fix it :)

**Comment by 4ian** [comment]
Make a git clone and always keep your master branch synchronized with GDevelop master branch, never push anything on it (especially because I "squash" the PR commits and put them on master, I'm not "merging" them).

See a few pointers here: https://github.com/4ian/GDevelop/blob/master/newIDE/docs/Using-git-to-make-and-propose-changes.md

**Comment by PawBud** [comment]
Thanks a lot, @4ian; I appreciate the fact that you are personally helping me with such basic mistakes :1st_place_medal:

**Pull request closed without merging**
