### PR TITLE
Upgrade the editor, and exported desktop games, to Electron 18 (#3806)

### PR DESCRIPTION
**Pull request by 4ian**
Opening this PR so that builds are automatically made for Windows/macOS/Linux. Let's see if it works :) 

See #3806 for the original PR.

TODO:
- [x] Fix preview not having access to @electron/remote
  - [x] Double check proper working of screenshot/advanced window/fs extensions (preview, dev version).
  - [x] Double check proper working of screenshot/advanced window/fs extensions (preview, built version).
- [x] Double check proper working of screenshot/advanced window/fs extensions (exported game).
- [x] Verify BBText and Tilemap (using requireModule) still working (editor, dev version).
- [x] Verify BBText and Tilemap (using requireModule) still working (editor, built version).
- [x] Verify BBText and Tilemap (using requireModule) still working (preview, dev version).
- [x] Verify BBText and Tilemap (using requireModule) still working (preview, built version).
- [x] Verify Piskel:
  - [x] macOS, dev version
  - [x] macOS, built version
  - [x] Windows, dev version
  - [x] Windows, built version
- [x] Check Debugger:
  - [x] macOS, dev version
  - [x] macOS, built version
  - [x] Windows, dev version
  - [x] Windows, built version
- [x] Check dev tools on Windows
- [ ] revert Macos circleci change before merging.

### CODE REVIEW

**Comment by willianholtz** [comment]
Hey @4ian 
With the Electron update, at least in my tests, it started working normally again. Regarding #3793
The same with #3845

**Comment by 4ian** [comment]
Experimental builds to test:

* [Windows](https://gdevelop-releases.s3.amazonaws.com/experimental-build/electron-18/latest/GDevelop%205%20Setup%205.0.132-testing1.exe)
* [macOS](https://gdevelop-releases.s3.amazonaws.com/experimental-build/electron-18/latest/GDevelop%205-5.0.132-testing1-mac.zip)
* [Linux](https://gdevelop-releases.s3.amazonaws.com/experimental-build/electron-18/latest/GDevelop%205-5.0.132-testing1.AppImage)

**Comment by willianholtz** [comment]
Well, I know I've already done the tests, but it's worth posting here how it was before the Electron update and how it is now.
I believe a video is worth a thousand words:
https://youtu.be/DzPPBE5Edpk

**Comment by 4ian** [comment]
Update with latest changes:

* [Windows](https://gdevelop-releases.s3.amazonaws.com/experimental-build/electron-18/latest/GDevelop%205%20Setup%205.0.133-testing1.exe)
* [macOS](https://gdevelop-releases.s3.amazonaws.com/experimental-build/electron-18/latest/GDevelop%205-5.0.133-testing1-mac.zip)
* [Linux](https://gdevelop-releases.s3.amazonaws.com/experimental-build/electron-18/latest/GDevelop%205-5.0.133-testing1.AppImage)

**Comment by willianholtz** [comment]
As usual, I bring a test video for analysis.
https://youtu.be/qEhaNk_uyGA

As @4ian  described, all updates are included, however note that at the end of the demo the "wait" function seems to bug something.

At first I put this function to create as soon as I started the game, waiting just 2 seconds. What actually creates the tree. But in the end, that shouldn't happen.. But that's another topic

I could also see a big improvement in rendering.

Before
Screenshot_20220503_140906

After
Screenshot_20220503_140552

**Comment by 4ian** [comment]
image

Move the trigger once in the first condition. Otherwise you every frame you run a new wait that will wait 2 seconds before doing nothing, so you'll have tons of actions waiting in memory.

**Comment by 4ian** [comment]
@nilaymaj We probably need to upgrade games too - otherwise some new web APIs could be used in previews and not in exported games (not to mention the performance drop on Linux because of the old Electron version).

Let me know if you want to take a look, otherwise I'll use your list to see if there is anything to upgrade (I think there will be some usage of the remote module + a package.json to update at least).

**Comment by 4ian** [comment]
New (final?) version with now the games also updated to be exported on desktop with Electron 18. Same links as before:

* [Windows](https://gdevelop-releases.s3.amazonaws.com/experimental-build/electron-18/latest/GDevelop%205%20Setup%205.0.133-testing1.exe)
* [macOS](https://gdevelop-releases.s3.amazonaws.com/experimental-build/electron-18/latest/GDevelop%205-5.0.133-testing1-mac.zip)
* [Linux](https://gdevelop-releases.s3.amazonaws.com/experimental-build/electron-18/latest/GDevelop%205-5.0.133-testing1.AppImage)

**Comment by willianholtz** [comment]
In my tests, both platforms were 100% exported. The old version, it was unusable when exported in linux (appimage)

**Comment by 4ian** [comment]
Cool! Hope we can have this in the next official version of GDevelop then.

**Comment by 4ian** [comment]
Everything test, we should be good! Developers, don't forget to run again npm install in `newIDE/app` and `newIDE/electron-app`.

**Comment by tristanbob** [comment]
> New (final?) version with now the games also updated to be exported on desktop with Electron 18. Same links as before:
> 
> * [Windows](https://gdevelop-releases.s3.amazonaws.com/experimental-build/electron-18/latest/GDevelop%205%20Setup%205.0.133-testing1.exe)
> * [macOS](https://gdevelop-releases.s3.amazonaws.com/experimental-build/electron-18/latest/GDevelop%205-5.0.133-testing1-mac.zip)
> * [Linux](https://gdevelop-releases.s3.amazonaws.com/experimental-build/electron-18/latest/GDevelop%205-5.0.133-testing1.AppImage)

If people want to test a Windows export on this version (v133) I have packaged a game with 13k particles that can be used as a benchmark.  I also included the v132 version for comparison.

RainbowWaterfall_5.0.132.exe
RainbowWaterfall_5.0.133.exe

https://filetransfer.io/data-package/Ujv4d8hI#link
(I think this link works for 21 days)

**Comment by 4ian** [comment]
Ok, thanks for confirming!

**Pull request merged**
