### PR TITLE
 Add example for screenshot extension 

### PR DESCRIPTION
**Pull request by Wend1go**
This includes the use of the FileSystem extension too.

### CODE REVIEW

**Comment by Wend1go** [comment]
Just had a look at the project's json file. Is it possible to erase the private information from an example before submitting it? The creators user name and folder structure are contained in the paths of "latestCompilationDirectory" and "projectFile" (which are wrong anyway when the project get uploaded)

**Comment by 4ian** [comment]
You can manually edit the json to remove them :) Just put an empty string
(and check that you can still open the game to be sure that nothing is
broken ;))

**Comment by 4ian** [comment]
We could almost write a script (in newIDE/app/scripts) that removes these
information. Ideally, the user preferences (these folders, but also grid
size, camera position in scene editor) could be written in another file.
Will have a look at this once I work on being able to split the project
file in multiple files

**Comment by Wend1go** [comment]
The wiki articles for [file system](http://wiki.compilgames.net/doku.php/gdevelop5/all-features/filesystem) and [screen shot](http://wiki.compilgames.net/doku.php/gdevelop5/all-features/screenshot) are ready too.
I'd really appreciate if a native English speaker would do a prove read. :)

**Comment by zatsme** [comment]
I'll dew dat rite nauw 😃

**Comment by zatsme** [comment]
I didn't like the fact you've used folder and directory to mean the same thing so wondered if folder or directory was more common in Mac land so I thought I'd check.... and found this.... 

'The Mac OS X file system stores files within folders, also known as directories. The top, uppermost folder is known as the root directory. Folders located within (or beneath) the root directory are known as subfolders or subdirectories, two different ways of saying the same thing.'

So I guess mixing and matching is the correct way to go 😆 it's nice to see that mac users are just as confused as the rest of us 👍

**Comment by zatsme** [comment]
Made some small changes, Looks fine to me 👍

**Comment by 4ian** [comment]
Merging the example now, thanks for doing it :)
I've quickly read the articles, for formatting prefer Markdown syntax in general (#, ##, ### for titles, backticks (`) for monospace, triple backtick for "code blocks" expression) and avoid legacy things like "WRAP" (instead, use <note> even if it's not standard markdown).

(Markdown is more widely recognized than Dokuwiki syntax so I prefer to use this syntax for portability in the future)

**Pull request merged**
