### PR TITLE
Enable macOS build for Apple Silicon and arm64 builds for Linux

### LINKED ISSUE #3971: Apple Silicon (M1 Pro/Max/Ultra) native support?
Are there any immediate or future plans to have GDevelop support Apple Silicon natively without having to use Rosetta?

### PR DESCRIPTION
**Pull request by 4ian**
Fix #3971

### CODE REVIEW

**Comment by arthuro555** [comment]
Could we also enable it for linux? That would allow using it on raspberry pi, and I believe a considerable amount of GDevelop's users may want to use it from there (Kids that are learning to code on their RPI, schools that use RPIs as cheap school computers, ...)

**Comment by 4ian** [comment]
@fannieyan @AlexandreSi any chance you can try the build on a Apple Silicon mac?

https://gdevelop-releases.s3.amazonaws.com/experimental-build/m1/latest/GDevelop%205-5.0.136-arm64.dmg

(Sorry this is based on a an old version, I'm rebasing now)

**Comment by 4ian** [comment]
@AlexandreSi @fannieyan Can you try:

https://gdevelop-releases.s3.amazonaws.com/experimental-build/m1/latest/GDevelop%205-5.0.138-arm64.dmg

to see if it's working?

**Review by CollinsVakayil — COMMENTED** [review]
Was able to successfully run this build on Apple Silicon (M1 Pro) MacBook Pro.

**Comment by 4ian** [comment]
Nice, we should be able to enable this then if you've not observed anything wrong.

**Comment by CollinsVakayil** [comment]
> Nice, we should be able to enable this then if you've not observed anything wrong.

So far it works as expected. Nothing out of the ordinary.

**Review by CollinsVakayil — APPROVED** [review]

**Review by CollinsVakayil — APPROVED** [review]
It's a go from me!

**Comment by CollinsVakayil** [comment]
> Nice, we should be able to enable this then if you've not observed anything wrong.

Any idea what's preventing review of this build? It works.

**Comment by 4ian** [comment]
I've merged this and we'll distribute these going forward if there are no issues. The only downside is that this makes the CI significantly longer for macOS (because of notarization, we're losing at least 10min at every build on master), so we may have to consider reducing the builds to just one a day or something like this.

**Comment by CollinsVakayil** [comment]
> I've merged this and we'll distribute these going forward if there are no issues. The only downside is that this makes the CI significantly longer for macOS (because of notarization, we're losing at least 10min at every build on master, which costs money), so we may have to consider reducing the builds to just one a day or something like this.

Thank you, forgive my ignorance on the CI regarding this matter, but from what I understand instead of making seperate builds for x64 and Apple Silicon; wouldn't it be better to have it as a universal build that runs native on both architectures respectively?

**Pull request merged**
