### PR TITLE
Add documentation link

### PR DESCRIPTION
**Pull request by piyushpalawat99**
Added a separate documentation page for the conditions/actions of the extension. The other two pages can work as introduction to the features while the new page has a sole purpose of helping users with the conditions/actions.

### CODE REVIEW

**Comment by 4ian** [comment]
I think the page should rather be a subpage of http://wiki.compilgames.net/doku.php/gdevelop5/objects/base_object
What do you think? It's not part of the basic game making tutorial - which goal is to be a one pager quick introduction to the most important things to understand GDevelop.

**Comment by piyushpalawat99** [comment]
I have moved the wiki page. The reason I chose basic game making tutorial was because the base object page guided the user to basic game making page for information on common features and so I thought that maybe it'd be good if common features and common conditions/actions are linked. Sorry for the misunderstanding on my side. 😅

**Comment by 4ian** [comment]
No worries :) 
Merging this now. I've updated the description of the argument that you changed.
In the page http://wiki.compilgames.net/doku.php/gdevelop5/objects/base_object/events, could you change the page to avoid referring to the user?
For example, avoid:

* "you can send a ray of light"
* "This condition allows us to compare [...]"

but instead:

* "This action sends a virtual ray (think of it as a ray of light) [...]"
* "This condition compares [...]"

In general, don't refer to the user (except in tutorials). Be concise and refer directly to what the thing you're describing is doing. 

Also, could you remove the "We compare the Y position of the object using the appropriate “Sign of the test”."? This is adding noise to the documentation and should be considered obvious for someone reading this page (because it should be easy to understand - if it's not the case, we have changes to do in the interface, not the documentation - and covered already in tutorials).

**Comment by piyushpalawat99** [comment]
Thanks, I'll fix the documentation part.
I was wondering if there is a reason for referring to the second object in the plural form as "Objects"?

**Comment by 4ian** [comment]
It's subtle but the difference is that the action is repeated for each of the first object against all of the second objects.

**Pull request merged**
