### PR TITLE
Add preload auto for fix video in next upgrade of electron v8.2.0

### PR DESCRIPTION
**Pull request by Bouh**
https://github.com/4ian/GDevelop/pull/1589#issuecomment-609425073

### CODE REVIEW

**Comment by 4ian** [comment]
Let's add a comment saying it's only for Pixi 4.8.6 and can be removed in Pixi 5 :)

**Comment by 4ian** [comment]
Done, merging now! Thanks :)

**Comment by 4ian** [comment]
Also @Bouh, should this be done in the runtime object too, for exported games? Or is it not useful?

**Comment by Bouh** [comment]
Bug is only in IDE, the runtime object renderer (preview and exported games) have been already edit in the past.

https://github.com/4ian/GDevelop/blob/master/Extensions/Video/videoruntimeobject-pixi-renderer.js#L27

**Comment by 4ian** [comment]
Ah I missed that, great then 👍

**Pull request merged**
