### PR TITLE
Add support for creating instances by dropping objects from objects list

### PR DESCRIPTION
**Pull request by 4ian**
Add drag'n'drop from objects list.

* Should be more intuitive than selecting object then making one click.
* This will allow the blue selection background to be used for highlighting the object in https://github.com/4ian/GDevelop/pull/649
* Tested on Chrome and Firefox.

Ideally `SceneEditor/index.js` should be flow typed as it's becoming large and this could avoid regressions/mistakes.

### CODE REVIEW

**Comment by 4ian** [comment]
@blurymind Are you able to test this branch? If yes, let me know if that's working for you.

dragdrop

What I recommend is that we merge this first, then you can update your PR to have the highlight of the selected object.

**Comment by zatsme** [comment]
Looking at your GIF it seems to me that you need to drag only the sprite otherwise it's not obvious where it's going to drop.  Yes, I know you can move it after... but it looks wrong.

**Comment by 4ian** [comment]
I know it's a bit distracting but I've not been able to find how to prevent this :/

**Comment by blurymind** [comment]
It seems to work great :) I tested it and changed my pull so it compliments this one.

Unfortunately I think that it duplicated some of the changes in this one. Hope its not a problem

**Comment by blurymind** [comment]
I can resubmit it after you merge this one if it is a problem

**Comment by Bouh** [comment]
To avoid moving in the list, there can be a timer of 0.5s on the touch, if it is below we put on the scene, and above we move in the list ?

**Comment by 4ian** [comment]
It's more complicated, unfortunately. The reordering by drag'n'drop is done by the list. When dragging an object, this drag'n'drop is activated.
I cannot deactivate it without hacks that are super dirty and still breaking in even more nasty ways.

I'm thinking that we should almost have no reordering by drag'n'drops of lists by default, and have an option in context menu called "Reorder". When clicked, the list switch to reordering (with drag handles on the left, like the list of layers) and things can be drag'n'dropped (only in the list).
When reordering is not activated, drag'n'drop would only work on the scene (and for other list, would do nothing).

What do you think? It's a pattern that is commonly used on mobile (you activate an option showing drag handle on the left of items in a list, that you can move). But it would requires reworking quite a lot of lists (resources editor, groups, objects list) so that it's consistent everywhere.

**Comment by blurymind** [comment]
The reorder move while drag to drop doesnt bother me that much personally. If its causing so much refactoring everywhere is it really worth investing time in it over other things?  :)

**Comment by Bouh** [comment]
You talk about handles as for layers why not put this handle by default, then the other part would be used for the slide placed in the scene.

Because a button checked to activate the move is one more button. The fewer clicks, the simpler it is, the more visual, the simpler it is too.

Otherwise I agree with blurymind, if this is too complicated let's leave it as it is, it doesn't bother too much, let's wait for user feedback to change if it doesn't work.

Red : move in list
BLue drag and drop on scene
idea

**Comment by 4ian** [comment]
@bouh Yes your mockup looks right, that would be like this. I was just concerned that this was taking too much space on screen.

Anyway for now I'll let this as is, as it's still an improvement over the current situation (even if it's a bit disturbing to see the objects moves when you drag'n'drop, should not be too much of a problem).
Will rework the list later :)

**Comment by blurymind** [comment]
Thank you @4ian . This is an awesome usability addition :D

**Pull request merged**
