### PR TITLE
New "Rosé Pine" Theme (Code Editor & UI Theme)

### PR DESCRIPTION
**Pull request by EhanAhamed**
Hi there, I made a new GDevelop theme that uses the [Rosé Pine color scheme](https://rosepinetheme.com).

The color scheme is licensed under MIT, however I wasn't able to find any attribution or 3rd party licenses page/panel in the GDevelop source code or the webapp, if GDevelop does have one and I simply missed it, please let me know so I can add Rose Pine's license.

The GDevelop theme is both a UI theme using GDevelop's already existing UI theme system and a code editor theme that's adapted from an existing Monaco Editor theme for Rose Pine.

I also wanted to note that the UI theme uses a CSS icon filter, like the one used in the GDevelop Nord UI Theme, that changes the icons to fit with the theme's colors.

This pull request changes nothing other than adding a new Monaco editor theme json file, adding said file to the Monaco Editor theme registry file, adding a new UI theme folder and adding said folder and it's contents to the UI theme registry file.

Screenshots of this theme, both the code editor and user interface, are included below.

Scene Editor
screenshot

Events Sheets
screenshot

Extensions Editor (With Code Editor/Monaco Editor)
screenshot

Game Settings/Properties
image

Thank you for your time, and have a great day/afternoon/night!

### CODE REVIEW

**Comment by 4ian** [comment]
Very nice! Thanks for submitting this.

> however I wasn't able to find any attribution or 3rd party licenses page/panel in the GDevelop source code or the webapp, if GDevelop does have one and I simply missed it, please let me know so I can add Rose Pine's license.

There is none in the app, I would have recommended at first sight that you add the license in the RosePine folder. Though this is not based on any source file from it, but from their specification I guess... so not sure if it makes sense, because your contribution is under the MIT license of the GDevelop source.
Maybe we can have a file "About Rose Pine.md" that have a link to their website/specification, and the content of their license? Seems like a good way to track this for the future (aund to guto-generate a third party license panel in the future).

Apart from that, nothing much to say. The close buttons in the panels are white on a fairly light color, surely because it's a dark theme. Maybe consider using a darker color for these panels, otherwise this will be ok anyway.

**Comment by EhanAhamed** [comment]
Hi There, @4ian!

Thanks for your tremendously insightful suggestions! I've added license information to a markdown file in the theme folder and I've changed the (*title*bars? *menu*bars? I'm not sure what to call them?) to be reversed with light text on a medium-dark background instead of dark text (and incorrectly colored light icons) on a light background. It now looks like so:
image

Thanks and if there is any more improvements I can make or any mistakes I didn't yet find please let me know!

**Comment by 4ian** [comment]
Awesome! The colors look better now. I'm happy to merge this - and feel free to push other PRs should you want to improve/adapt/rework any color (it's sometimes hard to get a new theme good on the first try, it's no problem to slightly change the colors later even if it's merged).

>  (titlebars? menubars? I'm not sure what to call them?)

Good question, I think these are "titlebars" as they contain the titles of the "panels".

**Comment by 4ian** [comment]
Thank you 👍

**Pull request merged**
