### PR TITLE
fix issue #672 - undesired instruction editor parameter autocomplete...

### PR DESCRIPTION
**Pull request by blurymind**
...pop up on mount.
https://github.com/4ian/GDevelop/issues/672
46233624-487f0100-c36b-11e8-9ca3-3bdb03a67051

### CODE REVIEW

**Comment by 4ian** [comment]
This makes the window requires an extra click on the first field to be usable with keyboard. Can we try to find another solution?

**Comment by Lizard-13** [comment]
Related: http://forum.compilgames.net/viewtopic.php?f=20&t=10719&sid=6a22728fcb3fe2bad5af0ef120956861
I can confirm it, in the online version and desktop app (Windows 7 and Ubuntu 16.04), a single click doesn't close this opened-by-default drop down.

**Comment by blurymind** [comment]
not sure how to approach this 

If it gets focus but has no selection list, does that make it useful? Could you still select another object with the keyboard without an extra click?

**Comment by blurymind** [comment]
One suggestion is to somehow give focus on the last (usually value) element  instead, but then TAB-ing to next needs to cycle back to the first

**Comment by blurymind** [comment]
sorry, I have to do the pull again due to deleting the original fork I had on this

New pull here
https://github.com/4ian/GDevelop/pull/709

**Pull request closed without merging**
