### PR TITLE
Allow using resources as behavior properties

### PR DESCRIPTION
**Pull request by arthuro555**
It looks like an oversight, since the necessary props were already being passed down to Behavior Editors, but then not to the generic properties editor. 
This allows using resources as behavior properties.

Before: 
image
After:
image

### CODE REVIEW

**Review by Bouh — APPROVED** [review]

**Comment by D8H** [comment]
It looks safe to me.
Do you edit the extension by hand to have resource properties?
Do you think it should be added to the list? It seems it could be useful for custom objects.

**Comment by arthuro555** [comment]
>  Do you edit the extension by hand to have resource properties?

Yes, although a JsExtension would not need to.

> Do you think it should be added to the list? It seems it could be useful for custom objects.

Probably, but that'd likely require extra work to add a way to actually get access to the JSON from events?

---

Actually, I just spotted an issue. This appears to work at first, but when closing and reopening the dialogue after setting a resource, the field is empty again...


https://user-images.githubusercontent.com/19349038/234124201-df97a9f5-91da-4656-aee9-a2e865ac2faf.mp4

**Comment by arthuro555** [comment]
Ok, the problem was just with custom behaviors since they did not know what type of data the "resource" property type corresponded to.

**Comment by arthuro555** [comment]
Bump, I think this should be ready to merge now :)

**Comment by arthuro555** [comment]
Bump

**Review by 4ian — APPROVED** [review]

**Pull request merged**
