### PR TITLE
Procedural Generation Example

### PR DESCRIPTION
**Pull request by Add00**
I converted [this](https://github.com/4ian/GDevelop/issues/2214) issue into a pull request. Supper thanks to arthuro for making the example more clear.

### CODE REVIEW

**Comment by 4ian** [comment]
Thanks! Commented on the original issue.

**Review by 4ian — COMMENTED** [review]
Seems like `fixtures/procedural-generation/procedural-generation.json` is missing, can you try again launching the two scripts related to examples?

**Comment by Add00** [comment]
I've fixed the issue, so now the newest commit has a `procedural-generation.json` file.

**Comment by 4ian** [comment]
Thanks! 👍

**Pull request merged**
