### PR TITLE
Update Emscripten version

### PR DESCRIPTION
**Pull request by arthuro555**
- Updates the docs to instruct to use version `3.1.21`. 
  - This is not the latest version, but `3.1.22` introduces an update to LLVM 15, which breaks compilation. It is likely fixable, but I didn't look too deeply into it. 
  - People will have to update their emsdk installation themselves!
- Update the docs to give instructions for powershell, the default terminal in modern windows
- As a part of the update, migrate from `emconfigure` to `emcmake`
- As a part of the update, change a few link flags
- Switch to recommended optimization settings for production (`-O2` -> `-O3 -flto`)
- Updated ninja
- Added documented debugging compiler/linker flags in commented out form for convenience
- Enable flags for exceptions/stack traces to hopefully get more descriptive error messages from crashes caused by C++ code

### CODE REVIEW

**Review by 4ian — COMMENTED** [review]
Nice, thanks for taking the time to upgrade!

- For exceptions (`-fwasm-exceptions`), in which case is this useful? Exception handling is still new in Safari 15.2 (https://webassembly.org/roadmap/) which makes me a bit nervous (past broken implementation of wasm in Safari + people still using iOS 15)
- Any impact on the size of the output binary or performance with `DEMANGLE_SUPPORT=1` and `ASSERTIONS=1`?

The other debugging options seems very useful, thanks for adding them :)

**Comment by 4ian** [comment]
Answering my question about size, it seems to be in the same range, according to what I see being built by the CI:

https://app.circleci.com/pipelines/github/4ian/GDevelop/10956/workflows/0cc0ae34-53ee-45da-9a24-e0855d654062/jobs/12380
https://app.circleci.com/pipelines/github/4ian/GDevelop/10953/workflows/992d1724-5221-49bc-af55-7fed356f0385/jobs/12373

Before:
image

After: 
image

Still worth checking if exceptions could be dropped or not.

**Comment by arthuro555** [comment]
We probably can disable exceptions, I haphazardly enabled flags that would likely improve the stack traces because it is to me a big pain point to not be able to see when a user gets a weird C++ error what the actual error is or what code path lead to this, what nested call is responsible for it, there's only at most a function call name done in JavaScript to C++. I am not certain in any way that it will help, although if it does what I assume it may do, that would be honestly make it so much easier to find and fix bugs. I had seen green on caniuse so I assumed support on the platforms was present, but if it's still new on safari it might be a better idea to get rid of it indeed.

Maybe we could make split builds of the library, one for the PC/mobile build with these kinds of safety/debugging features, and one for the web build that is more optimized for binary size?

**Comment by 4ian** [comment]
This seems finally working!

**Comment by 4ian** [comment]
Seems like there was a fix for loading the wasm library: https://github.com/4ian/GDevelop/pull/5942

**Pull request merged**
