### PR TITLE
Highlight add new event button

### PR DESCRIPTION
**Pull request by AlexandreSi**
My try at having the button glow to make it more visible, only when there is no event

demo_glowing_button

### CODE REVIEW

**Comment by tristanbob** [comment]
I like the color glow effect. 

However, why not use the same strategy that you recently used when creating a new project?  Previously users had to click "Add scene", but you skipped that step and created it for them.  Why not create an empty event?

**Comment by 4ian** [comment]
I think there is a limit to find between "presenting you with ready made stuff" and "let you discover the concepts by your own". In the case of a scene, it was less important to teach it to a new user. What is important is that a user discovers what's an object, what's a behavior, what's an event. But adding a scene to a project can be discovered later (I click on the project manager and "wow there is already a scene but I can make more of them").

For events, it's a bit different. People have to learn that they can add an event, composed of conditions and actions. If we skip the events creation, they might assume there is a unique single event and that each condition is associated to a unique action (we already had this confusion for some users). So I think it's better if they do themselves the work of clicking on "Add event", so they understand this can be repeated.

**Comment by AlexandreSi** [comment]
As I'm away for a bit, if you want to merge the contrast boost, feel free to remove the last commit!

**Comment by 4ian** [comment]
I've merged the contrast fix 👍 Letting this open so we can continue discussing this.

**Comment by Bouh** [comment]
Careful in this pr there is not just a Glow effect, you include changes for research matches.

**Comment by AlexandreSi** [comment]
Oups, I did it again!
Closing it any way, we will soon change it I guess.

**Pull request closed without merging**
