### PR TITLE
Added new action "Jump emitter forward in time"

### PR DESCRIPTION
**Pull request by tristanbob**
First attempt at: https://github.com/4ian/GDevelop/issues/4984

I believe I have changed the necessary parts, but I'm not sure.  My development server (npm) did not show this new action, so I think I need to compile the changes to C++ files?

How do I do this?

### CODE REVIEW

**Comment by AlexandreSi** [comment]
To build GDevelop.js and see the action in your project, you should follow [this README](https://github.com/4ian/GDevelop/blob/master/GDevelop.js/Readme.md). This part is a bit tricky and the installation of all the needed softwares is prone to issues so you might encounter some issues.
I can do it and send you the exec so that you can try it yourself?

**Comment by tristanbob** [comment]
Thanks @AlexandreSi! I was able to successfully build a development version of the app with my new feature, and it works great!

## Sample project
[JumpEmitterForwardInTime.zip](https://github.com/4ian/GDevelop/files/10787116/JumpEmitterForwardInTime.zip)

## Video

https://user-images.githubusercontent.com/8879811/220180803-9547a810-de51-46ec-a46e-f03ae07b4893.mp4

**Review by 4ian — APPROVED** [review]

**Comment by ClementPasteau** [comment]
You're missing formatting to pass the tests :)
Can you run `npm run format` in GDJS folder and commit the changes? @tristanbob

**Comment by tristanbob** [comment]
> You're missing formatting to pass the tests :) Can you run `npm run format` in GDJS folder and commit the changes? @tristanbob

Thanks @ClementPasteau!  
I am OK if anyone wants to work on this PR to get it published sooner than later.

**Comment by 4ian** [comment]
@tristanbob if you want to try adding the new field as a property of the object:

- UI: Add a new field in `newIDE/app/src/ObjectEditor/Editors/ParticleEmitterEditor.js`. Probably a `SemiControlledTextField`. You need to plug it into a property of the `particleEmitterConfiguration`, i.e: use a set function and a get function...
- Core: ...this means you need to add them in C++. In `Extensions/ParticleSystem/ParticleEmitterObject.h`, add two functions to Get and Set this property (like `GetZoneRadius` and `SetZoneRadius`). You also need the variable which will hold the value, add one like `double zoneRadius;` (double = a number).
- Core: finally, in `Extensions/ParticleSystem/ParticleEmitterObject.cpp`, ensure your new property is saved and loaded like the rest. Special case: don't forget to update `ParticleEmitterBase::Init` (that's a C++-ism we can remove probably later) and give a default value in the list in the constructor (`ParticleEmitterBase::ParticleEmitterBase`).
- Bindings: almost done for the "Core", modify Bindings.idl to add your two new functions to expose them to the JavaScript. If you try now to recompile and re-run the IDE, you can now set and modify the field!
- Runtime (logic): You can now implement this field in the runtime. Take a look at how `zoneRadius` is used in `Extensions/ParticleSystem/particleemitterobject.ts`. Do the same for your new field, so that it's stored by the object. The name of this field is the same as the name you put in the Serialize/Unserialize method in the .cpp file.
- Runtime (rendering): Almost done, if you `console.log` somewhere your field, you should see its value. You can now pass it to the renderer. Because it's a field used only at the beginning, I think you need to call `this.emitter.update` in `Extensions/ParticleSystem/particleemitterobject-pixi-renderer.ts` in the `constructor` (alternatively, use a boolean to do it once in the `update` method, but I don't think it would be good, because you want to forward the time as soon as the object is created).

And that should be it! 
It's more complex than a traditional object made in a `JsExtension.js`  file because C++ is involved, but it's "just" a bit of back and forth to do.

**Pull request merged**
