### PR TITLE
SFML offscreen rendering

### PR DESCRIPTION
**Pull request by victorlevasseur**
In the IDE, do the SFML rendering offscreen (thanks to a ```sf::RenderTexture```) and display it by drawing a ```wxBitmap``` on a ```wxControl``` (it manages focus, not like a ```wxPanel```).

**TODO list:**
 - [x] **Basic implementation**
 - [x] Adapt GDCpp and IDE to use it
 - [x] Generate all SFML events from wxWidgets events
   - [x] ```sf::TextEntered```
   - [x] ```sf::KeyPressed```
   - [x] ```sf::KeyReleased```
   - [x] ```sf::MouseButtonPressed```
   - [x] ```sf::MouseButtonReleased```
   - [x] ```sf::MouseMoved```
   - [x] ```sf::MouseWheelScrolled``` (and ```sf::MouseWheelMoved``` which is deprecated by the way and still used in GDevelop)
   - [x] ```sf::MouseEntered/Left```
 - [ ] Testing on Mac OS X @4ian 
 - [ ] Reenable preview in separate window feature

### CODE REVIEW

**Comment by 4ian** [comment]
@victorlevasseur I see that you've checked all the checkboxes concerning SFML/wxWidgets events. :) Do you want me to test it on OS X?

**Comment by victorlevasseur** [comment]
You can try it.

**Comment by 4ian** [comment]
Rendering of the objects seems ok, I can move by scrolling (both vertically and horizontally so keyboard shortcuts are working it seems!), zoom in/out but I can't select an instance or draw a selection rectangle.

Mouse position looks weird, here I have opened the platformer template, zoomed out a bit and put the cursor on the top left corner of the camera initial position (near the coin icon). The position that should be displayed is 0;0
image

Not sure if the mouse pressed/released events aren't working or if it's due to a bad positionning of the mouse cursor.. Also the window mask is not at the right position, I think it's related.

**Comment by dos1** [comment]
Without this PR, GDevelop's IDE is useless on GNU/Linux as it crashes on opening a scene to edit. Merging it in fixes it. The inactivity since February worries me :(

**Comment by 4ian** [comment]
Unfortunately, this was creating other issues on macOS and this refactoring was not developed until completion :/

Since a couple of months, I'm switching to the development of version 5 of GDevelop, which can you download from the website (http://compilgames.net/#download). It's still in beta but largely capable of handling large games, and I recommend that you take a look. Should work flawlessly on Linux! 😄

**Comment by Translator5** [comment]
How is the progress guys? Any way to fix is separately for Mac & Linux?

**Pull request closed without merging**
