### PR TITLE
Fix the "pick all" and "pick a random" conditions when they are in functions

### PR DESCRIPTION
**Pull request by D8H**

### CODE REVIEW

**Comment by tristanbob** [comment]
What was the problem?  Was it that the condition/action would "pick all objects" **in the scene** instead of just objects passed to the function?

When I built the "Homing Projectile" extension, I wanted to use "Pick All objects" (including all objects in the scene) inside an extension but it didn't seem to work.

**Comment by D8H** [comment]
> What was the problem? Was it that the condition/action would "pick all objects" **in the scene** instead of just objects passed to the function?
> 
> When I built the "Homing Projectile" extension, I wanted to use "Pick All objects" (including all objects in the scene) inside an extension but it didn't seem to work. The point is, I think extension creators want this to allow picking all objects.

The action is working. The issue is only on the condition. Otherwise, yes, it asked the objects to the scene with the parameter name.

**Comment by tristanbob** [comment]
> The action is working. The issue is only on the condition. Otherwise, yes, it asked the objects to the scene with the parameter name.

Oh, so it would auto-complete from the "real" object names in the scene, instead of the object parameter name?

**Comment by D8H** [comment]
> Oh, so it would auto-complete from the "real" object names in the scene, instead of the object name used by the parameter?

Yes, it's the difference between `objectsContext` and `currentScene` parameter type.

**Comment by 4ian** [comment]
Two things:
- the fix seems the right one indeed. A function does NOT have access to the scene, unless specific things like creating an object.
- the pick all would not pick all objects from the scene, even with the fix? It should select all objects passed as parameter to the function.

Example: you passed two object instances to a function. Then in the function you use a condition to filter and do an action on one. Then in a sub event, you can use this action or condition to re-select all, i.e: the two instances, passed as parameter, so you can do a change on both of them in this sub event.

Is this how it works?

**Pull request merged**
