### PR TITLE
Issue 1354: Tween animations example project

### PR DESCRIPTION
**Pull request by ssangervasi**
Issue link: https://github.com/4ian/GDevelop/issues/1354

## What was changed
I've been having fun with tweens in my own game, so I thought I'd knock out this task to demo their usage. 
After adding the project, I ran the scripts for generating fixtures as described [here](https://github.com/4ian/GDevelop/issues/1354#issuecomment-571753219).

## Demo
tween_examples

### CODE REVIEW

**Comment by Bouh** [comment]
I would prefer the [TweenTest ](https://github.com/4ian/GDevelop/pull/922#issuecomment-467959740)made by the author of Tween behavior.
The game files are here.
The game need to be cleaned.
[TweenTest.zip](https://github.com/4ian/GDevelop/files/5365706/TweenTest.zip)

**Comment by 4ian** [comment]
Well we could maybe have both?

**Comment by ssangervasi** [comment]
I added a commit that includes the "tween test" project, and I did a little tidying including adding the "click sprite" instruction.

**Comment by 4ian** [comment]
Nice! 👍  Let me take a look and we can merge this :)

**Comment by 4ian** [comment]
Merged! Your example is very clean, thanks for doing it - appreciate it. Also appreciate the tidying of the test project, thanks! Both will be very useful to demonstrate the Tween capabilities to users :)

**Pull request merged**
