### PR TITLE
Refactor force multiplier

### PR DESCRIPTION
**Pull request by 4ian**

### CODE REVIEW

**Comment by Lizard-13** [comment]
This reminds me, when you're moving an object with forces the events are delayed one frame from the rendering. For example, if you move the player with forces but want to attach another object over the player (copying position), the attachment will have an offset because the force is applied after the events.
(I've noticed this problem in the Lil Bub face attachment too).

Would like to know if there is a problem if the forces are applied before the user events. Or if the action that applies the forces and movement also "flags" the applied forces so they are not applied again in the post-event process (this applied flag would be reset in the next frame of course).

**Comment by 4ian** [comment]
That's a very good comment, I was also thinking of the issue. As you said, I think that indeed applying the force before the user events could be the solution (much like platformer engine movement are done before events).

**Comment by 4ian** [comment]
I'll give a try to the first solution, let me know if you have any new findings here too :)

**Comment by Lizard-13** [comment]
AFAIK that should be enough :)

**Comment by Lizard-13** [comment]
Oh!, maybe the forces should be updated before the behavior pre-events. Forces don't rely on other information, they just move the object, so they should be applied first. Behaviors need to know the updated position, for example the platformer could handle moving platforms better if the object position is already updated... or the platformer behavior should check for moving platform post-event?

**Comment by 4ian** [comment]
> Behaviors need to know the updated position, for example the platformer could handle moving platforms better if the object position is already updated

Yes I think it's better this way.

I think it's fine to have the forces updated before all the behavior pre-events then. i.e: 

1. Apply movements according to forces on objects
2. then behavior can kick in and react according to object positions
3. then events are launched and we can update positions or create forces for the next frame
4. behaviors post events (should not, if possible, change positions to avoid the same issue of offsets).

For reference, I've checked:

Behaviors that change position in post events:
* AnchorRuntimeBehavior (no reason we could not move this to pre events)
* PhysicsRuntimeBehavior (I think we should swap pre and post events)

Behaviors that change position in pre events (so we're good):
* DraggableRuntimeBehavior
* PathfindingObstacleRuntimeBehavior
* PathfindingRuntimeBehavior
* PlatformerObjectRuntimeBehavior
* PlatformRuntimeBehavior

**Comment by 4ian** [comment]
Yes this order looks correct to me

**Comment by Lizard-13** [comment]
So the anchor is the only one to be modified so far?, relatively easy :D

**Comment by 4ian** [comment]
Yes ;) I can do the changes to AnchorRuntimeBehavior and change the force updates (let's not touch PhysicsRuntimeBehavior as you're already re-working it :)) but I'll be busy this week-end so expect a few days before doing the change. 
If you want, you can also go ahead and do a PR for it if you have time. We'll need to test it with lots of examples and games though to be sure nothing is badly broken - but should be good I don't see what could happen.

**Comment by Lizard-13** [comment]
Yeah, I can do that :+1:

**Comment by 4ian** [comment]
Sweet, let me know how it goes :) Should be a good improvement in most games to have this offset removed when positioning objects on other that are moving.

**Pull request merged**
