### PR TITLE
Add hardcoded miterLimit=3 to remove spikes from text outlines 

### PR DESCRIPTION
**Pull request by Wend1go**
A miterLimit of 3 isn't perfect but should work in most cases.

(Spent almost an hour to clear merge conflicts when pulling changes from 4ian/GDevelop into my fork. I hope I didn't break anything)

### CODE REVIEW

**Comment by Wend1go** [comment]
Looks like it pulled the broken formatted tween commit in as wall. I don't know how to get rid of it.
Already deleted the branch and pulled the changes from master while solving the merge conflict by accepting the changes from upstream.
Git is very confusing. :confused:

**Comment by 4ian** [comment]
No worries I'll do this. Git is a bit complicated at first, but here are a few guidelines/explanations:

- Always start from your master branch (git checkout master). When you start a new branch (using `git checkout -b branch-name`), you will start this branch **from the previous branch you were on** (read more about this - but most of the time you want to do this when you're on master, not when you're already on a branch).
- Get the latest commits from the "upstream", which is my repository. 
  - To add the "upstream" as a remote repository, if needed, you can do: `git remote add upsteam https://github.com/4ian/GDevelop.git`.
  - Then, get the latest commits (make sure you're on your master): `git pull upstream master` ("pull the latest commits from master branch of the upstream repository"). If there is a merge, it's fine.
- Then from now, always start branch from master:
  - `git checkout master` - to go/be sure you are on master
  - `git checkout -b my-new-feature`
  - Make some changes and commit: `git commit` (and `git add`/`git add -p` to add changes using the command line)
  - Push your changes `git push` to your branch
- When you want to do a new change, unrelated to the branch, go back to master before creating a new change: `git checkout master` and then `git checkout -b my-new-feature-2`
- If you want to at some point update your branches with latest changes in master:
  - Go on master, pull the latest changes (`git pull upstream master`)
  - Go on your branch and either:
    - Easy: merge master in the branch: `git merge master`
    - More risky but allowing to get a clean history (no merge commit): `git pull --rebase origin master` (or directly `git pull --rebase upstream master`). This pulls the commits from master, then take the commits you did on your branch, and put them back *on the top* of the commits of master. The only "risk" is that in case of conflicts, you'll have to solve them (`git add` to mark a file as resolved, `git rebase --continue` to finish solving conflicts and apply the next commit until it's finished, `git rebase --abort` if everything is broken and you want to cancel everything).

Last tip: if you're unsure about doing something on your branches, make a copy of your branch ;)
It's as simple as going on your branch: `git checkout my-feature-branch` and creating a new branch from it, that will be a copy: `git checkout -b my-save` and go back to your branch `git checkout my-feature-branch`. Now you can always checkout "my-save" :)

**Comment by 4ian** [comment]
I think this explanation can be useful so I made a doc about it ;)
https://github.com/4ian/GDevelop/blob/master/newIDE/docs/Using-git-to-make-and-propose-changes.md

@Bouh @blurymind As you are contributing often, this might prove useful to you too :) Feel free to suggest changes to the explanations if it's not clear.

**Comment by 4ian** [comment]
> (Spent almost an hour to clear merge conflicts when pulling changes from 4ian/GDevelop into my fork. I hope I didn't break anything)

This most probably mean that you made some of your changes on your master branch. Avoid doing this and always work on branches. When your changes are merged by myself, like this one, go back to master and "pull my latest changes" - dont' import/merge/whatever your changes. They will be delivered as part of the new commits from "my" master branch :)

I usually squash (=merge all your commits into a single one), so conflicts could happen.

**Comment by piyushpalawat99** [comment]
Hey,

Just a few comments:

> Then, get the latest commits (make sure you're on your master): git pull upstream master ("pull the latest commits from master branch of the upstream repository"). If there is a merge, it's fine.

As mentioned, it will create a new merge commit, wouldn't it be better if we use git pull upstream master --rebase?

> I usually squash (=merge all your commits into a single one), so conflicts could happen.

In this case, I'd assume that the contributor wants to sync the local repo with the remote repo. So wouldn't it be more convenient to rather use git reset --hard followed by the SHA from where we began to make changes and then pull upstream master? This will ensure that both - local and remote - branches are on the same page.

**Comment by 4ian** [comment]
> So wouldn't it be more convenient to rather use git reset --hard followed by the SHA from where we began to make changes and then pull upstream master

Happy to add alternatives, it's just that I want to keep things as simple as possible even if it's not the cleanest possible way. 

> git pull upstream master --rebase

We can also add this as a side note, as a better alternative?

**Comment by piyushpalawat99** [comment]
> Happy to add alternatives, it's just that I want to keep things as simple as possible even if it's not the cleanest possible way.

Yes, that's right! It should be simple. For more information, can we add links to the git documentation because I believe that the objective of the file is to explain the simplest way and not each and every way of any given command. You can check out the git commands' documentation here: https://git-scm.com/docs

**Comment by Wend1go** [comment]
Thanks for the detailed explanations @4ian , @piyushpalawat99 .
I wonder if the long list of `Merge pull request #1 from 4ian/master` is related to me having the upstream changes pulled via github instead of adding an upstream repository via console.
I haven't seen these on any PR from other contributors.

**Comment by 4ian** [comment]
> I wonder if the long list of Merge pull request #1 from 4ian/master is related to me having the upstream changes pulled via github instead of adding an upstream repository via console.

They are "noise" but are not a real problem because they are not showing up in the list of changed files - so it's fine because in any case when I merge the PR, all your commits are combined in a single one.

These commits are the real culprit here:
image

Because they are part of your branch, the PR was including these commits with these changes inside. This is why in my tips I'm saying to always start from master, so that your branch is not including commits from previous work on other branches.

>  I believe that the objective of the file is to explain the simplest way and not each and every way of any given command

Yup exactly, I just want this to be a survival guide so that contributors like Wend1go are not fighting git more than a few minutes :D I'm not sure about git docs links - the documentation is a good reference but will be useless for a git beginner and will probably lead people to say "whoa if I have to read this doc to contribute to GDevelop, I quit!".
A few links to better git tutorials are fine, but really all we should need to know to make PRs should be self explaining in the new doc.

> I haven't seen these on any PR from other contributors.

True, maybe we can ask @blurymind or @Bouh how they are managing their branches/git? Pretty sure that the doc I wrote is still too complicated, there must be ways to simplify it :)

**Comment by Bouh** [comment]
I use GitKraken, i prefer see all commits and branches. Console have too many commands
I use only pull and merge. 
When i code for GD i pull code from master and open an new branch from this.
I checkout on new branch and i start to code. I open a PR with this branch.
If someone add code i need in my dev branch i prefer create a new branch with my code and code from other people. 
When i'am on master i use only pull for get last commits from this repository.
Never Merge because if i merge, commits like "Merge pull request #1 from 4ian/master"  appear and the mess come in your new branch and it's visible in PR.

**Pull request merged**
