### PR TITLE
Subtle words in README.md

### PR DESCRIPTION
**Pull request by Oneoeigh**
Slight changes to words to make it easier to understand

### CODE REVIEW

**Comment by 4ian** [comment]
Looks good, thanks for making the Pull Request for this :)

**Comment by zatsme** [comment]
Better grammar imo....

GDevelop is a full featured, open source game development software,
allowing you to create HTML5 and native games without any knowledge *of* a
specific programming language. All the game logic is built up via an
intuitive and powerful event based system. Also, maybe open source game
development engine sounds better?

**Comment by 4ian** [comment]
So that would be:

GDevelop is a full featured, open-source game development engine,
allowing you to create HTML5 and native games without any knowledge of a
specific programming language. All the game logic is built up via an
intuitive and powerful event based system.

> Also, maybe open source game development engine sounds better?

Maybe, might sound better but can't really tell. Will use what you think it's the better sounding :)

**Comment by zatsme** [comment]
Yes ...... 

'GDevelop is a full featured, open-source game development engine,
allowing you to create HTML5 and native games without any knowledge of a
specific programming language. All the game logic is built up via an
intuitive and powerful event based system.' 

I think you need the word 'development' in there to differentiate from a 'game engine' which to me is usually a library without ide...

🙂

**Comment by Lizard-13** [comment]
> differentiate from a 'game engine' which to me is usually a library without ide
That's actually a framework :)

**Comment by 4ian** [comment]
Well a framework can also be a "big library" without the associated editor/IDE ^^ 

But whatever we choose, we must emphasize that the editor is indeed a very important part compared to other engines.

**Comment by zatsme** [comment]
How about **Game Development System**?  This implies you have everything you need in the system to make games.  Systems can also be expanded/extended with add-ons or plugins like Piskel and the Sound Generator, so it seems to fit well,  😄

**Comment by 4ian** [comment]
Well I don't know if someone tell me that "look this is a game development system" I'm like "what's the bullsh*t, is that a game engine or what?" ^^

**Pull request merged**
