### PR TITLE
Commit pixi spine bundle

### PR DESCRIPTION
**Pull request by f0nar**
Hi!
I didnt create issue before this PR as it is pretty simple change and I think it is better to discuss and solve it here

I see that you keep in repo all files that are required to make runtime work. e.g. threejs, pixi.js, TileMapHelper. In this case tools like https://github.com/arthuro555/gdexporter are possible (I am using it)
Unfortunately now spine is not supported with it and that is why I would like to merge pixi spine bundle to repo code

### CODE REVIEW

**Comment by 4ian** [comment]
I think this is more in line with other extensions indeed. Do you need to remove also some script that used to run at npm install>

**Comment by f0nar** [comment]
It is up to you.
I did not remove it as script might be useful in future if you want to bump spine version. Now it does not affect us at all.

**Comment by f0nar** [comment]
Hi @4ian 
I update PR

**Comment by 4ian** [comment]
Looks better! I removed listing of the old file/replaced by the new one were useful. 
I also did a fix to ensure pixi-spine.js is excluded by TypeScript as it's a pre-built file (https://github.com/4ian/GDevelop/commit/cacd482af9143475cd1b2b81e7365e63b5799896).

Thank you :)

**Pull request merged**
