### PR TITLE
fix issue #672 - undesired instruction editor parameter autocomplete

### PR DESCRIPTION
**Pull request by blurymind**
...pop up on mount.
https://github.com/4ian/GDevelop/issues/672
46233624-487f0100-c36b-11e8-9ca3-3bdb03a67051

### CODE REVIEW

**Comment by 4ian** [comment]
@blurymind If you can merge master/solve conflicts, I'll merge this after :)

**Comment by blurymind** [comment]
It looks like I have deleted the original fork where I fixed this again. Would you like me to close it and do another pull or add it to the one I currently have - with piskel? 
Sorry about this. I really need to keep my fork and do these changes in separate branches - but when my fork gets too outdated I just delete it and fork again instead of merging changes from yours

**Comment by 4ian** [comment]
No worries, do as it is easier. You can as well do it again on another branch/another PR.

**Comment by blurymind** [comment]
I will close this and do it in another pull

**Pull request closed without merging**
