### PR TITLE
Add support for translations in GDevelop 5 🌎

### PR DESCRIPTION
**Pull request by 4ian**
* [x] Update to create-react-app v2.
* [x] Install js-lingui and remove react-i18next
* [x] Fix Flow errors with js-lingui see https://github.com/lingui/js-lingui/pull/448
* [x] Extract translations into PO catalogs for
  * [x] editor
  * [x] JS extensions 
  * [x] GDCore/GDCpp/GDJS/C++ extensions 
* [x] Script to combine all translations (PO files for the editor + the rest) and compile them.
* [x] Edit README to explain what script to launch to extract/compile translations.
* [x] Remove hardcoded "fr" language used for test.
* [x] Add language dropdown in preferences. 
  * [x] Potentially show the translation percentage? (or add "beta" or translations that have a small completion).
  * [ ] Ensure that when language is chosen, JS extensions are reloaded and builtin extensions too. Or relaunch GD?
* [x] Add a menu item to help discover the languages.
  * [ ] Potentially display the language on the start page to help people discover that the language can be changed.
  * In the future, the language can be asked at the first launch.

Things that will need to have translations markers added - this can be done progressively after this PR is merged:
* [x] Extensions are ok, already have `t("...")` (that I updated to `_("...")`)
* [x] GDCore/GDCpp/GDJS/C++ extensions (already using `_("...")`)
* [ ] All components in the new editor will need to use `<Trans>` (or `withI18n` + `this.props.i18n._(...)` like done in MainFrame.js)
  * [ ] Fix the `const t = str => str; //TODO`
* [ ] label props 
* [ ] emptyExplanationMessage
* [ ] emptyExplanationMessage
* [ ] emptyExplanationSecondMessage
* Fix the `unsafe-eval`.

### CODE REVIEW

**Comment by Wend1go** [comment]
Is it already possible to add translations for the new features in GD5 that were not available in GD4?

**Comment by 4ian** [comment]
Not yet, extracting translations and uploading them to Crowdin is part of what is achieved in this Pull Request.

Strings to translate in the editor will have to be put between a `<Trans>` component so that they are extracted.
Strings to translate in the extensions will be extracted when put between a the function call `t("blabla")` (which will be renamed with an underscore `_("blabla")` so that the translations can be extracted with the same tools as the C++ codebase).

Extensions are ok because from the start I introduced the "t" function. The editor will need more work because I need to go through every string and mark them as translatable.

**Comment by 4ian** [comment]
Made a script that added translation markers to most strings of the editor :) Still have quite a bunch to go manually through, made another script to list them.

Will merge this when Flow is fixed in js-lingui. As there are a lot of changes, better merge this as soon as possible.

**Comment by 4ian** [comment]
Might actually host a built version of js-lingui so that we can go ahead and merge this asap, and start having translations, while I finish to add missing translation markers.

**Comment by 4ian** [comment]
This Pull Request is becoming really super large and is going to need more and more work if we merge other Pull Requests. I'll merge it now, and will work on improving the remaining points in the description (missing translations markers, relaunch the app or reload translations when a new language is chosen).

@blurymind @Bouh @Wend1go @Lizard-13 or anyone that might have some Pull Request or using GD development version.
* When this is merged in master, I recommend **merging master** in your development branches. 
* You'll potentially have **conflicts**, because my changes were quite large spread and consisted in adding `<Trans>blabla</Trans>` components, and/or `i18n._(t`blabla`)` (for translations of raw strings). If you should be able to apply the proper changes. In case of doubt, ask me.
* In extensions, I've renamed the `t` function (used to translate strings: `t("blabla")`), to `_` (`_("blabla")`). If you're making a new extension, you can keep `t`, but at some point I'll have to rename all call to `t` to `_`. Calling the function `t` or `_` does not change anything code wise, it's for the translator extractor to work that extension (JsExtension.js files) must use `_`.

* Lastly, once you have merged master in your branches and solved conflicts, **you must relaunch `npm install` or `yarn`** (and then `npm start` or `yarn start`). Failing to do so will make GDevelop unable to launch itself. In case of doubt, **erase the folder called node_modules** in `newIDE/app` and then launch **you must relaunch `npm install` or `yarn`**.

Don't forget **`npm install` or `yarn`**! :)

**Pull request merged**
