### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by tberthel**
I had to search for the build info.

### CODE REVIEW

**Comment by 4ian** [comment]
Thanks for your PR. I think the sentences don't really fit in the current README table, which is just a getting started place. It should rather be placed in this README: https://github.com/4ian/GDevelop/blob/master/newIDE/README.md :)

**Comment by tberthel** [comment]
The root readme should have something on how to build or where to find the build instructions? right?

**Comment by 4ian** [comment]
Yep, the link is here: 
image

**Comment by tberthel** [comment]
So can it become "Contribute to the editor or build"?

**Comment by tberthel** [comment]
?

**Comment by 4ian** [comment]
Sorry, I think `Contribute to the editor` is fairly clear? "Build" means different things according to the context, so I think it's better to keep this using a simple word, "editor" that is clear and representing the whole app :)

**Comment by tberthel** [comment]
It took me a long while find the instructions to build (find and grep).  So whatever you have is not build instruction friendly.

**Comment by tberthel** [comment]
Contributing to me just means one of two things: 

- Opening a pull request with changes
- Pushing to the repo directly

Building and Running are also not the same.  If your project had a make file or pom.xml in the root of the project it would be less of a problem, but you have neither.

**Pull request closed without merging**
