### PR TITLE
Add CTRL+D shortcut to duplicate #6629

### PR DESCRIPTION
**Pull request by osmaneTKT**
I corrected accelerator and grouped onDelete with onDuplicate. I also added a comment to the one above the instantiation of keyboardShortcutsRef.  #6629

### CODE REVIEW

**Comment by osmaneTKT** [comment]
Hi @AlexandreSi , I made the modifications you asked for.

**Comment by osmaneTKT** [comment]
https://github.com/4ian/GDevelop/pull/6629

**Comment by osmaneTKT** [comment]
@AlexandreSi, it's done. I wanted to ask if you think it will be merged because it will allow me to complete my course, or if there are still other things to address.

**Comment by AlexandreSi** [comment]
I just realized that your 2 branches `master` and `contribution` should be merged.
You can do a cherry pick of the commit on `master` to put it on `contribution`.
Could you also rename duplicateObject ? it does not duplicate an object but an `objectFolderOrObjectWithContext`

**Comment by osmaneTKT** [comment]
@AlexandreSi, I think everything is good now.

**Comment by osmaneTKT** [comment]
?

**Comment by osmaneTKT** [comment]
@4ian

**Comment by AlexandreSi** [comment]
Just my thoughts about this:
- Using the tree view shortcut makes sure the user is actually focusing the objects panel and not trying to duplicate something else
  - In contrary to the global shortcut.
  - But it cannot be customized as is.
- The same could be added for object groups for instance

So for me this is the way to go.

But to make this PR clean, I think the shortcut to rename an object should be transferred to the treeview keyboard shortcut instead of the global shortcut, ignoring the custom shortcuts users might have set.

So I'm not sure about what we should do. @Bouh wdyt?

**Comment by AlexandreSi** [comment]
Closed by #6273

**Pull request closed without merging**
