### PR TITLE
Events functions

### PR DESCRIPTION
**Pull request by 4ian**
Highly experimental and still need lots of work.
Opening this PR to keep track of work to be done:

- [x] Merge #663
- [x] Do code generation/file writing/extension loading
- [x] Reload extensions on game opening
- [x] Reload extensions on modifications
- [x] Unload extensions on game closing?
- [x] Automatic "refactoring" when a events function/extension name change (instructions)
- [x] Automatic "refactoring" when a events function/extension name change (expressions)
- [x] Handle conditions/actions.
- [x] Add dialog to edit the "extension" properties
- [x] Expression, Str expression to compare/get the value of a parameter (string or number)
- [x] Actions to set the return value (number, string, true or false)
- [x] Maybe hide the feature behing a preference option while it's not battle-tested. 
- [x] Move EventsFunctionsExtensions to Project folder
- [x] Decide if ParameterMetadata is a good fit or should have a different class for it.
- [x] Decide if EventsFunctionsExtension is a good name or not. If not replace all `EventsFunctionsExtension` and `eventsFunctionsExtension`.
- [x] Add help buttons

Later:
- [x] Wiki page about this
- [ ] Examples about this
- [ ] And more things to come 😄

### CODE REVIEW

**Comment by blurymind** [comment]
I am very excited about this one. :D I can see that it took quite a lot of refactoring, but it is definitely worth it!!

**Comment by 4ian** [comment]
FYI, I think I should have something finalised hopefully by this week. The goal is, once it's ready, to release a new version with this + all the improvements made on master branch.
I won't be available next week-end unless for quick code reviews, so next version might be next week.

I think I may hide this feature under an option to activate in the preferences to avoid confusing people while the wiki is not updated with some help pages.

The implementation is way way more powerful compared to functions in GD4 (you'll see when using it - yeah I'm teasing 😄). I also think that this feature might unlock a lot of possibilities in terms of reusability and sharing - we'll see how it goes but I have a few ideas about it.

**Comment by zatsme** [comment]
Can't wait to try this out 😁

**Comment by 4ian** [comment]
Merging this now in order to have it on master and prepare for next release.
Still writing the new wiki page: http://wiki.compilgames.net/doku.php/gdevelop5/events/functions and will try to provide a few examples. Also a few things to sort out (re-ordering/deletion of functions), tracked in https://trello.com/c/SC01CLLc/16-experimental-support-for-reusable-function-events :)

**Comment by blurymind** [comment]
puts on the party hat * :D

**Comment by 4ian** [comment]
@blurymind @zatsme @Lizard-13 If you have some time feel free to read the wiki page I've written: http://wiki.compilgames.net/doku.php/gdevelop5/events/functions

Let me know if you have questions and I'll improve the page.
I need to create a few examples, to show the power of these events functions 🤩

**Comment by blurymind** [comment]
@4ian this looks really cool. I can't wait to play with it :D 👍  
Very elegant implementation

**Comment by Lizard-13** [comment]
Impressive!, the way to define them is the same than C++, still kinda shocked! :open_mouth:

**Comment by zatsme** [comment]
Looks great, can't wait to have fun with this 😁

I'm not sure if they should just be called functions, rather than 'events functions', what do you think?

**Comment by 4ian** [comment]
I guess internally we'll keep Events Functions, but for end users we can simply call them functions yeah I think. Might cause less confusion.

> Impressive!, the way to define them is the same than C++, still kinda shocked! 😮

Yes that the big selling point of all of this. Functions created like this are exactly handled the same ways as in extensions.
In fact, when you're creating functions, you're creating extensions on the fly ;) 🚀🚀🚀

**Comment by 4ian** [comment]
If you're curious, I've written a wiki page with an example of external events being replaced by a reusable function: http://wiki.compilgames.net/doku.php/gdevelop5/events/functions/replace-external-events

I still have a few things to fix and it should be good to go in the next version :)

**Comment by rikazukun** [comment]
Cool, thanks. Btw if I do a pull request, do I upload everything or only the ones I have changed? or Git automatically checks the changed files?
(It's been a long time since I did one sorry)

**Comment by 4ian** [comment]
So basically:

* You create your own "fork" of GDevelop using the Fork button on the top right
* You git clone your fork on your machine with Git (or a client like GitHub Desktop https://desktop.github.com/ or anything else)
* You make changes, create a commit with the changes (`git status` to see what changed, `git add filename` to add a file that was changed to the commit, `git commit -m "Description of changes"` to create the commit, `git push` to send it to your fork

When you have your changes on your fork, you can now open a pull request (see https://help.github.com/articles/creating-a-pull-request-from-a-fork/)

**Comment by 4ian** [comment]
FYI, I've started to add mentions to functions in the wiki and put links to the help page.
Next version will have functions visible by default.

In future versions, I'll work on more tools to share functions.

**Comment by Bouh** [comment]
The feature does not support true or false parameters.
And the expression GetArgumentAsNumber() is the only one that worked, I wanted to get a string with GetArgumentAsString(), but it didn't work.

**Pull request merged**
