### PR TITLE
Screenshot extension:  Brighten up the icon colour

### PR DESCRIPTION
**Pull request by Wend1go**
It melted with the background in the dark theme so I made it a bit lighter.

### CODE REVIEW

**Comment by 4ian** [comment]
Seems that you worked from your screenshot branch. Once I merged it, you have to start from master to do your changes, because all your commits were merged into one on master (to keep a clean git history).

**Comment by Wend1go** [comment]
Should I close this and create a new one?

**Comment by 4ian** [comment]
Yes, whatever is the easiest for you :)

**Comment by Wend1go** [comment]
Made a new PR: #834

**Pull request closed without merging**
