### PR TITLE
Run Babel on tweenruntimebehavior.js for backwards compatibility

### LINKED ISSUE #1148: Tween animation extension and android 4/5 compatibility for exported games
Hello,

Maybe i'm wrong on this report (or for the Swamp "case"), but i'm facing a bug for some users with Swamp since we released the demo on playstore. 
For some users, the loading of the game at app launch stop at 96%, and for now i observed that it only occurres on android 5.1 and inferior (tested on my own and i've seen the same issue on android 4.4.4).

I did a lot of test on my android 4 device to try to determine the reason. I tested several projects, examples and features to try to determine if i can reproduce the issue with other games, and i did it (or at least i experienced an issue) : If i export the Tween animation example (pairs) for android, the app load to 100%, then remains stuck at 100%. The app just can't be launched.

So idk what to do actually, maybe i could just exclude all devices on lollipop and previous android version on playstore console, but it seems that the Tween extension only works for android 6.0 (at least) and superior. 

any chance for it to be fixed/enhanced in GD ? Or maybe on the build services (changing android compatibility in manifest if this extension is used in project ?).

### PR DESCRIPTION
**Pull request by Wend1go**
Hope this fixes #1148

### CODE REVIEW

**Comment by Wend1go** [comment]
@4ian If you don't like the style, I could revert everything except for the 18 usages of arrow functions.

**Comment by Bouh** [comment]
4ian told me always, run prettier ^^

**Comment by 4ian** [comment]
Let's run Prettier on this, because it's a lot of noise for not that many changes :) 
The useful changes that we can see are the conversion from `() =>` to `function` and also some `const` translated to `var`.

**Comment by Wend1go** [comment]
Hm? Looks like prettifier brought the arrow functions back. :(
Is there a command to prevent it from touching these?

**Comment by 4ian** [comment]
Are you sure about these? Prettier only operates on the syntax of the code. It's never removing/changing code. I think you may have run it on an old version.

Also would be cool if you can do this in a separate branch, because Skeleton related files are being included in the PR?

**Comment by Wend1go** [comment]
Yes, I accidentally commited the wrong version of the file.
Will commit the correct prettifierd version after finding out how to push a headless commited version.

**Comment by Wend1go** [comment]
Managed to blow it up, next try here: #1151

**Pull request closed without merging**
