### PR TITLE
add objecttools argument types

### PR DESCRIPTION
**Pull request by andineck**
As discussed in #1202 , documenting the parameters Types could be helpful.

### CODE REVIEW

**Comment by 4ian** [comment]
That was fast! I've added a commit to use `*` instead of `any` (I think in JSDoc, you have to use *). And added the typing for the predicate (could be done for other predicates too).

**Comment by 4ian** [comment]
Note that I've seen you've made your PR from your master branch. Avoid this and prefer creating a branch, because when I merge your PR, I "squash" the commits into a single one, so that your master will diverge from mine. Better work on a branch, then go back to master and pull my changes :)

**Comment by andineck** [comment]
cool, thank you for merging, you are right `*` is correct, was confused with typescript. 
will do a branch next time :-)

**Comment by 4ian** [comment]
Yeah JSDoc is a bit different than typescript - but the goal is to keep using it and at some point add Typescript to do typechecking (as Typescript understand JSDoc annotation). So these kind of improvements to the types are very welcome!! :D

**Pull request merged**
