### PR TITLE
Start page, guide, tuts, docs

### PR DESCRIPTION
**Pull request by Bouh**
image

I've reused my ideas from this [previous PR](https://github.com/4ian/GDevelop/pull/1286) i've just keeped the start page idea.
Users will no longer have an excuse to say they didn't know there were tutorials and documentation :p 

(The guideline step-by-step is still in my mind)

I'am ready to merge! Just waiting for CI and others validation!

### CODE REVIEW

**Comment by 4ian** [comment]
That makes 6 button on the start page, that's a lot no? And 3 "primary" buttons, I'm not convinced it's the best UI we could find.

The first approach should be I think only a few buttons.

> Users will no longer have an excuse to say they didn't know there were tutorials and documentation :p

Believe me, there will be still lots of them asking about this ;)

Could we instead replace the "Search the documentation" button by a dialog showing this?

Last thing but important: how does it look like on mobile? Remember we should be be compatible with all form factors.

**Comment by Bouh** [comment]
Ok i've made some change for adapt mobile and move buttons.
[Commit change](https://github.com/Bouh/GDevelop/commit/e0a82d6593189cf2cdec0742e30c5811fd754859)

New look on large screen.
image

For non large screen aka tablet mobile we keep the default start page

image

**Comment by Bouh** [comment]
Six buttons or twelve is not too much of a problem.
The important thing is to have the most useful thing that jumps out at you.
What do I want to do?
Learn, left section.
Create, right section.

Next are the buttons with their primary and secondary roles.
How do I want to learn?
Read the doc, see tutorials.
How do I create?
A new project, I have a project and I open it.

**Comment by 4ian** [comment]
> For non large screen aka tablet mobile we keep the default start page

We could have "Search the documentation" replaced by a "Tutorials and getting started guide" and when you click on it, we open a dialog with this:
image

(more or less, but you see the idea)

> Six buttons or twelve is not too much of a problem.

I think it's very important on the contrary :) This is the very first screen and it must gives an overview of GDevelop being "simple but powerful". Here we have 6 large buttons, including 2 that are actually redundant with "GDevelop Games" and "Help and Tutorials" at the bottom.
It's not ideal and could give the idea that the software is bloated, or so complicated to use that we actually put twice the tutorial buttons on the same page.

> Learn, left section.
> Create, right section.

I think it's definitely interesting! But I feel there is a problem of balance on the screen:
- the graphics are good looking, but they are at the same position as the "GDevelop logo". So it's almost like putting more emphasis on this. 
  - If I read the screen as a new user in the old version, I would read from top to bottom. "Ok this is GDevelop, it's an open source game dev software, and I can create a new project or open one.". That's ok. Even if it has the problem: where do I learn?.
  - If I read the screen as a new user in the proposed version, I read from left to right and top to bottom: "Ok I have some graphics that are a generic about learning (then a text I'll probably skip reading because I have no time for that ;)), then a button Getting Started (good!), then Tutorials (good!) then documentation (ok, but I don't care about reading a doc for now) and then I have "GDevelop" ah but well I already started reading the page, why do they introduce GDevelop now?".
- The learn icons are good looking, but not game tailored. I would rather have the first image shown to user to be related to games... otherwise it would look like a generic boring SaaS product.  
  
In other words, we give the same visual importance to the introduction of the learn section than to the GDevelop logo, which I think make it look out of place. 
We also put the task of "reading/watching tutorials" the same importance as creating a new game. But our goal is to delight first time users and they don't care about tutorials during their first visit. They want to create a game and feel the magic! :D So they will want to click on a big button "Create a new project" to be sure they are about to make a game. Then when they have appreciated how simple it is to start a game, then will start to ask about "ok I actually need to learn a few things to use this GDevelop thing", and at this moment the "Learn" section will be very important.

I would rather see:

```
       GDevelop
       small text description of GD

Create                 Learn
[ New project ]   [ Tutorials ]
[ Open ]               [ Something else]


Icons on bottom:
[ Showcase ] [ Community]
[ Social icons ]
```

I'm not sure it's the right approach, but it's a bit more streamlined. And creates a flow "Here is GDevelop and here is first what you all want: "the button to create a game". THEN there are buttons to learn (because it's the second most important thing) and finally when you're ready come to the community we have tons of icons for it."

Or even more streamlined

```
 GDevelop
small text description of GD

[ New project ]  
[ Open ]           
[ Tutorials ] (---> open the dialog I with what you added)

Icons on bottom:
[ Showcase ] [ Community]
[ Social icons ]
```

Ooooor... we completely redesign the first page with something like Wishforge Games designed:
image

Which is akin to your idea of two columns "Learn", "Create", but with some differences:
- Showing games first. The first graphics we see are games
- Less buttons but it assumes that we have guideline step by step implemented for 3 games.

> (The guideline step-by-step is still in my mind)

That's indeed a new way to guide users that would be very interesting! (and also technically challenging to do it perfectly in a polished way).

**Comment by Bouh** [comment]
I'm not keen on redoing the whole startup interface, a new UI must be great i agree without, but there is questions to solve before. 
This new UI doesn't seem to me 100% accurate, tabs system isn't a good pratice for put things in evidence.
Tabs are too stuck in a corners, likes the "Help and Tutorials" on the current version.

I don't went spend too much time on another big change that will take months or weeks.

"Tutorials and getting started guide" is good!
Because the "Search the documentation" button is not what people want, it's tutorials they want, only nerdy guys learn with the documentation ;)

In this case we keep a screen with it:
- Create a new project
- Open a project
- Tutorials and getting started guide

The problem with the buttons "GDevelop games", "Community forum" and "Help and tutorials" is that they are just at the bottom and not any eye-catching style and are not in the eye line (in the center of the screen).

Give me 1 hours for prupose you a new version with less change, with one panel on start page and rethink the flow in "Tutorials and getting started guide" panel.

**Comment by 4ian** [comment]
> The problem with the buttons "GDevelop games", "Community forum" and "Help and tutorials" is that they are just at the bottom and not any eye-catching style and are not in the eye line (in the center of the screen).

I agree. These must be secondary, "less important" buttons here.

> In this case we keep a screen with it:
> * Create a new project
> * Open a project
> * Tutorials and getting started guide

Yes this sounds good! This way we remove the almost useless "Search the documentation" (I totally agree that nobody really want this, tutorials are better) and replace it with a "Getting Started and Tutorials" button.

> Give me 1 hours for prupose you a new version with less change, with one panel on start page and rethink the flow in "Tutorials and getting started guide" panel.

Sounds good! Thanks 👍

**Comment by Bouh** [comment]
image

In the perspective of keeping the reading from the top to the bottom, I put the buttons in the logical order for a new user.
1 - Learning, "Getting Started and Tutorials".
2 - Create, "Create A New Project".
3 - Open, "Open A Project".

I've keeped one panel, i've move in first position "Getting Started and Tutorials" button, As long as the tabs are still there it open the "Tutorial" tabs.
The "Search the documentation" has moved at the buttom of the screen and rename "Help and Documentation" it open the Help search panel.

**Comment by 4ian** [comment]
Looks good to me 👍

**Comment by Bouh** [comment]
>Looks good to me 👍

Ok to with it :)
It's really a small redesign that goes in the right direction while waiting for a nice startup panel.

We could open a discussion for it on Github Discussion!

**Comment by 4ian** [comment]
Yes, it's maybe a small change but could already have some good impact! :)

**Comment by 4ian** [comment]
And yes we can discuss about the "First Time User Experience" more in depth in a discussion :)

**Comment by nilaymaj** [comment]
> Ooooor... we completely redesign the first page with something like Wishforge Games designed

Wandered over here, and this mockup looks *absolutely* amazing. Although implementing this with MUI will take away a lot of the breathtaking-ness (I'm sorry, I'm not a huge fan of the default MUI look :sweat_smile:), it definitely has a better onboarding experience - super-impactful for the people trying out GDevelop on the online editor.

I'll be happy to take this up - next "rework", maybe?

Also, out of curiosity, did Wishforge Games create more of these mockups? These ideas are fantastic!

**Comment by Bouh** [comment]
I have a lot of mockups!
With some other layouts for Start page, and more.
We should open a discussion for talk about the ideas.

**Pull request merged**
