### PR TITLE
Skinning (basicly) the "Link" event for the DefaultTheme and the Darktheme

### PR DESCRIPTION
**Pull request by KinkGD**
This is very basic skinning for the 2 themes and the "link" events. 

I added a color for the selectable class on the DefaultTheme (to make it look like similar to the others modifiable elements of events).
image

I added a background color, text color, and a color for the selectable class of the DarkTheme.
image

First time i followed the readme to contribute to the newIDE, i have to admit : 
- installing node.js, cloning the repo was super easy
- identify the css files, classes, and modify it too
- but i've spent 2 hours to understand GitHub/Fork/Pull Requests ! Damn, i'm coming from subversion 🤣

### CODE REVIEW

**Comment by 4ian** [comment]
Nice!

> installing node.js, cloning the repo was super easy
> identify the css files, classes, and modify it too

Sweet :) You were actually lucky because that's one of the rare part that is using CSS files to do styling - other components are also using CSS but embedded inside JS. Not too difficult to modify, you just have to be aware of this and search a bit in the .js files ;)

> but i've spent 2 hours to understand GitHub/Fork/Pull Requests ! Damn, i'm coming from subversion 🤣

Yeah, it's still something that is hard to grasp at the beginning. Git is very powerful though once you know a few commands.

As for the changes, I like the theming! The CSS class you've modified is still used in a lot of different events: 
image

Could you post a few screenshots of both themes with more events, including for each/while? Want to double check everything is displaying properly :)

**Comment by 4ian** [comment]
> Where can i add some custom CSS class to these specifics elements ? I suppose it's the best to do ?

Yes, add a CSS class for links.
* Declare it in `newIDE/app/src/EventsSheet/EventsTree/ClassNames.js` (like disabledText or largeSelectableArea). Name it "linkContainer" (js variable) (and "link-container" for the value, which will be the CSS class name).

* Then, mark the LinkEvent as using this class. In LinkEvent.js, inside:

```
className={classNames({
          [largeSelectableArea]: true,
          [largeSelectedArea]: this.props.selected,
        })}
```
add a line for linkContainer. As it must *always* be applied, do like largeSelectableArea (i.e: `[linkContainer]: true`). Import linkContainer at the top of the file, like largeSelectableArea.

Finally, add in both theme CSS files a ".gd-events-sheet-dark-theme .link-container". And style this class :)

**Comment by KinkGD** [comment]
Ok, i'll try to do this.

Question about Github (i'm "worried" about already knowing the answer)... As a "true noob", for these two files i've modified my master branch on my fork. If i delete this fork and start a new one, does the PR (and this discussion) will disappear ? (my second PR #915 is a branch form this fork, so it would disappear too ?).

**Comment by 4ian** [comment]
I would avoid deleting the fork on GitHub, actually I've never done it. In the future, always create PR from a branch, so that your master branch is always "clean". You could remove the commits in your branch. Otherwise, try to remove the fork and create another, this time making modifications on branches. 
Not sure what will happen with PRs. To be extra sure, make a copy of the files you've modified, so that you can copy-paste them and avoid losing all changes :)

**Comment by KinkGD** [comment]
Ok, and i'll copy your explanations too, i don't want loose comments !

Le ven. 1 févr. 2019 01:15, Florian Rival <notifications@github.com> a
écrit :

**Comment by KinkGD** [comment]
Ok so i've deleted my old fork, it seems these dicussions is still here and files too, but i think this PR and the #915 can be archived/closed/canceled ? That would be "sad" to lost your explanaton about how to add a CSS class.

BTW, i've made a new fork, and now i work with branch as you recommend : 
- One branch for the work around the color picker, but i don't think i'll add anything more than what i did in #915 (i could just create a new "clean" pull request form this branch).
- One branche for the actual discussion : i successfully added a new CSS class and skinned it in the themes (and i'll add to this one if i'm succesful what you've written in #913) So this will be ready for a new Pull Resquest.

**Comment by 4ian** [comment]
Nice! Feel free to open new pull requests from your new branches. 
You can then close these original pull requests, and put links between them as comment or in the description (a link to the new one in the old one, a link to the old in the new one), so that someone reading this will have the full context :)

I'll re-read and merge them separately then

**Comment by KinkGD** [comment]
i close this "uncomplete" PR, the new PR is #916

**Pull request closed without merging**
