### PR TITLE
upgrade bondage to the yarn 2 spec - closes 6451

### PR DESCRIPTION
**Pull request by blurymind**
The new bondagejs appears to be imported correctly (see logging)

When trying to run my old test demo game however I get this error

image
image

@4ian @Silver-Streak any idea why this is happening? Is it something to do with how the umd module is configured?
This was one of the major things that the contributor did to modernize it. He migrated it from rollup/gulp to webpack
https://github.com/hylyh/bondage.js/blob/master/gulpfile.js
https://github.com/hylyh/bondage.js/blob/2.0/webpack.config.js

trying to address https://github.com/4ian/GDevelop/issues/6451

- [ ] fix new library import breaks the extension/runtime
- [ ] do extensive testing with existing projects

closes [6451](https://github.com/4ian/GDevelop/issues/6451) if I can ever figure out why the import no longer works in gdevelop

### CODE REVIEW

**Comment by Silver-Streak** [comment]
I'm not much help here, sadly. Without a stacktrace I can't even help research.

Bad end of line in the console makes it seem like something *somewhere* is not escaped properly, but I'm not sure.

I'd be looking at mayeb @D8H for input if not @4ian

**Comment by blurymind** [comment]
guess if you run Gdevelop with the dialogue tree project - with this branch you will see the stack and it is not helpful at all.

It appears to get an exception at the second screenshot i made

**Comment by blurymind** [comment]
I just noticed the developer who upgraded this has a branch that is slightly ahead from the pr he made
https://github.com/mnbroatch/bondage.js/commits/master/
https://www.npmjs.com/package/@mnbroatch/bondage
I will try using the version from his branch instead

**Comment by blurymind** [comment]
closing this as the upgraded yarn 2 spec implementation turned out to have a bunch of bugs. Stability is more important than features im afraid :(

**Pull request closed without merging**
