### PR TITLE
Add a button to report extension issues

### PR DESCRIPTION
**Pull request by D8H**
https://gdevelop-storybook.s3.amazonaws.com/report-extension-issue/latest/index.html?path=/story/assetstore-extensionstore-extensioninstalldialog--already-installed

### CODE REVIEW

**Review by 4ian — APPROVED** [review]

**Comment by D8H** [comment]
Should we merge it with broken stories and try to fix them later?

**Comment by ClementPasteau** [comment]
Which stories are broken @D8H ?
Ideally we'd fix them in the same PR

**Comment by D8H** [comment]
> Which stories are broken @D8H ? Ideally we'd fix them in the same PR

Storybook have an issue with this dependency:
```
import { diff } from 'semver/functions/diff';
```
So the view can't compare extension version and default on a result.
```
TypeError: Object(...) is not a function
    getUpdateMetadataFromVersions UseExtensionUpdates.js:20
    useExtensionUpdate UseExtensionUpdates.js:58
```
It's not new to this PR. It already doesn't work on master.

**Comment by ClementPasteau** [comment]
ok let's merge then!

**Pull request merged**
