### PR TITLE
Fix alignment in variables editor

### PR DESCRIPTION
**Pull request by Bouh**
Don't show in changelog

image

### CODE REVIEW

**Comment by 4ian** [comment]
The idea of this alignment was to keep the variable name at the top when there are multiple lines:
image

I don't have strong feelings on this, but what do you think?
We could also maybe reduce the margins (and size?) for the true/false buttons

**Comment by 4ian** [comment]
Try to remove the margin, set to 5 currently, on the True/False button and add noMargin to the Line having them, and this should give something like:
image

Space taken by the line is now not higher than a number/string :)

**Comment by Bouh** [comment]
True/False are too near of the value under it.
Margin left and right on True/False can be keeped, we are not on a switch component. even if we have one choice possible.

The idea is to ventilate a little the inputs, everything is glued too much and not aligned.

**Comment by 4ian** [comment]
We can give a bit more margins to the text fields then? To have every line (apart from the multiline texts) with the same height?

**Comment by Bouh** [comment]
noMargin on the line wrapping the booleans is better, but the issue persist the name of the variable are not aligned on the one line value or booleans. same for icons on right.

**Comment by 4ian** [comment]
Alright then, I think this could be solved by margins around the text fields (add a `Line` or something like this), but I'm ok going back to properly centered rows for now

**Pull request merged**
