### PR TITLE
Add links to documentation

### PR DESCRIPTION
**Pull request by piyushpalawat99**
Add the link to the documentation of layers and cameras

Edit: Link to documentation for external layouts has been added too (Used the same documentation as GD4) and both have been added as a sub page for scene editor :)

### CODE REVIEW

**Comment by 4ian** [comment]
Thanks for this :) 
Do you think this page would be better put as a sub page of http://wiki.compilgames.net/doku.php/gdevelop5/interface/scene-editor?

**Comment by piyushpalawat99** [comment]
Even though the category is related to the scene editor, it cannot be accessed without using actions/conditions and that's the reason I've kept it in the "All other interfaces". But if you want me to, I can move it there.

Also, I'm unable to see a "Help for this action/condition" button at the bottom of the dialog in my build. I don't think there are any other files that need to be altered. Is there anything I'm missing?

While going through the code, I found many actions that I have never encountered in the software. Is there any particular reason for it?

For the documentation part, there are a few things that need to be fixed and I've been trying to resolve them but to no avail. I'll contact you soon regarding the same.

**Comment by 4ian** [comment]
> Also, I'm unable to see a "Help for this action/condition" button at the bottom of the dialog in my build. I don't think there are any other files that need to be altered. Is there anything I'm missing?

This is a C++ file so you need to recompile it to see the changes: https://github.com/4ian/GDevelop/blob/master/GDevelop.js/Readme.md (it's more complex than just having Node.js though, also I've only tried on Linux and macOS)

> While going through the code, I found many actions that I have never encountered in the software. Is there any particular reason for it?

If `SetHidden()` is called, they are probably deprecate actions only there for backward compatibility. Otherwise they are somewhere in the app :)

**Comment by piyushpalawat99** [comment]
> This is a C++ file so you need to recompile it to see the changes: https://github.com/4ian/GDevelop/blob/master/GDevelop.js/Readme.md (it's more complex than just having Node.js though, also I've only tried on Linux and macOS)

I recompiled the app using npm install followed by npm start but couldn't see the change being reflected (must be an issue on my system)

> If `SetHidden()` is called, they are probably deprecate actions only there for backward compatibility. Otherwise they are somewhere in the app :)

The actions for which `MarkAsComplex()` is called are not in the app.

Also, should I change the documentation path to a sub page on scene editor?

**Comment by 4ian** [comment]
> I recompiled the app using npm install followed by npm start but couldn't see the change being reflected (must be an issue on my system)

Have you checked the link? :)

> Some actions for which MarkAsComplex() is called are also not in the app.

Yes, it's something that is not used currently :)

**Comment by piyushpalawat99** [comment]
I'm really sorry, I thought that it was the newIDE readme. I'll test it soon :)

**Comment by 4ian** [comment]
Thanks for the latest additions. I'll add links to these pages in the wiki left menu and will merge then.

**Comment by piyushpalawat99** [comment]
> Thanks for the latest additions.
Is it possible for you to go through them once as there is one topic that needs your help (Effect parameter in Layers and Cameras)? 

>  I'll add links to these pages in the wiki left menu and will merge then.
Yes, you can merge them as the changes can be done later too :)

**Comment by piyushpalawat99** [comment]
Also, I found a deserted [screenshot extension](http://wiki.compilgames.net/doku.php/gdevelop5/all-features/screenshot) page. Can you add a link to it too?

**Comment by 4ian** [comment]
> Also, I found a deserted screenshot extension page. Can you add a link to it too?

Added, and added the rest in the menu too :) 
Will merge now, thanks for the PR!

**Pull request merged**
