### PR TITLE
Rework fonts loading

### LINKED ISSUE #536: Problems with custom fonts
## 1. Custom fonts are not loaded in exported games and in preview

**5.0.0-beta42**
GDevelop5.0.0-beta42Print1

**Electron v2.0.3 x64**
Electronv2.0.3Print

## 2. Text objects with custom fonts are not displayed in Firefox

FirefoxPrint1

**Without custom font**
FirefoxPrint2

## Additional Information and Links
Windows 7 Home Premium SP1 x64
XAMPP 7.2.5-0

**game.json with custom font** https://pastebin.com/raw/AXGVGmqh
**game.json without custom font** https://pastebin.com/raw/NrVhjP5N
**Font** https://fonts.google.com/specimen/Righteous

### PR DESCRIPTION
**Pull request by 4ian**
Fix #536

Fonts will now be part of the game resources, like textures (images) and audio resources. This allow to wait for them to be loaded during the game initialization.

* Add FontManager to the game engine, used to load and get access to loaded fonts.
* Use fontfaceobserver library to detect when a font is loaded.
* Add FontResource as a resource, like AudioResource.
* Update the TextEditor to use a selector for fonts.
* Refactor ResourceSelector floating label text

TODO:
- [x] Fix remaining TODOs 
- [x] ~Add "Scan for new fonts/remove useless fonts" options in Resources editor.~ => Will do later or will let someone add this (cc @blurymind)
- [x] Add a list of public fonts to the web-app
- [x] Handle font resource in editor for rendering text objects
- [x] Handle font resource in Cocos2d-JS

### CODE REVIEW

**Comment by blurymind** [comment]
@4ian I can add the scan options if you want to :)
Btw does GD.js have a method for removing unused audio files? I was wondering about that in a previous push

**Comment by 4ian** [comment]
> Btw does GD.js have a method for removing unused audio files? I was wondering about that in a previous push

Not yet but this is part of this pull request ;) 

> I can add the scan commands to resource editor if you want to :)

Don't worry, I'll add them to this pull request as it should be fairly simple :)

**Comment by 4ian** [comment]
Well all things considered it's better to add the "Remove All Unused Audio" and "Remove All Unused Fonts" as well as "Scan for Audio" and "Scan for Fonts" after this pull request is merged to avoid doing again the work that you've done in your PR.

So feel free to add this once this is merged :)

**Comment by 4ian** [comment]
> Related, what do you think about a workaround for pixi to set the text non-smooth without too much trouble?, it's done changing the font size x4 and then scale down the text object x4 (scale.x = scale.y = 0.25).

Well looks like a work around indeed, wonder is there is no other solution at all?

**Comment by 4ian** [comment]
Ready and tested :) 
Existing games will continue to work as before (font name in the text object will act as the font filename if no font resource is found) but to benefit from font loading at the start of the game, you should add the font using the selector now available in the Text editor (this will add a font to the resources, like audio and textures :))

**Pull request merged**
